### ISSUE TITLE
More test cases

### ISSUE THREAD

**Issue by rauchg** [zeit/styled-jsx#1]
- [x] Multiple style tags per component
- [x] Multiple components with styles per file
- [ ] Extensive error handling

**Comment by giuseppeg** [comment]
Worth adding a test for JSX partials like the following:

```jsx
class Test extend PureComponent {
   renderItem(item) {
      return <li key={item.id}>{item.value}</li>
   }
   render() {
      return <ul>{this.props.items.map(this.renderItem)}</ul>
   }
}
```

Maybe it already works?

**Comment by adamyonk** [comment]
If you could document a bit how you set up the fixtures and run tests in this project, I'd be happy to write some tests for this stuff!

**Comment by rauchg** [comment]
@giuseppeg I did imagine that situation. It should work, but it's not tested. Obviously has a slight perf impact as it calls `inject` many times, but that should be ok since we dedupe with an O(1) check

@adamyonk it's simple. Create two files under `fixtures/` (one for the expected result and one for the source), and then set up a corresponding test in `test/index.js`. For more complicated tests like error handling an out file is not needed

**Comment by adamyonk** [comment]
OK, great! Thanks for the info. I can start putting something together once I get #12 figured out.

**Comment by giuseppeg** [comment]
created a separate issue for Error handling #128
