### ISSUE TITLE
Make semicolon optional?

### ISSUE THREAD

**Issue by bassbump** [zeit/styled-jsx#103]
Since with ES6 and all of zeits packages it's become standard to not use the semicolon, wouldn't it be consistent to also apply this practise in the styled-jsx?

**Comment by giuseppeg** [comment]
We are not using semicolons in js. What do you mean?

**Comment by bassbump** [comment]
```
<style jsx>{`
  .page-header {
    background-color: #000
    height: 60px
  }
`}</style>
```

instead of 
```
<style jsx>{`
  .page-header {
    background-color: #000;
    height: 60px;
  }
`}</style>
```

**Comment by nkzawa** [comment]
Semicolon of css is not optional except last declarations in blocks.

**Comment by giuseppeg** [comment]
ditto
