### ISSUE TITLE
exported variables don't seem to work with hot reloading

### ISSUE THREAD

**Issue by bassbump** [zeit/styled-jsx#104]
I have the following in Navigation.js component

```
.site-nav__list {
  ${utils.clearlist}
  overflow: visible;
}
```

and the following in theme.js

```
export const utils = {
 'clearlist':
   `list-style: none;
    padding: 0;
    margin: 0;`
}
```

This works on page reload, but doesn't work with hot reloading if I change something in theme.js

Is this intended? Not sure if I should post this here or in next.js?

**Comment by giuseppeg** [comment]
Yup can you move this issue to the Next.js repo?
