### ISSUE TITLE
Different components get the same jsx id if using interpolation.

### ISSUE THREAD

**Issue by lixiaoyan** [zeit/styled-jsx#107]
For example:

``` javascript
// header.js
const Header = () => (
  <div className="root">
    <style jsx>{`
      .root {
        position: fixed;
        height: ${theme.height};
      }
    `}</style>
  </div>
);

// main.js
const Main = () => (
  <div className="root">
    <style jsx>{`
      .root {
        padding-top: ${theme.height};
      }
    `}</style>
  </div>
);
```

Both of them using interpolation in styles, and they get the same jsx id `[data-jsx="3533501187"]`.

**Comment by samjbmason** [comment]
The fix released for this doesn't seem to have worked Im running the latest `next@beta-2.0.24` and Im still getting the same `data-jsx` values on every component when using expression.

**Comment by giuseppeg** [comment]
We clarified on slack, @samjbmason had some unrelated caching issue. The patch works as expected :)
