### ISSUE TITLE
SyntaxError: import

### ISSUE THREAD

**Issue by adamyonk** [zeit/styled-jsx#11]
In a non-`next.js` project, after installing `styled-jsx` and adding `"styled-jsx/babel"` to the  `plugins` array in my `.babelrc` file, I'm seeing the following error on compilation:

```
Module build failed: /my_project/node_modules/styled-jsx/babel.js:1
(function (exports, require, module, __filename, __dirname) { import jsx from 'babel-plugin-syntax-jsx'
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

Is there something else needed in the babel config to get this to work?

**Comment by hzoo** [comment]
Were fixing this now. It's publishing import export rather than compiling it atm. https://unpkg.com/styled-jsx@0.0.1/

**Comment by leo** [comment]
@adamyonk Does 0.0.3 work?

**Comment by adamyonk** [comment]
Fixed!
