### ISSUE TITLE
Adding className to non-dom elements

### ISSUE THREAD

**Issue by timsuchanek** [zeit/styled-jsx#111]
`styled-jsx` works fine, however, as soon as we have a component like an `<Icon />` component that we want to customize with `<Icon className='invisible' />`, the `className` is not passed down.
This is a huge problem, as we use a lot of these components and now our workaround is to use `global` all the time, which removes the isolation.
With `styled-components` you don't have that problem, there you can do ```styled(Icon)`...` ```

Is there a better approach than using `global`?
Thank you!

**Comment by giuseppeg** [comment]
Do you mean that the `className` prop is not passed down or are you asking if it is possible to pass down `[data-jsx="currentComponentID"]` to `Icon`?

**Comment by timsuchanek** [comment]
I'm asking if it is possible to pass down `[data-jsx="currentComponentID"]` to `Icon`

**Comment by nkzawa** [comment]
This is intentionally removed by https://github.com/zeit/styled-jsx/issues/71

Actually, I also feel this is inconvenient in some situations, but `closestparent :global(> *) { color: red; }` is a way to do something similar for now.

https://github.com/zeit/styled-jsx/issues/66#issuecomment-270601315

**Comment by giuseppeg** [comment]
Updated my comment, it is `closestparent > :global(*) {}`

One problem with the above is that `*` doesn't affect the selector specificity which sometimes it is what we want instead. A workaround is to target children by tag, class, attribute or id e.g. `closestparent > :global(div)`

The reason why I think that passing down the `data-jsx` attribute with the parent id `currentComponentID` is not a good idea is that:

* the child component might already have its own `data-jsx` attribute (elements can't have duplicate attributes by spec) and we don't have a way set or override it 
* setting the data attribute on the child component root doesn't buy you much – you'd still need to target descendants with `global` if you want to style them.

**Comment by nkzawa** [comment]
> the child component might already have its own data-jsx attribute (elements can't have duplicate attributes by spec) and we don't have a way set or override it

I think we can avoid this if we change `data-jsx="123"` to `data-jsx-123` ?

> setting the data attribute on the child component root doesn't buy you much – you'd still need to target descendants with global if you want to style them.

I think this is not required when you assume webcomponent-like behaviors. Style for top level element is enough.

Though I am not trying to say we should revert it. I just want to have a clean alternative way.

**Comment by giuseppeg** [comment]
> I think we can avoid this if we change data-jsx="123" to data-jsx-123 ?

Yep that could work (probably better call it `data-jsx-parent={123}`) although we'd need to rewrite every react component to set that attribute

**Comment by timsuchanek** [comment]
Hey @giuseppeg thanks for that workaround!
Indeed `:global(.child-class)` works perfectly, I'm even using it with styled-jsx-postcss and cssnext.
I also just realized that it's described [here in the README](https://github.com/zeit/styled-jsx#global-selectors).
So for me it's resolved, we can close it.
This passing down thing is not needed and I like this parent class scoping.
