### ISSUE TITLE
“>” turning into &gt;

### ISSUE THREAD

**Issue by rolz** [zeit/styled-jsx#112]
“>” gets converted to html entity.
Hover only works on page hot-reload. Does not work on normal page load. 
Also says 'Warning: Unknown prop `jsx` on <style> tag.'.

Using nextjs 2.0.0.

```
container:hover > item {
  background: #f2f2f2;
}
```

turns into 

```
container:hover &gt; item {
  background: #f2f2f2;
}
```

**Comment by giuseppeg** [comment]
Are you sure that you are using `next@^2.0.0-beta.24` ? 
`Warning: Unknown prop jsx on <style> tag.` usually means that styles are not transpiled at all

**Comment by rolz** [comment]
Yes I am use `next@^2.0.0-beta.24` with `preact-compat`, like in the [example](https://github.com/zeit/next.js/tree/master/examples/using-preact)

**Comment by timmywil** [comment]
I had the same issue, but my styled-jsx was in fact not running. It was due to my custom babel config that didn't include styled-jsx babel plugin.

**Comment by rolz** [comment]
@timmywil Thank you very much!
