### ISSUE TITLE
Is there a way to use this with create-react-app without ejecting?

### ISSUE THREAD

**Issue by stevensacks** [zeit/styled-jsx#118]
STS

**Comment by giuseppeg** [comment]
probably you can do something similar to this https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc but in your case you'd install babel and styled-jsx to transpile css before starting the app

**Comment by comerc** [comment]
[Yes!](https://github.com/timarney/react-app-rewired/issues/46)

**Comment by fabioespinosa** [comment]
How can you use it with an ejected create-react-app? Please help!

Please answer on StackOverflow, so the answer gets more visibility 👍 

https://stackoverflow.com/questions/49156164/add-styled-jsx-to-ejected-create-react-app-config

**Comment by fabioespinosa** [comment]
Just answered my own question above in the stackoverflow link 👍
