### ISSUE TITLE
Allow whitespace in expressions inside template literals

### ISSUE THREAD

**Issue by nikvm** [zeit/styled-jsx#126]
As of now expressions like the following won't get replaced because I'm using spaces  inside the curly braces.

```JavaScript
<script jsx>{`
  p {
    color: ${ colors.primary }
  }
`}</script>
```
It has to be written as `${colors.primary}`.

Also note that the README's [demo](https://github.com/zeit/styled-jsx#constants-and-config) is using that style.

I believe this is the corresponding source: https://github.com/zeit/styled-jsx/blob/45ba8542f93d5caee262ead08a584a25767eacd5/src/babel.js#L108.

**Comment by giuseppeg** [comment]
@nikvm good catch, can you send a pr to fix this? It should be a matter of replacing using a regular expression (keep the initial for later tho). 

I believe that you need a regexp at line 108 which you will use at line 115

```js
new RegExp(`\\$\\{\\s*${e.getSource()}\\s*\\}`)
```

**Comment by nikvm** [comment]
Sure. I should find some time the coming days.
