### ISSUE TITLE
Extensive error handling

### ISSUE THREAD

**Issue by giuseppeg** [zeit/styled-jsx#128]
It would be nice to have even more explanatory error messages/handling.

**Comment by nikvm** [comment]
Can we start compiling a checklist with references/to-dos? I'd ❤️ to improve on error handling. Though it's still a little to vague for me. 🙉

**Comment by giuseppeg** [comment]
@nikvm honestly I am not sure either, I just moved this to its own issue from #1 .

I think that we should try to scan the babel transform and see if there are critical spots where it'd make sense to handle possible failures / and throw with meaningful and helpful messages.
