### ISSUE TITLE
Allow styling of components

### ISSUE THREAD

**Issue by lorensr** [zeit/styled-jsx#142]
Both of these, when rendered, become an unstyled div:

```jsx
import Paper from 'material-ui/Paper'

<Paper>
                <style jsx>{`
                  div {
                    background: red;
                  }
                `}</style>
</Paper>
```

```jsx
<Paper>
                <style jsx>{`
                  Paper {
                    background: red;
                  }
                `}</style>
</Paper>
```

It would be nice if there were a way to style the div that `<Paper>` becomes.

**Comment by zachdixon** [comment]
I was able to accomplish something similar via [global selectors](https://github.com/zeit/styled-jsx#global-selectors). For example

```
<div className="root">
    <Paper className="my-paper">
    ...
    </Paper>

    <style jsx>{`
        .root :global(.my-paper) {...}
    `}</style>
</div>
```

`.root` will have the scoped selector, but `.my-paper` won't, so I believe it basically turns the rule into something like:
`.root[data-jsx="1234"] .my-paper {...}`

**Comment by lorensr** [comment]
Thanks, that works. Would be nice to have something simpler like my examples though.

**Comment by rauchg** [comment]
@lorensr I'm trying to stick as much as possible to "just CSS". Since we're inverting the CSS model (everything is scoped by default, no globals), we needed syntax for opting into globals, and that's the only reason I broke that rule with `:global`.

So, arguably our current solution is _simpler_, just not necessarily _easier_. I'd be open to exploring that model though in other modules, or maybe a fork of `styled-jsx`, and see how it goes. There's a lot to explore. Thank you

**Comment by rauchg** [comment]
Thanks @zachdixon for helping out. I purposefully also put this example in the README, referencing how I'd style `react-select`:

![image](https://cloud.githubusercontent.com/assets/13041/23728068/b7f96362-040f-11e7-838d-f0e20864f04c.png)

https://github.com/zeit/styled-jsx#global-selectors

**Comment by cdeutsch** [comment]
This still really needs improvement (or you should switch away from `styled-jsx`)

When you're using something like `material-ui` and you need to make a tiny tweak, it's not uncommon for the whole component to be nested components; and there are zero acceptable ways to style it with `styled-jsx`

**Comment by fillipvt** [comment]
Is there a chance to reopen this?

Possible use case is individually styling one of components without impacting the general styles globally.

I managed to do this by using `css.resolve` from `styled-jsx/css` but I'm totally unsure if that's the way to go.

**Comment by eric-burel** [comment]
Hi, I also struggle to find the best pattern to handle global styling. I try to favour styled-jsx against Material UI as much as possible, so I can mix non material-ui components with mui components and have consistent styling.

This is how I try to define the global style, and override MUI defaults.

```js
const AppLayout = ({ children }: AppLayoutProps) => (
  <div className="global-style">
    {children}
    <style jsx global>{`
      .global-style h1, .global-style .MuiTypographi-h1 {
        font-size: 3.815em;
        /* 61px */
      }
      h2, .MuiTypography-h2 {
        font-size: 2.441em;
        /* 29px */
      }
...
```
The first one will work, but feels clumsy. A palliative would be using PostCSS, which allows a cleaner nesting. Ok, but not really simple.

The second one won't have enough specificity, Material UI style is added later in the tree so I can't override it.

Third alternative is using theme overrides. Works perfect, but it makes me duplicate my style, both for `.MuiTypography-h1` (using overrides) and `h1` (using styled-jsx global mode).$

Any thoughts on this?

**Comment by eric-burel** [comment]
PostCSS with nesting is better, as you just wrap the whole style with a class to get +1 specificity, but breaks VS code. There does not seem to be a "styled-jsx + postcss" plugin yet.

```
<div className="global">
    {children}
    <style jsx global>{`
      /* Typescale */
      .global {
        .MuiTypography-h1 {
          font-size: 16px;
        }
...
```

**Comment by eric-burel** [comment]
Actually when I don't use a `div` wrapper, it doesn't work.

```js
export const Button = (props: ButtonProps) => {
  const { preferredTechnology, ...muiButtonProps } = props;
  return (
    <MuiButton
      {...muiButtonProps}
      className={clsx("vns-button", props.className)}
    >
      {props.children}
      <style jsx>
        {`
          & :global(.MuiButton-root) {
            color: ${technologyToColor[preferredTechnology] || colors.blueNext};
          }
        `}
      </style>
    </MuiButton>
  );
};
```
Also tried a simpler style, eg `button { color: red }`, it is not applied to the button generated by Material UI.

![image](https://user-images.githubusercontent.com/7983005/86451604-6e44f100-bd1b-11ea-89bf-82b47b3a1589.png)

It works if I use a basic HTML button however, so the style or my components do not seem to be faulty.

@oliviertassinari do you have any insight on this? Your example is using a `div`, so it works ok, but I do not find a pattern that works eg if you wanted to render the Typography directly in order to create a "StyledTypography".

**Comment by oliviertassinari** [comment]
> after a few more tries, I indeed can't find a solution without a wrapper element :(

@eric-burel I came to the same conclusion when experimenting with different options.
