### ISSUE TITLE
Support Simpler Syntax

### ISSUE THREAD

**Issue by arunoda** [zeit/styled-jsx#15]
Why don't we use the familiar syntax like this:

```html
 <style jsx>
      p {
        color: red;
      }
 </style>
```

But this:

```html
 <style jsx>{`
      p {
        color: red;
      }
 `}</style>
```

**Comment by bogas04** [comment]
Wouldn't JSX compiler freak out seeing {} inside a JSX tag ? And what if I want to use 

```jsx
color: {`theme().color`}
```

how will your change support that ?

I personally feel that using template string is the right way as it allows you to extract it to variable(s), which would likely be the case if you have more than 4-5 style rules. The above convenience doesn't serve much purpose and would require a lot of change to the babel plugin IMO.

**Comment by rauchg** [comment]
@bogas04 is right. I, too, wanted that to be possible, but we got pretty close!

**Comment by arunoda** [comment]
Yep. Makes sense.
