### ISSUE TITLE
About styling tags in dynamic content

### ISSUE THREAD

**Issue by iamjacks** [zeit/styled-jsx#154]
The API I'm working with retrieves blog posts which have html tags (h1,h2..., p, blockquote etc.), so I have to use `dangerouslySetInnerHTML` to render them. I'm using a global selector to target those tags. `.blog-post p, .blog-post h1 ...`. Is this the best approach for this scenario? Curious how others handle this sort of thing.

**Comment by giuseppeg** [comment]
@iamjacks yep that's how I would do that use a scoped selector and `:global` to target the dynamic children.

```css
.blog-post :global(h1) { }
.blog-post :global(h2) { }
```

I use [a similar approach](https://github.com/giuseppeg/giuseppeg.github.com/blob/master/assets/components/copy/index.css) in my personal blog.
