### ISSUE TITLE
Doesn't work with Rollup

### ISSUE THREAD

**Issue by foisonocean** [zeit/styled-jsx#159]

**Comment by jimthedev** [comment]
Does this mean that if you want to create a library of distributable components bundled with rollup then you can't?

**Comment by giuseppeg** [comment]
@jimthedev have you tried this? @foisonocean can you provide more details?

**Comment by jimthedev** [comment]
I haven't tried it. Was curious.

**Comment by jimthedev** [comment]
I know next.js 5 has pretty much doubled down on webpack for front and back end bundling so I'm sure rollup isn't their top priority.

**Comment by Tomekmularczyk** [comment]
Hi,

I actually posted a similar issue [here](https://github.com/rollup/rollup-plugin-babel/issues/202).
I want to create a components library with styled-jsx (as an external dependency) and rollup. But I end up bundling a lot of code. 

[here is the minimal repo demonstrating the problem.](https://github.com/Tomekmularczyk/react-package-rollup/tree/with-styled-jsx)

**Comment by giuseppeg** [comment]
can you put together a minimal repo that includes styled-jsx? fwiw styled-jsx should be a peerDependency

**Comment by Tomekmularczyk** [comment]
@giuseppeg in my previous answer I’ve included a link to the repo.

https://github.com/Tomekmularczyk/react-package-rollup/tree/with-styled-jsx

**Comment by giuseppeg** [comment]
@Tomekmularczyk sorry I was looking at the wrong link :) Thank you

**Comment by giuseppeg** [comment]
@Tomekmularczyk you need to declare all the `styled-jsx/*` imports as external: 

```
external: id => /^react|styled-jsx/.test(id)
```

**Comment by giuseppeg** [comment]
you might also want to set the `NODE_ENV` to `production`

`package.json`
```json
{
  "scripts": {
    "build": "NODE_ENV=production rollup -c"
  }
}
```

**Comment by Tomekmularczyk** [comment]
@giuseppeg Thank you! <3

**Comment by Tomekmularczyk** [comment]
Oh, so depending if a client is using development/production environment I should return proper file. Thanks again!

**Comment by afzal273** [comment]
I'm unable to access the test repo, I'm looking for a working config with rollup or webpack for a react component library with styled-jsx. Could you please re-share a working link?

**Comment by giuseppeg** [comment]
@Tomekmularczyk it would be cool to write a blog post about this! Let me know in case you have time and want to do this :)

**Comment by giuseppeg** [comment]
If you have a personal blog you could just post it there :) As for the guidelines I guess your workflow seems pretty good to me so I'd just describe that with an example :)

**Comment by afzal273** [comment]
Thanks much @Tomekmularczyk , do you also have an example for bundling a component library that uses styled-jsx with webpack instead of rollup? We use webpack and would be great to have it working for webpack as well!

**Comment by Tomekmularczyk** [comment]
@afzal273 there's already an [article on that.](https://medium.com/@efreyreg/create-react-component-libraries-with-storybook-and-styled-jsx-8999f423f06b)

**Comment by Tomekmularczyk** [comment]
@giuseppeg how can I contact you about that article? I would like you to review it.

**Comment by giuseppeg** [comment]
@Tomekmularczyk I am on Slack as `g` https://zeit.chat or you can dm me on twitter https://twitter.com/giuseppegurgone

**Comment by Tomekmularczyk** [comment]
I have posted it on Medium. Thanks.

https://medium.com/@tomaszmularczyk89/guide-to-building-a-react-components-library-with-rollup-and-styled-jsx-694ec66bd2

**Comment by giuseppeg** [comment]
awesome! If you tweet that I'll retweet :) Also feel free to submit a PR to add a link to this under the FAQ section of the main readme.md

**Comment by Tomekmularczyk** [comment]
@giuseppeg sure I’ll do that. Thanks again!

**Comment by DominicTobias** [comment]
It doesn't work unless styled-jsx is declared external, that's a shame. Don't want to stipulate that to users I guess I'll have to switch to Webpack and hope they release ESM support in v5 not to long after it is stable

**Comment by DominicTobias** [comment]
Edit: The library also doesn't work with Webpack if react is declared as an external module for library components like so:

```
externals: {
    react: {
      root: 'React',
      commonjs: 'react',
      commonjs2: 'react',
      amd: 'react',
    },
  },
```

So basically this lib doesn't work at all for a library of components. Shame as Emotion does but I don't like the way it wraps every component in Consumers and every styled component in a HOC, that is an efficiency dog poop.

**Comment by sw-yx** [comment]
for the benefit of future pple who come across this

i declared styled-jsx external, then didnt know how to get styled-jsx running (i dont have enough rollup-fu to take it from there).

so in order to do it i... inlined all of styled-jsx into my index.html, so that it would get picked up as an external module properly.

https://github.com/sw-yx/rollup-react-boilerplate/commit/02cee453c0c60df63a138aae9e268a6738a1e03d

here's hoping nobody else needs to do what i did. it felt dirty af but im on a deadline and didnt know what else to do

**Comment by jacksteamdev** [comment]
Just to be clear, this issue is about using `styled-jsx` in a _library of distributable components_ bundled with Rollup. You can do that by declaring all `styled-jsx` imports as external:

```javascript
// rollup.config.js

export default {
  ...
  external: id => /^react|styled-jsx/.test(id),
  ...
}
```

It is not about using `styled-jsx` in an app bundled with Rollup. That is being tracked in #588 and #669.
