### ISSUE TITLE
A failed attempt to enable syntax highlight for vscode and a temporary solution

### ISSUE THREAD

**Issue by xekri** [zeit/styled-jsx#161]
I was trying to enable syntax highlight for vscode by changing vscode's built-in extension `javascript`. 
The extension has a directory called `syntaxes`, and the file `JavaScript.tmLanguage.json` inside is the colorize configuration, which use [Language Grammars from TextMate](https://manual.macromates.com/en/language_grammars).
I added the following code to the end of json body
```json
{
  "jsx-style": {
    "begin": "(?<=<style jsx>{)|(?<=<style jsx global>{)",
    "end": "(</)((?i:style))(>)(?:\\s*\\n)?",
    "patterns": [
      {
        "include": "source.css"
      }
    ]
  }
}
```
The pattern `begin` is modified from atom's language-babel setting.
The pattern `end` is modified from a html tmLanguage file.
It didn't work. I don't know how to debug the syntax highlight. I guess it has some conflicts with original javascript highlight syntaxes.

Luckily, I found this extension [ES6 Template Literal Editor](https://marketplace.visualstudio.com/items?itemName=plievone.vscode-template-literal-editor) that can let me choose which language is inside the template literal and edit it. It's rather convenient than before. I hope it's useful to others, and it can be written into the readme.md.

**Comment by xekri** [comment]
I wrote a language extension for jsx styled.
package.json: 
```json
{
	"name": "vscode-jsx-styled",
	"displayName": "vscode-jsx-styled",
	"description": "Syntax highlighting for styled-jsx",
	"version": "0.0.1",
	"publisher": "xekri",
	"license": "MIT",
	"engines": {
		"vscode": "^1.5.0"
	},
	"categories": [
		"Languages"
	],
	"contributes": {
		"languages": [
			{
				"id": "source.jsx.styled",
				"aliases": [
					"CSS (jsx styled)"
				],
				"configuration": "./css-styled.configuration.json"
			}
		],
		"grammars": [
			{
				"injectTo": [
					"source.js",
					"source.ts",
					"source.jsx",
					"source.tsx"
				],
				"scopeName": "styled-jsx",
				"path": "./syntaxes/styled-jsx.json"
			}
		]
	}
}
```
./syntaxes/styled-jsx.json: 
```json
{
	"fileTypes": ["js", "jsx", "ts", "tsx"],
	"injectionSelector": "L:source -comment",
	"patterns": [
    {
      "contentName": "source.css.styled",
      "begin": "\\s*+((?<=<style jsx>{)|(?<=<style jsx global>{))\\s*(`)",
      "beginCaptures": {
        "1": { "name": "entity.name.tag.js" },
        "2": { "name": "punctuation.definition.quasi.begin.js" }
      },
      "end": "\\s*(?<=[^\\\\]\\\\\\\\|[^\\\\]|^\\\\\\\\|^)((`))",
      "endCaptures": {
        "1": { "name": "punctuation.definition.quasi.end.js" }
      },
      "patterns": [
        { "include": "source.css.styled" }
      ]
    }
	],
	"scopeName": "styled-jsx"
}
```
(source.css.styled is imported by [vscode-styled-components](https://github.com/styled-components/vscode-styled-components), so you should install it first.
These rules are generated by language-babel package in atom, as written in the README.md file.

**Comment by tuespetre** [comment]
*Thank you* for this example of using `injectTo`!

**Comment by jcklpe** [comment]
@tuespetre  Is it just me or does it seem no one uses the injectTo method even though it's the recommended way of doing things according to vscode's documentation? Why is that?

**Comment by tuespetre** [comment]
@jcklpe no clue, I don't even remember what I needed it for or why I commented on this to be honest 🤷‍♂️
