### ISSUE TITLE
Use in component <style jsx>， repeat output

### ISSUE THREAD

**Issue by durongzhang** [zeit/styled-jsx#166]
I have a problem

Use of a component <style jsx>, loop this component repeat output

A.js
```js
export default () => (
  <div>
      11111
      <style jsx>{`
         .content{padding: 10px}
     `}</style>
  </div>
)
```

index.js
```js
import A from 'A';

const arr = [1,2,3]

export default () => (
  <div>
    2222222
    arr.map((obj, key) => {
    return  <A  key={key}  />
  })
</div>
)
````
Where the contents of the <A /> component <style  jsx> will be exported 3 times;

How to avoid this problem?

**Comment by giuseppeg** [comment]
What do you mean by exported 3 times? Behind the scenes we dedupe styles so styled-jsx will only render a single style tag for `A.js`

**Comment by durongzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/15725537/24734905/ad7e514a-1ab2-11e7-912e-92a84204b4c8.png)
Style is repeated

**Comment by giuseppeg** [comment]
@durongzhang selectors don't seem to be scoped (you should get `.content[data-jsx="somenumber"]`). Which version of styled-jsx are you using? Are you using Next.js `1.x` by any chance?

**Comment by durongzhang** [comment]
I'm using next.js 2.0.0

**Comment by giuseppeg** [comment]
@durongzhang odd, can you push your project or a test app to github so that I can take a look?

**Comment by leesiongchan** [comment]
Are you using custom `.babelrc` and forget in include `next/babel` preset? 

https://github.com/zeit/next.js/blob/master/examples/with-custom-babel-config/.babelrc

**Comment by anongit** [comment]
Had the same problem, the issue was with tsconfig.json:
```diff
-    "module": "none",
-    "jsx": "react",
+    "module": "esnext",
+    "jsx": "preserve",
```
