### ISSUE TITLE
[feature request] Support nested syntax (a la Sass)

### ISSUE THREAD

**Issue by corysimmons** [zeit/styled-jsx#171]
```jsx
<style jsx>{`
  div {
    background: orange;

    span {
      background: pink;
    }
  }
`}</style>
```

Doesn't seem like it'd hurt the philosophy of styled-jsx, and it's just nice tbqh.

**Comment by giuseppeg** [comment]
We want to stick with CSS standard – the only exception being `:global` which we can use to opt out scoped styles on occasion.

I made [styled-jsx-postcss](https://github.com/giuseppeg/styled-jsx-postcss) which should let you add nesting support. Keep in mind though that I don't have a lot of time to maintain it so sometimes it could take a while to get the same features as styled-jsx latest.

**Comment by corysimmons** [comment]
Sounds perfect, thank you!

>I don't have a lot of time to maintain it

Damn, the possibilities of PostCSS in styled-jsx are endless.
