### ISSUE TITLE
Help needed: Styling shared components

### ISSUE THREAD

**Issue by khankuan** [zeit/styled-jsx#172]
Hi, I have the following view that I am unable to style:
```
const MyButton = () => (
  <button className="root">MyButton<style jsx>{`.root { background: red }`}</style></button>
)

const MyView = () => (
  <div>
    <style jsx>{`
      .button-1 {
        color: green;
      }
      .button-2 {
        color: blue;
      }
    `}</style>
    <MyButton className="button-1" />
    <MyButton className="button-2" />
  </div>
)

```
The color styling does not seem to apply to the button. I then tried:
```
const MyView = () => (
  <div>
    <MyButton className="button-1">
      <style jsx>{`
        .button-1 {
          color: green;
        }
      `}</style>
    </MyButton>
    <MyButton className="button-2">
      <style jsx>{`
        .button-2 {
          color: blue;
        }
      `}</style>
    </MyButton>
  </div>
)
```
but got an error on babel `Invalid attempt to destructure non-iterable instance`. 

Neither did this worked:
```
const MyButton = () => (
  <button className="root">MyButton<style jsx>{`.root { background: red }`}</style></button>
)

const MyButton1 = () => (
  <MyButton className="my-button-1">
    <style jsx>{`
      .my-button-1 {
        position: absolute;
        bottom: 20px;
        left: 20px;
      }
    `}</style>
  </MyButton>
)

const MyButton2 = () => (
  <MyButton className="my-button-2">
    <style jsx>{`
      .my-button-2 {
        position: absolute;
        bottom: 20px;
        right: 20px;
      }
    `}</style>
  </MyButton>
)
```

Thanks in advance!

**Comment by khankuan** [comment]
Hi, I've just saw that global has to be used in #111 and #66. I think that defeats the purpose of the library. It is also fairly common that we build components and parent components would use them but adding layout styles to them.

**Comment by giuseppeg** [comment]
@khankuan in React `<MyButton>` is not a real DOM element therefore when you pass a `className` to it you need to apply that to its internal elements explicitly and by hand. i.e.

```jsx

const MyButton = (props) => (
  <button className={props.className}>
     <span>{props.children}</span>
  </button>
)
```

If you didn't do so `<MyButton className="my-button-2">` won't propagate (apply) the class name `my-button-2`. This might be the case with 3rd parties components where you don't have control over the component's source code and therefore can't set the `className`.

Even if we were to support class names propagation where would you apply them? 
Assuming we set the `className` on the component root then that's not different than using `> :global(.root) { color: red }`.

**Comment by jmar777** [comment]
In terms of familiarity with styled-jsx, I'm in an early-research phase, so apologies if I'm missing something obvious. I'm curious how the `> :global(.root) { color: red }` advice translates to cases where the intention is to apply a className further down the DOM tree (potentially in a dynamic way that isn't part of a reliable, structural contract).

For example, consider a simple `Tabs` component that might be consumed something like:

```jsx
<Tabs className='my-tabs' tabLinkClassName='my-tab-link'>
  <Pane title='Foo' className='my-pane-1'>Hello</Pane>
  <Pane title='Bar' className='my-pane-2'>World!</Pane>
</Tabs>
```

...and might render to the following:

```jsx
<div class='my-tabs'>
  <ul>
    <li class='my-tab-link'>Foo</li>
    <li class='my-tab-link'>Bar</li>
  </ul>
  <ul>
    <li class='my-pane-1'>Hello</li>
    <li class='my-pane-2'>World!</li>
  </ul>
</div>
```

There's obviously also another hidden question in there about whether or not it's possible to grab a scoped className for use in a different attribute (`tabLinkClassName` in this case). Thanks for any insights!

**Comment by giuseppeg** [comment]
@jmar777 I would do something like this:

```jsx
const uniqueClass = '123' // maybe use uuid() 

const Toolbar = () => (
  <div>
    <Component className={uniqueClass}>
      <span>hello</span>
    </Component>
    <style jsx>{`
      div > :global(.${uniqueClass}) {
        color: hotpink
      }
    `}</style>
  </div>
)
```

**Comment by jmar777** [comment]
Thanks, @giuseppeg.

I think that helps me understand how I would pass a unique, non-munged className further down the tree, but what if the `Tabs` component from my example was also using styled-jsx. How does it attach the un-munged className without causing it to _then_ be munged?

I.e., if I pass `123` down to a child component that also uses styled-jsx, how does that chid component actually emit `class='123'`?

**Comment by giuseppeg** [comment]
@jmar777 you'd have to set it by hand like you would do for any other prop

**Comment by giuseppeg** [comment]
by the way if you need to pass it down to descendants (instead of children) you need to remove the `>` from the selector

**Comment by jmar777** [comment]
> you'd have to set it by hand like you would do for any other prop

I'm sensing that I'm missing something fundamental here, so apologies for the noise. :\

Here's a specific example with the point of confusion specified in the comments:

```jsx
const uniqueClass = '123';

const Parent = () => (
  <div>
    <Child buttonClassName={uniqueClass} />
  </div>
  <style jsx>{`
    div :global(.${uniqueClass}) {
      color: hotpink;
    }
  `}</style>
);

// ^ so far so good, i think

const Child = ({ buttonClassName }) => (
  <div>
    {/*
      In this case, `'the-button'` should be scoped for the
      Child component, whereas we need `buttonClassName`
      to remain un-munged, such that it can be styled from
      further up the tree.

      Unless styled-jsx leaves class names that aren't referenced
      in the <style> tag alone (?), it seems like both get munged?
    */}
    <button className={`the-button ${buttonClassName}`} />
  </div>
  <style jsx>{`
    .the-button {
      color: fuschia;
    }
  `}</style>
);
```

**Comment by jmar777** [comment]
@giuseppeg is there a possible workaround by putting an empty rule list inside the Child `<style>` tag? E.g.,

```jsx
const Child = ({ buttonClassName }) => (
  <div>
    <button className={`the-button ${buttonClassName}`} />
  </div>
  <style jsx>{`
    :global(.${buttonClassName}) {}    <-- maybe this kills the auto-munging?
    .the-button {
      color: fuschia;
    }
  `}</style>
);
```

**Comment by giuseppeg** [comment]
@jmar777 `Child` should not define `buttonClassName` styles, those come from the `Parent`. 
Imagine `Child` as a standalone component that accepts an optional `buttonClassName` prop.

styled-jsx doesn't rewrite `className` so you're good. 

What do you mean by munged by the way? scoped? :)
