### ISSUE TITLE
Targeting the root question

### ISSUE THREAD

**Issue by martinhorsky** [zeit/styled-jsx#174]
Hi, I have one simple question and I hope someone can explain me what section **Targeting the root** says.

https://github.com/zeit/styled-jsx#targeting-the-root
> Notice that the parent `<div>` above also gets a `data-jsx` atribute. We do this so that you can target the "root" element, in the same manner that `:host` works with Shadow DOM.

So, is there any way how to refer the root element without adding special class?

Thanks a lot

**Comment by giuseppeg** [comment]
> is there any way how to refer the root element without adding special class?

There isn't any special selector (like `:host`) to target the root

**Comment by martinhorsky** [comment]
Thanks for answer.

**Comment by treshugart** [comment]
Relates to #13.
