### ISSUE TITLE
'Not come from the closest scope' error when using constants

### ISSUE THREAD

**Issue by coluccini** [zeit/styled-jsx#176]
I'm getting the 'Expected var to not come from the closest scope' error even when the var it is not coming from the closest scope. It happens when the var is a index from a object that has the same name as one of the component props.
Ex:
```
const blue = { bg: 'blue', color: 'white' };
const orange = { bg: 'orange', color: 'white' };

const Button = ({ title, color }) => (
  <button className={color}>
    {title}
    <style jsx>{`
      button { border-radius: 5px; border: 1px solid; }
      .blue { background: ${blue.bg}; color: ${blue.color}; }
      .orange { background: ${orange.bg}; color: ${orange.color}; }
    `}</style>
  </button>
);

<Button title="go" color="blue" />
<Button title="cancel" color="orange" />
```

In that code, I'm getting the error when using ${blue.color}. If I change the name 'color' to something else (in the style object or the props), it work perfectly. Can this be a bug from the validator?

**Comment by giuseppeg** [comment]
yep it should be a bug
