### ISSUE TITLE
how to deal with 3rd party react elements?

### ISSUE THREAD

**Issue by thisguychris** [zeit/styled-jsx#18]
for example, <Link /> of react router for instance where the 3rd party controls how that element is rendered.

**Comment by rauchg** [comment]
I don't fully understand the question. Can you give me an example?

**Comment by tauren** [comment]
I just discovered this project, looks interesting! I'm not sure what @thisguychris is asking, but perhaps my question is similar. I'd be interested to see how easy it is to use something like https://github.com/JedWatson/react-select within an app that uses styled-jsx.

**Comment by thisguychris** [comment]
@rauchg to be clear, there are a lot of 3rd party React components in our ecosystem that people consume everyday.

Checking the api:
```javascript
export default () => (
  <div>
    <p>only this paragraph will get the style :O</p>
    { /* you can include <Component />s here that include
         other <p>s that don't get unexpected styles! */ }
    <style jsx>{`
      p {
        color: red;
      }
    `}</style>
  </div>
)
```

It seems the style object is inside, or adjacent to the component / jsx.  What happens if you want to style a React Component, say 

`<Link to={`/user/${user.id}`}>{user.name}</Link>`

How do you target the 'a' element of that react component?

Also this is how `styled-components` [api](https://github.com/styled-components/styled-components#third-party-components) looks like dealing with 3rd party components:

**Comment by rauchg** [comment]
I don't think `<Link>` in that example should be an element. It should decorate an element that you style statically:

```js
<Link><a>hi</a></Link>
<style jsx>{`
  a {
    color: pink
  }
`}</style>
```

**Comment by rauchg** [comment]
(we've used this pattern on zeit.co with very high success)

**Comment by rauchg** [comment]
For react-select, you could combine `optionClassName` with a glamor class:

```js
import css from 'next/css'
export default () => (
  <Select optionClassName={style} />
)
const style = css({ })
```

**Comment by thisguychris** [comment]
ah yes! if you can pass the classname then you can inject any arbitrary 3rd party react component, at least most.  Thanks @rauchg !

**Comment by rauchg** [comment]
Also, in view of this, there's a strong benefit to the discussed selector #26.

```js
export default () => (
  <div>
     <div className="select">
       <Select optionClassName="woot" />
     </div>
     <style jsx>{`
        .select >> .woot {
          color: red
        }
     `}</style>
  </div>
)
```

**Comment by thisguychris** [comment]
New API landed.  Very useful for 3rd party React components via passing classes.

```javascript
import Select from 'react-select'
export default () => (
  <div>
    <Select optionClassName="react-select" />

    <style jsx>{`
      /* "div" will be prefixed, but ".react-select" won't */
      div :global(.react-select) {
        color: red
      }
    `}</style>
  </div>
)
```

**Comment by reggi** [comment]
Just to help out any weary travelers with the `react-router` `<Link/> issue. This totally works.

```
import React from 'react'
import {Link} from 'react-router'

const UseLink = (props) => (
  <div>
    <Link className='my-link' to='/hi'>Hi</Link>
    <style jsx>{`
      div :global(.my-link) {
        color: red
      }
    `}</style>
  </div>
)
```
<img width="199" alt="screen shot 2017-06-05 at 2 25 21 pm" src="https://cloud.githubusercontent.com/assets/296798/26797460/f7227016-49fa-11e7-8624-f7ca43d2b1e5.png">
<img width="326" alt="screen shot 2017-06-05 at 2 25 32 pm" src="https://cloud.githubusercontent.com/assets/296798/26797461/f7239f22-49fa-11e7-9c44-9abbe942a0c7.png">
