### ISSUE TITLE
Is there a way to automagically find unused styles in styled-jsx?

### ISSUE THREAD

**Issue by valnub** [zeit/styled-jsx#183]
Is it possible to find unused styles, similar to how unused variables in ES6 can be found through warnings/treeshaking?

Example:

```jsx
export default () => (
  <div>
    <p>Hello</p>
    <style jsx>{`
      /* There is no span element, so there should
         be a warning about unused style during transpilation */
      span {
        color: red;
      }
    `}</style>
  </div>
)
```

**Comment by giuseppeg** [comment]
Potentially yes, but it would be a lot of work and quite complex, not sure if it is worth it.

**Comment by valnub** [comment]
I think it's absolutely worth it, why not have treeshaking for css if it's available for js? The last project I've been with has lots of unused css and we have a hard time to find this.

**Comment by giuseppeg** [comment]
It is a complex matter, because we would need to figure out which selectors apply to the component tree. I don't want to start this journey and build a matching engine.

If you styles go along with components the number of unused css should be minimal or very easy to track manually.

eg.

```jsx
const MyComponent = ({children}) => (
   <button>
       <span>{children}</span>
       <style jsx>{`
             button { display: block }
             div { color: red }  /* unused => remove it */
       `}</style>
   </button>
)
```

**Comment by giuseppeg** [comment]
Obviously PRs are welcome.
