### ISSUE TITLE
vim syntax highlighting?

### ISSUE THREAD

**Issue by danawoodman** [zeit/styled-jsx#184]
Would be great to have docs on supporting syntax highlighting in vim 😄

**Comment by pak11273** [comment]
I use this for jsx.  Has been working fine with styled-jsx too:

https://github.com/heavenshell/vim-prettier

**Comment by danawoodman** [comment]
@pak11273 that plugin just runs prettier doesn't it? I don't see how/why it would add syntax highlighting?

**Comment by pak11273** [comment]
no syntax highlighting.  I thought it did at first because I put the css values in quotes.  But I just found out those values don't need quotes.  I guess we have to wait til someone builds a plugin for it.

**Comment by alampros** [comment]
I'm _horrible_ with vim syntax, but I started messing around with the [vim-jsx](https://github.com/mxw/vim-jsx) syntax and made a *tiny* amount of progress on this. Here's what I modified:

```patch
diff --git after/syntax/jsx.vim after/syntax/jsx.vim
index 5813a67..69d6f9c 100644
--- after/syntax/jsx.vim
+++ after/syntax/jsx.vim
@@ -40,6 +40,11 @@ syn region xmlString contained start=+{+ end=++ contains=jsBlock,javascriptBlock
 syn region jsxChild contained start=+{+ end=++ contains=jsBlock,javascriptBlock
   \ extend
 
+syn include @CssSyntax $VIMRUNTIME/syntax/css.vim
+
+syn region styledJsxTag start=/<style.*jsx>/ end=+</style>+ containedin=jsxRegion contains=@CssSyntax,jsxCssTemplateString transparent
+syn region jsxCssTemplateString start=+`+ end=+`+ containedin=styledJsxTag contains=@CssSyntax
+
 " Highlight JSX regions as XML; recursively match.
 "
 " Note that we prohibit JSX tags from having a < or word character immediately
```

With this change, the syntax was identified correctly as a `jsxCssTemplateString`, but I couldn't get it to recognize the contents as CSS. 🤷‍♂️

![screen shot 2017-06-14 at 4 33 24 pm](https://user-images.githubusercontent.com/297461/27153464-8763edaa-511f-11e7-8108-16153f8faf9a.png)

Anybody have any ideas as to how I might get this working?

**Comment by alampros** [comment]
Hmmm... might be able to take a page from the [vim-styled-components plugin](https://github.com/fleischie/vim-styled-components/blob/develop/after/syntax/javascript.vim). They have to detect an `import` of their module, while here we would only have to detect the `jsx` attribute on the `<style>` tag.

**Comment by alampros** [comment]
🙌 

I got it working and pushed it to a new repo: [alampros/vim-styled-jsx](https://github.com/alampros/vim-styled-jsx)

### Screenshot:
![screen shot 2017-06-15 at 9 47 39 am](https://user-images.githubusercontent.com/297461/27184977-d9452a52-51b1-11e7-9980-b4363cb333e1.png)
