### ISSUE TITLE
Global CSS order.

### ISSUE THREAD

**Issue by rickyrauch** [zeit/styled-jsx#185]
Hello,

I'm loading webfonts on scaleapi.com but I see flash of invisible font.

While I add the font-face css at the top, I think it's being ignored and I see it 3rd.

<img width="762" alt="screen shot 2017-05-05 at 3 58 51 am" src="https://cloud.githubusercontent.com/assets/197196/25752799/bf5c306e-318f-11e7-87fe-ebaf869df106.png">

Thanks

**Comment by giuseppeg** [comment]
I am not sure if you can rely on the definition order, I'd load fonts differently maybe in the `head` with a `link` tag.

**Comment by rickyrauch** [comment]
@giuseppeg thanks for your answer, but I want to avoid more requests and flashing.

**Comment by rickyrauch** [comment]
Isn't this a bug? since I'm loading these webfonts first

Thanks

**Comment by rickyrauch** [comment]
I think I resolved it. But it think <style jsx global> should load first by mandatory.

Thanks

**Comment by rickyrauch** [comment]
update: flash of invisible font is not related to the order of the webfont, I'll create an example this weekend to make a better debugging.

My hypothesis is that base64 @font-face loaded via <style> tags is causing the issue. If it is correct, I'm going to close this issue.

**Comment by rickyrauch** [comment]
Hi, 

Quick update: Loading font-face via <link> still flashing.

I changed `"HarmoniaSans W01", -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen,Ubuntu,Cantarell,"Open Sans","Helvetica Neue",sans-serif` by "HarmoniaSans W01" and it works better https://scale-frontend-spnydozmuy.now.sh/ but still flashing.

If you inspect the code you will see the webfont <style> loading 10th. So I think that's the bug.

**Comment by giuseppeg** [comment]
@rickyrauch I am gonna need to see some code and be able to try it out. Can you make a minimal and simple Next.js app and put it on github?
