### ISSUE TITLE
PostCSS

### ISSUE THREAD

**Issue by comerc** [zeit/styled-jsx#188]
Please add solution to readme.

[styled-jsx-postcss](https://github.com/giuseppeg/styled-jsx-postcss) + VSCode + [postcss-sugarss-language](https://marketplace.visualstudio.com/items?itemName=mhmadhamster.postcss-language) + [Template Literal Editor](https://marketplace.visualstudio.com/items?itemName=plievone.vscode-template-literal-editor) = works fine!

**Comment by corysimmons** [comment]
I think they're hesitant to officially support the PostCSS plugin, but yeah, PostCSS support is huge.

**Comment by giuseppeg** [comment]
We may add support for plugins (which would enable preprocessing) to styled-jsx soon #182

**Comment by giuseppeg** [comment]
I will re-open if #182 doesn't get merged
