### ISSUE TITLE
Keeping CSS in separate files

### ISSUE THREAD

**Issue by ooade** [zeit/styled-jsx#193]
This is not working. Tried the example laid out [here](https://github.com/zeit/styled-jsx#keeping-css-in-separate-files).

I'm always getting this error: `Module build failed: SyntaxError: Expected a template literal or String literal as the child of the JSX Style tag (eg: <style jsx>{`some css`}</style>), but got Identifier`

**Comment by giuseppeg** [comment]
@ooade this feature has not been released yet. Are you using `master` or installing from npm?

**Comment by ooade** [comment]
@giuseppeg not sure. Using it on a next.js app

**Comment by giuseppeg** [comment]
@ooade ok makes sense. As I said we haven't released a new version of styled-jsx that includes this feature. We'll do very soon.
