### ISSUE TITLE
Write benchmarks for main transformation functions

### ISSUE THREAD

**Issue by rauchg** [zeit/styled-jsx#2]
I suspect it's very very fast (specially thanks to @thysultan), but it'd be nice to know

**Comment by thysultan** [comment]
for [150 LOC](https://rawgit.com/thysultan/stylis.js/master/benchmark/index.html) i get ~17ms.

**Comment by rauchg** [comment]
Amazing. 0.24 on my macbook 12. Although it'd be nice to know also how performant the babel transformation is
