### ISSUE TITLE
Keeping external styles

### ISSUE THREAD

**Issue by wearevilla** [zeit/styled-jsx#203]
Getting the following error when importing styles and using <style jsx>{styles}</style>

`Module build failed: SyntaxError: Expected a template literal or String literal as the child of the JSX Style tag (eg: <style jsx>{`some css`}</style>), but got Identifier`

Any help is much appreciated! :)

**Comment by wearevilla** [comment]
It tried writing <style jsx>`${styles}`</style> and that works, but ignores live style injection and requires clicking the refresh button...

**Comment by wearevilla** [comment]
closing because i just saw this has been addressed. its in the docs but not release yet :( 

https://github.com/zeit/styled-jsx/issues/193

**Comment by giuseppeg** [comment]
@wearevilla I will try to release this week

**Comment by wearevilla** [comment]
@giuseppeg you're the best! thank you! :D

**Comment by Yuripetusko** [comment]
Thank you guys, any ETA when external styles will be released to npm?

**Comment by giuseppeg** [comment]
We should release this week

**Comment by Yuripetusko** [comment]
@giuseppeg thank you

**Comment by wearevilla** [comment]
hey @giuseppeg i saw that version 1.0.1 got published here https://github.com/zeit/next.js/pull/2095
Does that by any chance have anything to do with the fix for this issue? im using next@3.0.0-beta3

Thanks! :D

**Comment by wearevilla** [comment]
@giuseppeg ah i just saw this issue was already addressed at 1.0.0 a day ago!! you are the best dude!!! thanks! 💯 🎉
