### ISSUE TITLE
Using SASS styles inside <style jsx>

### ISSUE THREAD

**Issue by vladejs** [zeit/styled-jsx#205]
Is that possible? I am used to SASS and want to use it in my _next app_.
Currently, I have this code: 

```
p {
    color: red;
}

p.span {
  color: blue;
}
```

And I wanna make it like this:
```
p {
    color: red;

    &.span {
      color: blue;
    }
}
```
If I do that, it doesn't throws errors, but the indented style gets ignored.

**Comment by giuseppeg** [comment]
Not yet but it might be very soon thanks to #190

**Comment by vladejs** [comment]
Currently, if I import a SASS file I get it compiled thanxs to webpack, but I don't know if I can do this:

```
import React from 'react'
import buttonStyles from './button.scss'

export default props => (<div>
  <p>
    Hello Sr
  </p>
  <style jsx>
    {`${buttonStyles}`}
  </style>
</div>)
```

**Comment by giuseppeg** [comment]
you can but they won't be scoped

**Comment by vladejs** [comment]
So there's no way to make it scoped?

**Comment by giuseppeg** [comment]
no yet, but with Plugins it will be possible and very easy.

**Comment by vladejs** [comment]
thanks, but how long do I need to wait in order to use plugins?

2017-05-22 12:49 GMT-04:00 Giuseppe <notifications@github.com>:

**Comment by giuseppeg** [comment]
@vladejs I already have a Pull Request ready but we won't include it in the next release yet. So my guess is that probably in a couple of weeks we will be able to release a version that introduces plugins.

**Comment by pexxi** [comment]
This would be an awesome addition. Any news on this?

**Comment by giuseppeg** [comment]
@pexxi we might have to postpone this feature to when dynamic styles support is implemented (#81).

**Comment by fredsh** [comment]
Hello, not sure this is the right place for this question.
I am using styled jsx with the sass plugin. Works well but I have encountered a small issue trying to use js variable inside the style.
It seems that simple variable use works for simple values, but not when used in more complex case like parameter of a mixin.
Below is a small example of what I am trying to do. The color is applied correctly but the media query will not work as expected (always evaluates to true).
`
    const bp = 'medium'
    const col = 'yellow'

        <style jsx>{`
          @import 'styles/css/foundation.scss';
          .layout{
            width: 100%;
            @include breakpoint($bp) {
              max-width: 80%;
              background-color: ${col};
            }
          }
          `}</style>
`

I have seen this in the readme 
> Plugins won't transform expressions 

If I understand correctly, what I want to do is currently not supported right? Is there any plan to support this in the future? And if I wanted to help support this, where should I look?
By the way, thanks for the great work.

**Comment by cristianzamar** [comment]
@fredsh I'm testing the same styled-jsx plugin and I can't get the imported .scss files to hot-reload or even reload with a page refresh. Have you achieve that??

**Comment by HansUXdev** [comment]
Any update on this?

 Or atleast using postcss plugins for css nesting and [container-query](https://github.com/ZeeCoder/container-query)? 

With javascript functions and variables, we don't really need css vars (and the ugly syntax) or mixins but nesting and container query support would be very nice.

**Comment by chiqui3d** [comment]
What shitty `styled-jsx`, I just started with Next.js and was **impressed with the easy and great explanation on their page**, but it has been getting to the `styles `and it's something awful, first because of the way they declare the styles and second because we've been looking for two hours to use sass in the following way:

```
import home from '../css/home.scss'
<style jsx>{home}</style>
```

**Comment by darrylsepeda** [comment]
Still encounter same issue with next v9.0.2.
indented style from scss not applied..

seems the pull request was not merged at all: https://github.com/zeit/styled-jsx/pull/190

https://github.com/zeit/styled-jsx/issues/310, I used `styled-jsx-plugin-sass` also in my project, but still indented style not working.
```
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": ["styled-jsx-plugin-sass"]
        }
      }
    ]
  ],
}

```

**Comment by adam-zhu** [comment]
> Hello, not sure this is the right place for this question.
> I am using styled jsx with the sass plugin. Works well but I have encountered a small issue trying to use js variable inside the style.
> It seems that simple variable use works for simple values, but not when used in more complex case like parameter of a mixin.
> Below is a small example of what I am trying to do. The color is applied correctly but the media query will not work as expected (always evaluates to true).
> 
> const bp = 'medium'
> const col = 'yellow'
> 
> ```
>     <style jsx>{`
>       @import 'styles/css/foundation.scss';
>       .layout{
>         width: 100%;
>         @include breakpoint($bp) { // 👀 ${bp}?
>           max-width: 80%;
>           background-color: ${col};
>         }
>       }
>       `}</style>
> ```
