### ISSUE TITLE
styled-jsx/babel cannot work with ['transform-react-jsx', { 'pragma': 'h' }]

### ISSUE THREAD

**Issue by zaaack** [zeit/styled-jsx#206]
I want to using preact with styled-jsx, and pragma to jsx transformer, but then <style jsx> cannot be transformed. Also I find that if not using { 'pragma': 'h' }, but using default jsx options, and add some hack for  preact, it's working.

**Comment by giuseppeg** [comment]
What error do you get? Can it be an order issue? If not chances are that the two plugins visitors are merged and one is breaking the other

**Comment by zaaack** [comment]
@159938 no error, just not parsed, I tried different order, before jsx plugin, after jsx plugin, the first, the last, but my babelrchas react preset, I tried removed, bnothing change, until I remove custom pragma,  and using monkey pack for React.createElement, it worked.

**Comment by matthewmueller** [comment]
ran into this too, but i just tested it and it works if you put `styled-jsx` before `transform-react-jsx`.

Here's an example `.babelrc`:

```
{
	"presets": [
		"babel-preset-flow",
		"babel-preset-env"
	],
	"plugins": [
		"babel-plugin-transform-class-properties",
		"babel-plugin-transform-runtime",
    "styled-jsx/babel",
		["babel-plugin-transform-react-jsx", { pragma: "h"}]
	]
}
```

**Comment by matthewmueller** [comment]
Quick update on this: Disregard what I previously said, since I was mistaken, it doesn't actually work, it just looks like it works because `<style>` will still get applied, just outside of styled-jsx.

This is actually most likely a webpack issue, you need to externalize `styled-jsx/style`.

**Comment by garrettmac** [comment]
try
```jsx
{
	"presets": [
		"flow",
		"env"
	],
	"plugins": [
		"transform-class-properties",
		"transform-runtime",
		"styled-jsx/babel",
		["transform-react-jsx", { pragma: "h"}]
	]
}
```
