### ISSUE TITLE
media query with React property

### ISSUE THREAD

**Issue by sedubois** [zeit/styled-jsx#208]
With styled-jsx there's a "recommendation" (which is actually compulsory, AFAIK) to use inline styles when local props are involved. But I need to set my style with a media query, something like:

```
        @media (max-width: 767px) {
          a {
            display: ${display ? 'block' : 'none'};
          }
        }
```

How do I do that, as `@media` queries are AFAIK not supported in inline styles? 

Thanks a lot

**Comment by giuseppeg** [comment]
you can use the `matchMedia` api and toggle a class name

```jsx
const matches = window.matchMedia('(max-width: 767px)').matches
const myClass = matches ? 'foo' : 'bar'
```

FWIW we are going to implement support for dynamic values, we just need time (I don't have a lot of free time) and to do it right so that it is not disruptive and slow.

**Comment by sedubois** [comment]
Thanks a lot @giuseppeg, that sounds like a good start! But `window` only exists client-side, how can I reproduce the media query's behaviour server-side (for Next.js)?

**Comment by sedubois** [comment]
Also it looks like using this `matches` approach, the style doesn't get recomputed upon window size change, so it's quite cumbersome.

**Comment by giuseppeg** [comment]
> the style doesn't get recomputed upon window size change, so it's quite cumbersome. 

You can add a [listener](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener) to the object returned by matchMedia. 
There is also [an handy component for React](https://www.npmjs.com/package/react-media) – usually you could as well render different trees.

Server side rendering might be a bit of an issue but you could try to compute the mq on componentWillMount on the client.

**Comment by sedubois** [comment]
Thanks. I used react-media which works well, except for SSR again, the initial render is incorrect.

Not quite sure how to use react-media together with componentWillMount.

Anyway it's all quite complicated. For now I stick with a plain ugly `<style>` tag, at least it works.

So looking forward to improvements within styled-jsx :)

**Comment by giuseppeg** [comment]
Yeah, your use case is best solved with a dynamic prop. 
Unfortunately the current code doesn't support them. I want them badly too but it might take a while considering that I don't have a lot of free time.

**Comment by sedubois** [comment]
Sure no worries, if it becomes critical I'll temporarily switch to styled-components or something. Wish you all the best, this can be an awesome project.

**Comment by giuseppeg** [comment]
@sedubois as of v2 we support dynamic styles.. this should solve your issue. Feel free to re-open if you need further help or this is still not possible to do.
