### ISSUE TITLE
Add uniqueClass generator utilily

### ISSUE THREAD

**Issue by giuseppeg** [zeit/styled-jsx#209]
Parent components could style children by passing a classname that they control e.g.

```jsx
import { uniqueClass } from 'styled-jsx/utils'
const buttonClass = uniqueClass()

export default () => (
  <div>
      <Button className={buttonClass} />
      <style jsx>{`
          .${buttonClass} { color: red }
      `}</style>
  </div>
)
```

In order to do so we'd need to transpile the import to something like

```js
const uniqueClass = (() => {
   const uid = hash(thisModuleRelativePath)
   const counter = 0
   return () => `__style-jsx-${uid}-${counter++}`
})()
```

Where `thisModuleRelativePath` could be something like [this](https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/displayNameAndId.js#L9-L13).

@nkzawa @rauchg thoughts? Do you think that this could be useful?

**Comment by pungggi** [comment]
Hi any news on that?

**Comment by giuseppeg** [comment]
Found a better mouse trap: https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent
