### ISSUE TITLE
Need to transpile ES2015 modules to  CommonJS

### ISSUE THREAD

**Issue by nkzawa** [zeit/styled-jsx#21]
The transformation of `styled-jsx/babel` adds the `import` statement (`styled-jsx/inject`), which means you always have to transpile it to CommonJS by using `babel-transform-es2015-modules-commonjs`.
I wonder if this is the design decision, like for tree-shaking.

**Comment by MoOx** [comment]
Just a note/reminder: webpack 2 understand totally ``import`` (and tree-shaking only works with import btw, not with transpiled import)

**Comment by rauchg** [comment]
Yeah, IMHO we have to assume a webpack2 future

**Comment by nkzawa** [comment]
That makes sense, but I wonder if it works since we actually use CommonJS to proxy the module.

https://github.com/zeit/styled-jsx/blob/master/inject.js

And the module is very small and it looks there is no unused exports.

**Comment by nkzawa** [comment]
Or does tree-shaking work even if there is the proxy ?

**Comment by rauchg** [comment]
Yeah we might need to get rid of the proxy. Anyways, I just tried it with webpack2 and it works great

**Comment by nkzawa** [comment]
`inject.js` is transpiled to CommonJS. Does this still work ?

**Comment by rauchg** [comment]
yep. I just launched two demos: https://dei.now.sh and https://dei-global.now.sh/

**Comment by rauchg** [comment]
dei-global is the exact same codebase minus the `styled-jsx/babel` transformation, which means it's working amazingly (the `<p>` styles don't leak)

**Comment by jescalan** [comment]
I think this should be probably be switched over to a `require`. While it will work ok with webpack2 which probably many users are on, if you are not using webpack2, you're going to very consistently get an error. Having this library break without any real explanation if you are not using webpack2 doesn't really seem super reasonable. Just switching the import to a require will immediately solve this issue.

If I get a 👍 from a maintainer, I'd be happy to submit a PR to patch this!

**Comment by giuseppeg** [comment]
If people is not using webpack2 chances are that they have `babel-transform-es2015-modules-commonjs` in their `.babelrc` or some other way to manage `import` so I don't see the problem tbh

**Comment by jescalan** [comment]
I don't think basing the library's functionality on a chance that someone might be using an optional unrelated dependency is really very sound software development. For example, I'm here because I was not using it and ran into this error.
