### ISSUE TITLE
Can get <Link> from React Router styled anymore [v1.0.0]

### ISSUE THREAD

**Issue by soulchainer** [zeit/styled-jsx#212]
In v0.57, this worked:

```js
render() {
    const { label, to } = this.props;
    return (
      <div className="ButtonLink">
        <Link className="ButtonLink-link" to={to} onClick={this.onClickLink}>
          {label}
        </Link>
        <style jsx>{`
          [some other rules]
          .ButtonLink-link {
            border: .25rem solid ${colors.shadowWhite};
            color: ${colors.white};
            display: inline-block;
            height: 100%;
            line-height: 2rem;
            padding: .5rem;
            text-decoration: none;
            transition: border-color .1s .4s, background-color .4s;
            width: 100%;
          }
        `}</style>
      </div>
    );
  }
```

I updated to `v1.0.0` and it doesn't work anymore.
In this case, `a` generated by React Routed get the `className` OK, but they never get the styles applied.

I think this is because (and extract of what it's inyected in `<style>`, at the page:

```css
.ButtonLink[data-jsx="1324817230"]{rules rules}.ButtonLink-link[data-jsx="1324817230"]{rules rules}
```

And, in the HTML, the `data-jsx` is only setted to `ButtonLink` element, not to the `a` tag.
So, it get's it never applied.

I also tried with `.ButtonLink > .ButtonLink-link`. Same result, it only sets the `data-jsx` to `ButtonLink` and in injects something like:

```css
.ButtonLink[data-jsx="1368184654"]{rules rules}.ButtonLink[data-jsx="1368184654"]>.ButtonLink-link[data-jsx="1368184654"]{rules rules}
```

and, like `ButtonLink-link` never gets the attribute `data-jsx`, the styles are never applied.

And, mention appart, previously to tried this (before to migrate to v1.0.0), I had `.ButtonLink-link` as `.ButtonLink > a`. And **it was working just fine**. I just changed it and added a `className` to `Link` and all that just to try if that way it worked (previously to checked what it was injecting.

I'm not so sure if this is a `stylis` issue or a `styled-jsx`, so I prefered to put it here (already put another issue in `stylis`, so, balancing the charge :þ).

**Comment by giuseppeg** [comment]
As far as I can tell this behavior is "correct" because we don't add the data attribute to components (in your case `Link`). What you are trying to do shouldn't work in 0.5.7 either.

The following should work:

```css
.ButtonLink > :global(.ButtonLink-link) { ... }
```

In the future something like #209 should make it possible to avoid the `global` selector for cases like yours.

**Comment by soulchainer** [comment]
Thanks, @giuseppeg. Well, it was working in 0.5.7, so it got me puzzled.

What you proposes works fine, so: problem solved. But, Ideally, yes, #209 would be great :). I will be watching that issue ^^.

Thanks for your help 👍.
