### ISSUE TITLE
Can't keep styles for more than one component in separate files: it breaks

### ISSUE THREAD

**Issue by soulchainer** [zeit/styled-jsx#215]
I was pretty excited when, at last, this feature got shipped.
Last night, at last, I could try it.

I first tried moving the global CSS I have and it worked flawlessly.

Then, I tried to add any other CSS, from any component. And it breaks. Doesn't matter what component, at any level or deep... it just break.

As example, I'm creating this file:

`animatedTitle.js`

```js
const AnimatedTitleCSS = `
  .AnimatedTitle {
    align-items: center;
    display: flex;
    justify-content: center;
    width: 100%; /* If the width isn't setted, the SVG won't scale */
  }

  /* Put some space between the letters */
  svg {
    margin-left: 2vmin;
    top: 10vmin;
  }
`;
export default AnimatedTitleCSS;
```

And using it like this:

`AnimatedTitle.jsx`

```jsx
...
import animatedTitleCSS from '../styles/animatedTitle';
...
render() {
    return (
      <div className="AnimatedTitle">
        ...
        <style jsx>{animatedTitleCSS}</style>
      </div>
    );
  }
...
```

In theory, I'm using it the right way, right? Or not?

When I try this, the project build without problem, but the only thing it injects for the mentioned component is:

```html
<style>undefined</style>
```

And, even more, it breaks/avoid the inyecting of the global styles at all, so the previously working global styles don't get neither applied.
You think about declaring this second styles also `global` (even when not what you want, and not desired at all)? OK. Then styles of this component get injected, yes: but keeps breaking the global CSS. Avoids it to be injected at all. And, because of that, renders the feature not usable at all T_T.

At the state it is, I can only keep in a separate file... one file, with the global styles. That's it. So it loses all the magic.

Am I the only one with this problem/issue?

If so, I can push a branch of my project with this fail. The `global.js` (file with the global styles) isn't doing anything special, or weird, to get banned out **just when any other style is keep isolated from their component**. And, if you remove the extra CSS module, the `global.js` works again just OK.

`global.js`

```js
import { colors } from '../constants';

const GlobalCSS = `
  * { box-sizing: border-box; }

  body {
    background-color: ${colors.black};
    margin: 0;
    max-width: 100%;
    min-height: 100vh;
    overflow-x: hidden;
    width: 100vw;
  }

  #root {
    align-items: center;
    display: flex;
    justify-content: center;
    min-height: 100vh;
    opacity: 0;
  }

  .Root {
    align-items: center;
    display: flex;
    font-family: 'Titillium Web', sans-serif;
    height: 100%;
    justify-content: center;
    width: 100vw;
  }
`;

export default GlobalCSS;
```

**Comment by giuseppeg** [comment]
@soulchainer I am so excited that people is trying this feature out, Thanks!

In your case the problem is that this way of exporting is not supported:

```js
const GlobalCSS = 'some css'

export default GlobalCSS
```

However if you try the following, it should work:

```js
// named export
export const GlobalCSS = 'some css'

// or default export
export default 'some css'
```

**Comment by giuseppeg** [comment]
Maybe we should add some error with an explanation, sorry if you spent time on this.

**Comment by soulchainer** [comment]
Thanks for your really quick response, @giuseppeg :D.

With `export default` it doesn't work;

And... this is gonna sound... weird, but, after you said that, I tested some ways to export it, and it only works when I
```js
export default  `
[here the global.js CSS]
`;
```

And them:

```js
/* eslint-disable import/prefer-default-export */
export const AnimatedTitleCSS = ` 
  [the AnimatedTitleCSS]
`;
```

or when you named export everything. If you just `export default` in all files your chunks of CSS, it won't work. At least, doesn't for me.
This, for sure, it's not the intended behaviour, I guess ;). But, well, at least works :þ. (But now I need to overwrite my ESLint rules, because when there is only one export in a file, it errors if you do a named export instead of a default one, that's the most logic choice in that case, of course).

**Comment by giuseppeg** [comment]
np! Yeah, as I said

```js
export default GlobalCSS
```

won't work. 

Are you referring to this when you say 

> If you just export default in all files your chunks of CSS, it won't work.

?

**Comment by soulchainer** [comment]
No. I mean than this, doesn't work:

`global.js`

```js
export default `
  [CSS global]
`;

`animatedTitle.js`

```js
export default `
[CSS of AnimatedTitle]
`;

While, using instead a named export for the second, works.
Or using named exports for both, also works.

**Comment by soulchainer** [comment]
After some tests, I «know» what causes it.

It breaks always (except, that's weird, for the `global.css` [and it being global doesn't the key, because I also tried adding `global` to the others with the same result]) when the extracted CSS uses variables.

The `global.js` uses variables and doesn't break. Any other CSS module using variables → breaks, `global.js` isn't injected, neither the css module breaking it.

This is hard, because almost **everything** uses variables. The second component I first tried (what an huge coincidence) was the only one that I have don't using variables, so it didn't break then.

**Comment by giuseppeg** [comment]
@soulchainer can you put together a test repository and push it to github so that I can take a look?

**Comment by soulchainer** [comment]
I can create (as I said previously) a branch in the project I'm talking (that's already in GitHub), with my take to use this, yeah. Here:
https://github.com/soulchainer/simongamejs/tree/refactor_extract_css_to_styles_folder

That would suficce?

To install project: `yarn`
To run the dev server: `yarn start`

I put already in `src/styles` a `settingsOptions.js` CSS module, for `src/components/SettingsOptions.jsx`. That it's not still applied. For that:

`SettingsOptions.jsx`

```js
// remove colors from this line: imports values only used in the CSS and the linter will throw error when unused
import { colors, gameModes, MAX_MOVES } from '../constants';
import { SettingsOptionsCSS } from '../styles/settingsOptions';
// change <style jsx> to, obviously
<style jsx>{SettingsOptionsCSS}</style>
...
```

And, in the site, the path http://localhost:5000/settings will render awful.

Revert the changes and it will render OK again.

HMR doesn't work pretty well and some times fails (it's a Neutrino/Webpack/Whatever issue), so F5 just in case xD.

I guess this is the best way (hope it won't be too much trouble) to check it. Cause it's where I'm using it and I know it fails there. Putting together a new repo from zero to get it would be too much trouble,indeed. I guess it's easy to check this way... or not? (If not, I could try something, of course, it just would require a lot more of time to reproduce the problem, I guess).

**Comment by loick** [comment]
Hi there, I have the same kind of issue. Apparently, it's coming up when I import another configuration file in the CSS: 
```
import branding from '../../branding.js'

export const style = `
  .primary {
    background-color: ${branding.color.blue};
    color: ${branding.color.white};
  }

  .secondary {
    color: ${branding.color.blue};
  }

  .tertiary {
    color: ${branding.color.darkGray};
  }

  .danger {
    color: ${branding.color.red};
  }
`
```

If I only have plain CSS, it's working very well :)

**Comment by soulchainer** [comment]
@loick Yes. I said the same [here](https://github.com/zeit/styled-jsx/issues/215#issuecomment-304651344). It breaks when you import values from and outside file for pass them as variables to the styles.
Well, I can guess now it probably isn't just a problem with other config in my project :). Now, waiting till this gets sorted out, someway ^^.

**Comment by loick** [comment]
Good to know where this is coming from at least :) I just tried to make it work in different ways (even by using the tagged functions instead of directly using the variables from the object in the CSS, but it didn't work. Which kind makes sense but.. I had to try it :) 

So, indeed, this is likely to come from the babel plugin!

**Comment by giuseppeg** [comment]
@soulchainer there is a bit too much going on in your app and I cannot even `console.log` because the linter complains and throws, I need a very simple test[ app].

@loick @soulchainer would you be so kind to submit a PR with a failing test so that I can understand what's going on? If you don't want to bother writing a test maybe you can put together a minimal app, using Next.js 2.4.0 which already comes with styled-jsx 1.0.0.

**Comment by soulchainer** [comment]
@giuseppeg I don't know if I did it well (but, in general, it appears to work and the (only) test appears to fail xD), but I did a quick repo with a minimal app using Next.js 2.4.1 → https://github.com/soulchainer/test_nextjs

I made this quick and this is the first time I use Next.js and also Jest (learning how to testing React was my next learning step and still pending ^_^U). Hope this will be OK/suffice.

It only shows a «Hello Next.js» in green when the styles work and, when not, well, just the text in black.

**Comment by soulchainer** [comment]
I was watching the tests and I wouldn't have so much problem editing them... if I could be sure of what I'm doing xD.
I thing this project, *maybe*, needs a `CONTRIBUTING.md` (?). Or maybe I'm wrong.

I understand, more or less, how the tests are used here, without reading specifically about `ava`, but I don't know, as example, in this case:

- If I should create a new fixture for this particular test or maybe edit `fixtures/external-stylesheet.js` and add to it.
- If I should edit `fixtures/styles.js` for add a new named export set of styles, that would be imported and used in the file from the previous point, or if I should, instead, create a new `fixtures/stylesWhatever.js` for that purpose.
- As this uses snapshot testing, I don't know how to «test» if the added CSS intended to set a new «working fine» state are OK, prior to update the snapshots (to don't break them) with them and be able in that moment to change the code again to test the new snapshot against the code that doesn't work.

And I don't want to break something trying, so :þ.
So I hope the simple repo in the previous comment will be useful (or help me with this doubts).

**Comment by giuseppeg** [comment]
@soulchainer no worries I found the bug! 
Thanks a lot for putting together the repo! that was helpful.

In short the problem was that when using interpolation in external files eg. `div { color: ${colors.foo} }` we replace the interpolation `${colors.foo}` with a placeholder so that it can be parsed as css.

For external files we also check whether the export is a string or rather valid css (we do css detection). The problem was that the placeholder is invalid css eg. `div { color: %foo% } }` (`%foo%` is not a valid value for color) so we skip the file altogether.

I will fix it by using a fake css custom property as placeholder instead.
