### ISSUE TITLE
Same styles are applied twice when Server-Side Rendering

### ISSUE THREAD

**Issue by nkzawa** [zeit/styled-jsx#22]
It seems we have to skip generating style tags on client if it's already rendered on SSR.

**Comment by rauchg** [comment]
Yeah that's a great point. I think I have an idea for this. Instead of adding expensive checks with the DOM, we could have an API like this:

```js
import register from 'styled-jsx/register'
const elements = Array.from(document.querySelector('style.styledJSX'))
for (const el of elements) {
  register(el.getAttribute('data-jsx-id'), el)
}
```

**Comment by rauchg** [comment]
We could also expose and manipulate `styled-jsx/memory` directly, but probably not a good idea?

**Comment by thisguychris** [comment]
@rauchg here's an idea:

What if we just save the ids via global object:

```javascript
rehydrate function
import flush from 'styled-jsx/flush'

return function rehydrate(ids = 'jsx_style') {
    if (typeof window === 'undefined') return
    const styles = flush()
    window[ids] = Object.keys(styles)
}

```

Then on the the _JSXStyle injector, we just check for that global variable if its set, it means we check the id against the window.jsx_style variable.

**Comment by nkzawa** [comment]
How about to perform automatic detection of server rendered DOMs, which I think is similar to how `React` works ?

```js
import React from 'react'
import { flushAsString } from 'styled-jsx/server'
import App from './app'

function handler (req, res) {
  const app = React.renderToString(<App />)
  const styles = flushAsString()
  const html = `<!doctype html>
    <html>
      <head>${styles}</head>
      <body>
        <div id="root">${app}</div>
      </body>
    </html>`
  res.end(html)
}
```

`styles` should looks like the following:

```html
<style data-jsx-id="12345">p[data-jsx="12345"] { color: red }</style>
<style data-jsx-id="98765">p[data-jsx="98765"] { background-color: blue }</style>
```

Then we can automatically collect these DOMs.

I think this less flexibility is good because we have to force users to create each `style` element per `jsx-id` for ditching unused styles anyway.

**Comment by thisguychris** [comment]
@nkzawa would style-jsx moving out of the data selector and use classNames instead? see #27

**Comment by nkzawa** [comment]
@thisguychris Both ways would work fine anyway.

About your idea, `const styles = flush()` is what we're discussing how we can make it work 😂

**Comment by thisguychris** [comment]
@nkzawa yeah the idea is adding / attaching all generated ids inside a global variable. We then add a check the existence of the variable inside renderOnClient function. 

When you say 
> Then we can automatically collect these DOMs.

Does that mean we're going to have some DOM traversals to collect these ids from the generated styles?  If so attaching an array of ids inside a window variable would be faster and simpler?  Thoughts?

**Comment by nkzawa** [comment]
@thisguychris 

> Does that mean we're going to have some DOM traversals to collect these ids from the generated styles?

yep, ids and elements

> If so attaching an array of ids inside a window variable would be faster and simpler?

I can't fully imagine how it works. To achieve this, we have to force users to write some JS on client ? Additionally, we need to get `style` elements too. just collecting ids is not enough.

**Comment by thisguychris** [comment]
@nkzawa if we have the ids, we can add a check inside `renderOnClient` function.  If the id is there, then we skip rendering the style?
