### ISSUE TITLE
Shorter ID

### ISSUE THREAD

**Issue by pietrasiak** [zeit/styled-jsx#221]
Is it possible to make id of `data-jsx="1809743507"` shorter?

or even make it like 1, 2, 3, 4 ... a, b, c, d ... z, 11, 12, 13 ... 1a, etc.? 

I'd say those ids are big part of my rendered html with inlined css.

Also - why can't we use `data-reactid` for selectors?

**Comment by giuseppeg** [comment]
It is not possible right now, but we might switch to classes at some point. See #27 

> Also - why can't we use data-reactid for selectors?

this is gone in recent versions of React
