### ISSUE TITLE
I recommend using hash style className

### ISSUE THREAD

**Issue by MinJieLiu** [zeit/styled-jsx#226]
Attribute selector is not efficient.

I think it should be like this:

```css
.container {}
```

to

```css
.container__$suffix {}
```

If it is a property selector, it is the same as it is now.

like:

```css
p {}
```

to

```css
p[data-jsx="xxx"] {}
```

Is not that better?
😊

**Comment by giuseppeg** [comment]
We will do this at this point, there is already a tracking issue #27
