### ISSUE TITLE
styles minification 

### ISSUE THREAD

**Issue by vincent178** [zeit/styled-jsx#229]
Hi guys, is there any documentation related to styles minification auto prefix for class for production?

![screen shot 2017-06-07 at 1 09 12 pm](https://user-images.githubusercontent.com/2183720/26863056-9c8aa1bc-4b82-11e7-9c5f-84321756cd8e.png)

I don't there's any configuration to turn on these two features.

**Comment by vincent178** [comment]
I have find the example I need, thanks for the great work.

**Comment by royeeshemesh** [comment]
@vincent178 what exactly have you found?

**Comment by vincent178** [comment]
Hi @royeeshemesh , I believe I found the solution at that time, but I can't find the code any more, now I turn to use styled-components, I already use it for some time, it's pretty good.
