### ISSUE TITLE
How to extend existing Component styles

### ISSUE THREAD

**Issue by ron-liu** [zeit/styled-jsx#240]
I try to extend `Component A` style, but the following code doesn't work.  What is the best way to extend styles using styled-jsx? 

```jsx
const A = () => <div>Hello
	<style jsx>{`div {color: red}`}</style>
</div>

const B = () => <A>
	<style jsx>{`
		div {background-color: blue;}
	`}</style>
</A>
// doesn't work, no background-color ejected. 
```

**Comment by amio** [comment]
It's not recommended but you could use ["global styles"](https://github.com/zeit/styled-jsx#global-styles).

**Comment by giuseppeg** [comment]
@amio you can't use props in styles.. yet

**Comment by amio** [comment]
Oops, any details about why?

**Comment by giuseppeg** [comment]
Because all the instances of a component share the same styles. If you update the styles based on props changes that happened on a single component will affect all of them which is not what you want :)

**Comment by amio** [comment]
@ron-liu I just found this, multiple ways to style child component:
https://github.com/zeit/styled-jsx#global-selectors
https://github.com/zeit/styled-jsx#dynamic-styles

**Comment by giuseppeg** [comment]
You cannot extend components but you could pass some styles/className. See https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent

**Comment by mshez** [comment]
You can import the styles and use it like this

// Component A whose styles needs to be used
export const SomeStyles = css`Styles goes here`
<style jsx>{SomeStyles}</style>

// Component B where the styles need to be extended
import {SomeStyles} from './ComponentA

export const SomeOtherStyles = css`Styles goes here`
<style jsx>{SomeStyles}</style>
<style jsx>{SomeOtherStyles}</style>
