### ISSUE TITLE
Disable autoprefixing for everything inside particular style tag

### ISSUE THREAD

**Issue by almeynman** [zeit/styled-jsx#243]
Given  component like that. I do not want to autoprefix global styles.

```jsx
import stylesheet from "./index.css";
import globalStyles from "./global.css";
import Layout from "../components/Layout";

export default () =>
  <Layout>
    <div className="hello">
      <p>Hello World</p>
    </div>
    <style jsx>{stylesheet}</style>
    <style jsx global>{globalStyles}</style>
  </Layout>;

```

**Comment by giuseppeg** [comment]
Could not be done for external styles though. What we can do is add an option to disable it completely maybe.

**Comment by almeynman** [comment]
An option to disable it completely is exactly what I need.
I need to disable it completely for external stylesheet, as most of them do not require prefixing

**Comment by giuseppeg** [comment]
@almeynman that would disable it also for inline styles, is that ok?

**Comment by almeynman** [comment]
@giuseppeg ok

**Comment by giuseppeg** [comment]
the option to disable vendor prefixing was introduced in version 2.1.0 https://github.com/zeit/styled-jsx/releases/tag/v2.1.0
