### ISSUE TITLE
Browser Warning: Unknown prop

### ISSUE THREAD

**Issue by PDXIII** [zeit/styled-jsx#250]
Hello, folks! 
Haven’t found anything like that in the issues so I hope someone has already fixed that. 
I use styled-jsx in a [create-react-app](https://github.com/facebookincubator/create-react-app) project and I keep getting these errors in the browser. 

![screen shot 2017-06-27 at 15 43 52](https://user-images.githubusercontent.com/415557/27591018-c5eb7db4-5b50-11e7-886e-8c6131f141b7.png)

Besides that everything works fine. But who likes to have errors. ;)

**Comment by giuseppeg** [comment]
How are you using it in `create-react-app`? As far as I know it is not possible to configure `.babelrc`.
Anyhow that error usually means that `styled-jsx` didn't run at all and therefore your CSS is not compiled and scoped.

**Comment by PDXIII** [comment]
Funny thing! It is compiled.

**Comment by giuseppeg** [comment]
@PDXIII yeah if you need further help maybe you can create a demo repository

**Comment by PDXIII** [comment]
Thanks, @giuseppeg! I will let you know.
