### ISSUE TITLE
Column count doesn't get prefixed

### ISSUE THREAD

**Issue by roopemerikukka** [zeit/styled-jsx#252]
I'm using `column-count` in my css but it doesn't get prefixed. Does the built-in prefixer read `browserslist` config inside projects package.json or how it decides what properties to prefix?

**Comment by giuseppeg** [comment]
nope we don't use autoprefixer / browserslist but [Stylis](https://github.com/thysultan/stylis.js)' built in prefixer. You may want to open an issue on that repo instead.

With plugins #190 you will be able to disable it and write a plugin that uses autoprefixer instead.

**Comment by roopemerikukka** [comment]
Thanks for the reply! I opened an [issue](https://github.com/thysultan/stylis.js/issues/43) to the Stylis repo.
