### ISSUE TITLE
>>: unprefixed descendant selector / shadow piercing

### ISSUE THREAD

**Issue by rauchg** [zeit/styled-jsx#26]
It'd be interesting to skip prefixing if the user uses `>>`:

```jsx
export default () => (
  <div>
    <div class="my-component">
      <MyComponent /> { /* this component has a <span> child */ }
    </div>
    <style jsx>{`
       .my-component >> span {
         color: red
       }
    `}</style>
  </div>
)
```
Not sure if `>>` is in conflict with any existing or future CSS specs, but I like this a lot. `styled-jsx` effectively turns the CSS model upside down, making the dangerous aspects of it "opt-in", through, in this case the extra `>>`

**Comment by rauchg** [comment]
TIL: https://drafts.csswg.org/css-scoping/#deep-combinator

**Comment by rauchg** [comment]
Curious why it's `>>>` and not `>>`? cc @TakayoshiKochi @hayatoito @annevk

**Comment by luisrudge** [comment]
why would you want to not autoprefix stuff?

**Comment by rauchg** [comment]
@luisrudge I normally don't. My preferred pattern is to pass _props_ to make changes _explicit_ on both sides.

Passing props establishes a _contract_, whereas this introduces external mutations that are unexpected by the component.

But there are edge cases and scenarios where people might want to override a 3rd party codebase, for example.

**Comment by luisrudge** [comment]
oh, sorry.. I thought this was for stopping autoprefix for unsuportted properties.. 😊 Forget I was here :D

**Comment by treshugart** [comment]
@rauchg I'm fairly certain the shadow piercing combinator is deprecated?

**Comment by rauchg** [comment]
@treshugart not according to that discussion ?

**Comment by treshugart** [comment]
@rauchg Ahh yep, I remember reading the thread a couple months ago. At that time the discussion ended around "not useful for closed trees". Still lots of contention. And yeah, I never understood the extra `>` either.

**Comment by rauchg** [comment]
Just based on the initial feedback to `styled-jsx`, I have a strong instinct that it's good to have it as a occasional escape hatch. So even if it ends up being deprecated, it might be cool to support it

**Comment by annevk** [comment]
I don't know, but I'm pretty sure this feature lacks agreement.

**Comment by hayatoito** [comment]
"`>>`" is an *alias* for "` `" (space; descendant combinator), though `>>` is not supported widely by UAs, as of now.
See https://drafts.csswg.org/selectors-4/#descendant-combinators for the spec.

**Comment by pemrouz** [comment]
@rauchg to clarify, that thread is only about `>>>` in JS btw (querySelector, querySelectorAll). [It's deprecated for styling in CSS](https://github.com/w3c/webcomponents/issues/78#issuecomment-238452345). @dglazkov put together [the best writeup here](https://github.com/w3c/webcomponents/wiki/Shadow-piercing-Combinators-in-the-Wild). I agree it's the wrong approach to theming, but also [that it should be available via JS](https://github.com/w3c/webcomponents/issues/78#issuecomment-223458546).

Still, I'm +1 for keeping it as an escape hatch here and seeing how people use it :)

**Comment by rauchg** [comment]
Got it. 

1. It's a bit weird that it works on one side and not the other
2. I think it's a nice escape-hatch because it's so gross-looking and explicit (specially with three `>`)

So, still interested in retaining it!

**Comment by rauchg** [comment]
Thanks @annevk @hayatoito @pemrouz for weighing in

**Comment by TakayoshiKochi** [comment]
As already mentioned, `>>>` is for use only for JS (querySelector), not for CSS styling, but still contentious. If you are interested, please follow the discussion at https://github.com/w3c/webcomponents/issues/78.

On the other hand `>>` could be used for styling.  As of now, only Safari 10 implements `>>` ([caniuse](http://caniuse.com/#feat=css-descendant-gtgt)).

**Comment by giuseppeg** [comment]
@rauchg 

> Passing props establishes a contract, whereas this introduces external mutations that are unexpected by the component.

This could be also done with CSS Custom Properties already.

> But there are edge cases and scenarios where people might want to override a 3rd party codebase, for example.

I think that [a named `<slot>`](https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom#slots) for user styles could solve this issue POF: http://codepen.io/giuseppegurgone/pen/dOKWpV?editors=0010 (we'd need to add prefixing)

**Comment by ericclemmons** [comment]
It's weird for auto-prefixing to _not_ be a default (I'd <3 to see a compelling argument), but is adding props to `style` acceptable?
```js
export default () => (
  <div>
    <div class="my-component">
      <MyComponent /> { /* this component has a <span> child */ }
    </div>
    <style no-autoprefix jsx>{`
       .my-component > span {
         color: red
       }
    `}</style>
  </div>
)
```

Go all out with props:

```js
{/* All classes get normalize.css-equivalent applied wo0t! */}
<style normalize jsx>
```

Alright, I'm done bikeshedding. :wave:

**Comment by rauchg** [comment]
I definitely thought about it. Notice #5

**Comment by thysultan** [comment]
@rauchg namespace prefix? can't you do this with `:host-context(.my-component span) {}`

**Comment by giuseppeg** [comment]
@thysultan you can't reach to the "shadow dom" from the outside with `:host-context`.
It works like this:

```jsx
const MyComponent = () => (
  <div>
    <span>hello</span>
    <style jsx>{`
      span { color: red; }
      :host-context(.my-component) span { color: green; }
    `}</style>
  </div>
)

const App = () => (
  <div class="my-component">
    <MyComponent /> {/* the span now will be green */}
  </div>
)
```

@ericclemmons I think that react has a whitelist of *valid* html attributes and warns when it finds invalid one, therefore those should be stripped out at transpilation time. Also this pattern looks a bit like passing N arguments to a function... it could get nasty, maybe a better way to pass option would be to set the `jsx` attribute value to an object like:

```jsx
const options = {
  autoprefix: false
}

<style jsx={options}></style>
```

**Comment by thysultan** [comment]
@rauchg `:host-context(.my-component) span { color: green; }` will generate `.my-component .user {color: green;}"` without a namespace what did you have in mind for `.my-component >> span` to yield.

**Comment by giuseppeg** [comment]
@thysultan the difference is subtle. 

@rauchg is describing a way to tweak component styles from the outside with `>>>` 
while `:host-context` is internal to the component: 

`:host-context(.my-component) span { color: green; }` means when **MyComponent** is rendered inside of an element with class `my-component` then `span` will get `color: green`

**Comment by thysultan** [comment]
@giuseppeg thanks i get it now, similar to `@root` or a `@at-root` block in scss but for a single specific selector. @rauchg could this work.

```css
<<< .my-component span {}

// or
<< .my-component span {}
```

**Comment by rauchg** [comment]
We ended up implemented this with `:global`, inspired by css modules: https://github.com/zeit/styled-jsx#global-selectors

Hope you like it!
