### ISSUE TITLE
Changing external styles based on global variable throws a syntax error

### ISSUE THREAD

**Issue by hamlim** [zeit/styled-jsx#262]
One of my use cases for styled jsx is to style components slightly differently based on a global theme variable `window.theme` which can be a few different values, but is not dynamic. I intended to switch the styles used to override default styles based on this global value outside of my component and then use them as such:

```Javascript
import { themeAOverrides, themeBOverrides } from './styleOverrides.js';
const themeOverrides = window.theme === 'LIGHT' ? themeAOverrides : themeBOverrides;

const MyComponent = props => (
  <div className="MyComponent">
    // content
    <style jsx>{` /* default styles */ `}</style>
    <style jsx>{themeOverrides}</style>
  </div>
);
```

This ends up throwing:

```Javascript
Syntax error: The Identifier `themeOverrides` is either `undefined` or it is not an external StyleSheet reference i.e. it doesn't come from an `import` or `require` statement
```

Is it possible to get styled-jsx to support different external styles based on global variables outside of the component (i.e. not props/state/context)? If not is there a better suggested solution to resolve this issue?

**Comment by giuseppeg** [comment]
yeah ideally we could enable those kind of things. The problem right now is that we check whether the identifier reference `themeOverrides` is imported.

Maybe there is a better way to do so or we can remove that check completely and just make sure that the identifier is not defined within the scope of the component.

**Comment by hamlim** [comment]
Seems like this code should allow for that: https://github.com/zeit/styled-jsx/blob/master/src/_utils.js#L149 

Unless I am misreading the implementation/comments.

**Comment by giuseppeg** [comment]
Ah no that is for inline styles to stop people from using `props` and `state` but yea possibly it could be used for external styles as well. Would you like to put a PR together? It might be worth adding an integration test too  see [this](https://github.com/zeit/styled-jsx/blob/master/test/browser.js).
