### ISSUE TITLE
[Question] How to create a mixin

### ISSUE THREAD

**Issue by Kikobeats** [zeit/styled-jsx#264]
Hey,

Currently my code looks like:

```jsx
<style jsx>{`
      .card__image {
        box-shadow: 0 0 40px 0 #fff;
        transition-property: box-shadow;
        will-change: box-shadow;
        transition-duration: .2s;
        transition-timing-function: cubic-bezier(.4, 0, .2, 1);
      }

      .card__image:hover {
        box-shadow: 0 0 60px 0 #fff;
      }
    `}</style>
```

I want to refactor it and extract a transition effect to be used in other parts of my application.

I can extract it in something like:

```js
const addTransition = property => `
        transition-property: ${property};
        will-change: ${property};
        transition-duration: .2s;
        transition-timing-function: cubic-bezier(.4, 0, .2, 1);
`
```

It's similar to `@mixin` under SASS.

Now I can simplify and refactor my code into:

```jsx
<style jsx>{`
      .card__image {
        box-shadow: 0 0 40px 0 #fff;
        ${addTransition(box-shadow)}
      }

      .card__image:hover {
        box-shadow: 0 0 60px 0 #fff;
      }
    `}</style>
```

Problem? this doesn't work; I don't know if the problem is my syntax or what.

**Comment by giuseppeg** [comment]
As we speak styled-jsx supports only static css.

If you want to reuse styles you can define them in a separate module [[link](https://github.com/zeit/styled-jsx/blob/master/readme.md#keeping-css-in-separate-files)] (still as static, so you can't use the function approach) or set the dynamic property as inline style.
