### ISSUE TITLE
Class re-writing mode

### ISSUE THREAD

**Issue by rauchg** [zeit/styled-jsx#27]
For background: https://github.com/zeit/styled-jsx/issues/4#issuecomment-265600546
The transformation we might have to use would look like this:

```js
<div className={ a ? 'b' : 'c' }></div>
```

becomes

```js
import _styledJsxPrefix from 'styled-jsx'
<div className=_styledJsxPrefix('r4nd0m', { a ? 'b' : 'c' })></div>
```

and the implementation of `_styledJsxPrefix` would perform class prefixing

**Comment by operatino** [comment]
Definitely looking forward to have such option, not only it will help excluding less performant attr styles, but also:

* Keep selectors less [specific](https://www.smashingmagazine.com/2007/07/css-specificity-things-you-should-know/)
* Output smaller generated CSS

**Comment by rauchg** [comment]
I think to support complete isolation we might have to retain attribute selectors and `data-jsx` attributes however, but we can perform some optimizations to avoid them if needed by statically analyzing the CSS.

Some scenarios. If there's a tag selector:

```css
p { }
```

it becomes

```css
.$prefix_p { }
```

and each element gets a class for its tag name.

If there's a class selector:

```css
.woot { }
```

**Comment by thysultan** [comment]
The following will produce conflicts

```javascript
.p {}
p {}
```

```javascript
.$prefix_p { }
.$prefix_p {}
```
class and ids should probably use a different delimiter to differentiate it from tag selectors.

```javascript
.$prefix_p { }  // tag
.$prefix__p {} // class
```

**Comment by giuseppeg** [comment]
> The following will produce conflicts

also it breaks the specificity model. 

The current behaviour is the right one because it bumps the specificity of **every** selector by `0010`. Similarly a solution that involves the use of classes should add a class to every element.

```jsx
className=_styledJsxConcat('h4sh', originalExpression)
```

Result:

```css
p.h4sh {}
.p.h4sh {}
*.h4sh {}
#test.h4sh {}
/* and so on */
```

**Comment by thysultan** [comment]
why is the hash after the user defined selector?

```
p {
color: red;
}

&:hover { color blue; }
```

to generate 

```
.h4sh p { color:red; }
.h4sh:hover { color: red; }
```

and have the hash added to just the parent element

**Comment by giuseppeg** [comment]
`.h4sh p` will affect the entire subtree.

Also `* { color: red }` converted to `.h4sh* { color: red  }` won't work

**Comment by rauchg** [comment]
For wildcard we can give a class to every element with the prefix

**Comment by thysultan** [comment]
`* { color: red }` would actually be `.h4sh * {}`... what do you mean by 

> affect the entire subtree

shouldn't the selector `p { color: red; }` affect every p element in the namespace element? where as `> p { color: red; }`  will only affect the immediate descendants.

so 

```
<div>
	<p>only this paragraph will get the style :)</p>
	<style jsx>{`
	  p {
	    color: red;
	  }
	`}</style>
</div>
```
becomes 

```
<div class="h4sh">
	<p>only this paragraph will get the style :)</p>
</div>
```

then `& {` selects the `div.h4sh` then `p {` selects the p in the `div.h4sh` and `* {` affects everything in the namespace'd element.

@rauchg does that mean you also have to apply the namespace to the elements children, and how far down the tree does this happen if that's the case.

**Comment by rauchg** [comment]
"affect the entire subtree" means that you're affecting elements of children components you don't know about

**Comment by rauchg** [comment]
Obviously you could force people to use `>` but the whole point is to invert that model, and disallow access to subtress unless explicitly (`:global()`)

**Comment by thysultan** [comment]
You could auto insert the `>` otherwise you can run into cases where the output css and html is are large when using multiple selectors since every selector is getting a suffix and every element that matters is getting a class i.e

```css
h1 span, h2 {}
```
will generate.
```css
h1[data-jsx="woot"] span[data-jsx="woot"], h2[data-jsx="woot"] {}
```

**Comment by giuseppeg** [comment]
@thysultan size is not a problem gzip will do the magic since it is very repetitive data.

> affect the entire subtree

I meant that in styled-jsx styles shouldn't cross the boundaries of the current component and therefore don't leak into nested components.

If you use the children selector `>` you'd have to reconstruct the dom structure to make sure that selectors match the right element(s). Imagine you have this dom

```html
<div>
  <p>
    <span>zeit <span>rocks</span></span>
  </p>
</div>
```

and want to style the innermost `span` 

```css 
span > span { color: red }
```

If you need to style it with the children selector the css should be:

```css
div > p > span > span { color: red }
```

How would you do that? Also now you've increased the specificity of the selector.

**Comment by giuseppeg** [comment]
see #247

**Comment by yxh10** [comment]
Could someone please explain how this resolves the styled-jsx not working with antd components issue?

I still could not get styled-jsx working with antd. antd components's class name doesn't have the random number generated by style-jsx. Therefore, it never matches the style.

The workaround I have are:

1. modify the less file which affects the whole site if I don't add style contexts.
2. inline styling

I think either of the solutions is not ideal. Would be great to have a consistent solution across the whole project which is having styled-jsx to handle all the styling. 

Thank you very much for any help in advance. 

![screen shot 2018-09-30 at 11 38 11 am](https://user-images.githubusercontent.com/100944/46251094-f8f12000-c4a5-11e8-86eb-dfa4b7fe231c.png)

**Comment by guanpengchn** [comment]
@yxh10  Do you have any idea about your question? I have the same problem now.

**Comment by tbarkley** [comment]
@yxh10 I'm also having this same issue

**Comment by bryjch** [comment]
In case anyone is dealing with this problem in the future, seems it can now be handled by either using:

- [`resolve` tag](https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent)
- [`:global()` styles](https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent)

**Comment by toFrankie** [comment]
> Could someone please explain how this resolves the **styled-jsx not working with antd components** issue?
> 
> I still could not get styled-jsx working with antd. antd components' class name doesn't have the random number generated by style-jsx. Therefore, it never matches the style.
> 
> The workaround I have are:
> 
> 1. modify the less file which affects the whole site if I don't add style contexts.
> 2. inline styling
> 
> I think either of the solutions is not ideal. Would be great to have a consistent solution across the whole project which is having styled-jsx to handle all the styling.
> 
> Thank you very much for any help in advance.
> 
> ![screen shot 2018-09-30 at 11 38 11 am](https://user-images.githubusercontent.com/100944/46251094-f8f12000-c4a5-11e8-86eb-dfa4b7fe231c.png)

除了 [resolve tag](https://github.com/vercel/styled-jsx#the-resolve-tag) 有什么更为优雅的解决方案吗？
