### ISSUE TITLE
example implementation for server side rendering?

### ISSUE THREAD

**Issue by tkellen** [zeit/styled-jsx#276]
Hi! First, thanks for your tremendously awesome work on this ecosystem. I've been using next.js for two days now and for the most part everything just works. Very impressive given all the complexity under the hood!

I have one question... are there any examples of using styled-jsx with a custom server? I see you have a request handler in the readme, but I'm not sure how to wire that up to this:

```js
const micro = require('micro')
const match = require('micro-route/match')
const { parse } = require('url')
const next = require('next')

const port = parseInt(process.env.PORT, 10) || 3000
const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

const server = micro(async (req, res) => {
  const parsedUrl = parse(req.url, true)
  const { query } = parsedUrl

  if (match(req, '/a')) {
    return app.render(req, res, '/b', query)
  } else if (match(req, '/b')) {
    return app.render(req, res, '/a', query)
  }

  return handle(req, res, parsedUrl)
})

app.prepare().then(() => {
  server.listen(port, err => {
    if (err) throw err
    console.log(`> Ready on http://localhost:${port}`)
  })
})
```

I'd be happy to contribute back some documentation around this (or a PR example to the next.js repo) if you could help clarify this for me.

Cheers!

**Comment by giuseppeg** [comment]
hi @tkellen! I just tried the [custom-server example](https://github.com/zeit/next.js/tree/master/examples/custom-server) from the Next.js repo and SSR seems to work fine. `handler` would just handle all the routes except for `/a` and `/b`. What is your setup? Do you mind sharing a sample Next.js app / repo?

**Comment by tkellen** [comment]
Hi @giuseppeg! Here's the project so far:

https://github.com/tkellen/thewoodlandkitchen

To reproduce, compare initial render in dev vs build. Everything looks great in dev. In the built version the styles from `layouts/main.js` do not seem to be present.

Thanks in advance for looking at this. Heads up, the repo is a bit heavy (lots of images that will eventually be on a CDN).

**Comment by giuseppeg** [comment]
uhm there is a bit too much going on there and honestly I can't tell what is broken. When I view the source I can find the styles from `layouts/main.js` in both dev and prod mode, but I may be missing something. Can you make a simplified test case (just a page with one element and a background-color maybe)?

**Comment by tkellen** [comment]
Sure can. Ack. I should have started with an isolated test case. Apologies for the wasted time.

For clarity sake, the reason I asked the question to begin with was because of this line in the README:

> It's paramount that you use one of these two functions so that the generated styles can be diffed when the client loads and duplicate styles are avoided.

To my mind that says I need to *do* something to get SSR rolling for styled-jsx.

I'll break it down to something small and reproducible (and probably figure out the issue on my own in doing so) later today. Will follow up with my results soon!

**Comment by giuseppeg** [comment]
No worries! Yeah the reason why it is "paramount" is that styled-jsx's SSR helpers add an id to the `style` tag that we can later use to select pre-rendered styles and avoid duplicates / initial client side rendering.

**Comment by giuseppeg** [comment]
@tkellen any update?

**Comment by tkellen** [comment]
Hi @giuseppeg! No, I've been pretty swamped with work since I posted this. I will be able to answer this in early November (I'm finishing up a rather long contract that has me totally swamped until the end of October).

I'm pretty confident I can resolve the issue. If it would make you feel better to have one less issue open, feel free to close this. I'll be sure to reply with my findings either way :)

**Comment by tkellen** [comment]
PS: Thanks for asking!

**Comment by giuseppeg** [comment]
@tkellen no worries or pressure :) I am quite busy as well with work  and stuff so I can empathize – I just asked in case you needed help and because I realized that I never came back to this issue.

**Comment by steida** [comment]
Is SSR docs in readme actual? For me, it seems it works out of the box.

**Comment by giuseppeg** [comment]
Closing this. Happy to reopen in case you need help again :)
