### ISSUE TITLE
`>` is rendered as `&gt;` on the server

### ISSUE THREAD

**Issue by ifyio** [zeit/styled-jsx#277]
When rendered on the server

```css
.Foo > *:not(:first-child) {
  ...
}
```

is rendered as 

```css
.Foo &gt; *:not(:first-child) {
  m...
}
```

and this causes the initial styling to not be proper

**Comment by giuseppeg** [comment]
Just tried and it seems to work fine, can you put together a sample repo to reproduce?

**Comment by ifyio** [comment]
Actually I just realised that I was doing `<style>` instead of `<style jsx>`. Apologies for the time waste. I will close this issue.

**Comment by giuseppeg** [comment]
no worries!
