### ISSUE TITLE
ant-design not working with style-jsx

### ISSUE THREAD

**Issue by johhansantana** [zeit/styled-jsx#278]
I'm having problems with ant.design and nextjs built in `style-jsx` they aren't applying

 ```
<Button className={'login-form-button'}>
  hello
</Button>
{/*language=CSS*/}
<style jsx>{`
  .login-form-button {
    width: 100%;
  }
`}</style>
```

doesn't seem to work unless I use the `global` property on `style jsx global`

**Comment by johhansantana** [comment]
@timneutkens clarified this since it's a separate component I have to use
`div :global(.login-form-button)`

**Comment by timneutkens** [comment]
👌

**Comment by guanpengchn** [comment]
@johhansantana  Could you use style-jsx in ant design components? I config the babel file and code it as the example. But it doesn't work. Please tell me how to use it. Thank you very much.
