### ISSUE TITLE
external styles with module exports

### ISSUE THREAD

**Issue by manglobe** [zeit/styled-jsx#280]
This is the first time ,I'm using styled-jsx with next.js to write.
It's very great to write all the html, css ,js in one file.
But now  I  have a simple whim about the dynamic styles.

When I see the styled-jsx write all the css-style in string template ,
I want to  extract all the styles into one file.

Just like this:
```
//product .js
const product ={
  index:`div{
              width:100px;
              height:100px;
            }
           div.a{
              backgound-color: #fff;
           }
`,
}
module.exports = { product};
```
```
// index.js
import { product } from 'product';
export default props => <div><style jsx>
     {`${product.index }`}
    </style>
</div>
```
I wish it will be compiled as this:
```
div[data-jsx=*]{
              width:100px;
              height:100px;
            }
           div.a[data-jsx=*]{
              backgound-color: #fff;
           }

```
but it compiled as this:
```
[data-jsx=*]{
div{
              width:100px;
              height:100px;
            }
           div.a{
              backgound-color: #fff;
           }
}
```

**Comment by giuseppeg** [comment]
as stated in the README:

N.B. We support CommonJS exports but you can only export one string per module:

```js
module.exports = `div { color: green; }`

// the following won't work
// module.exports = { styles: `div { color: green; }` }
```

This however works with ES6 `exports` (default and named) so you could do:

```js
export const foo = `div { color: red }`
export const bar = `p { font-size: 10px }`
```

and then import them as usual

```js
import { foo, bar } from '../product-styles'

// ...
<style jsx>{foo}</style>
<style jsx>{bar}</style>
```

**Comment by manglobe** [comment]
@giuseppeg  Thanks for your quickly reply!
And  sorry, it's my wrong. I haven't read the README clearly.  
But an other thing I want to know ,is that I import the style as string type into es6 string template, but why the code after compile was enclosed in braces ? 
And I had try a lot of way to do this ,every time the `{}` will around  the `${}` after compile, because of this the  `[data-jsx=*]`  will be added before the first `{` .

**Comment by giuseppeg** [comment]
@manglobe can you create a minimal repo on github to reproduce the issue so that I can take a look? maybe use Next.js

**Comment by manglobe** [comment]
@giuseppeg
just like this:
```
const x = `div{
    font-size: 20px;
  }
  div{
    width: 10px;
  }`;

export default props =>
  <div>
    <style jsx>
      {
        `
        div{
          display: inline-block;
        }
        ${x}
        `
      }
    </style>
  </div>;
```

I wish it will be compiled as
```
div[data-jsx-*]{
          display: inline-block;
        }
div[data-jsx-*]{
    font-size: 20px;
  }
div[data-jsx-*]{
    width: 10px;
  }
```
But it was compiled as 
```
div[data-jsx-*]{
          display: inline-block;
        }
[data-jsx-*]{
  div{
    font-size: 20px;
  }
  div{
    width: 10px;
  }
}
```

of course,this one works well
```
const x = `#fff`;
export default props =>
  <div>
    <style jsx>
      {`
       div{
         color: ${x};
       }
  `}
    </style>
  </div>;
```

**Comment by giuseppeg** [comment]
Ok you can't reference external styles like that. External styles should be reference is a separate `style` tag:

```jsx
export default props =>
  <div>
    <style jsx>{`
        div { display: inline-block; }
     `}</style>
    <style jsx>{x}</style>
  </div>;
```
