### ISSUE TITLE
A similar css has led to some problems

### ISSUE THREAD

**Issue by czy0729** [zeit/styled-jsx#281]
A List Page and a Detail Page.
I wrote a function to generate a class prefix so I not need to think a unique class, but this made a problem。
Look at the 2 gif, one is refresh then List into Detail, and other is refresh then Detail into List.

![gif](https://user-images.githubusercontent.com/13514316/30464401-e3fbabe8-9a03-11e7-8d65-8ff4cd3398bc.gif)

![gif2](https://user-images.githubusercontent.com/13514316/30464486-557f670a-9a04-11e7-8dd4-a902fd13a84f.gif)

I think because the two page has the same css, but the prefix is not the same. 
![tim 20170915105524](https://user-images.githubusercontent.com/13514316/30464507-730193fc-9a04-11e7-9b51-85d2a5d7cfd4.png)

I saw when into a new page, the old style will be deleted. and goBack to the old page, the style not append. 

I guess the styled-jsx fail to judge the variable and not append the old style.

Then I modified one of the styles to make them a little different and it work well.
![tim 20170915110247](https://user-images.githubusercontent.com/13514316/30464679-8873bed0-9a05-11e7-89e9-630a15e1782b.png)

**Comment by giuseppeg** [comment]
@czy0729 can you put together a sample repo (very minimal) with the necessary code to reproduce the issue? Looking at some code and try it would make it easier to understand what is going on.

**Comment by czy0729** [comment]
I try to write the code in codepen , but I don't know how to import styled-jsx in codepen (；′⌒`)

I make a function to generate unique class like
```javascript
function generateUniqueId() {
   return `styles-${uniqueId++}`;
}
```
So I can get different class in different js to pass to the third-party component because I hate to wrap a unnecessary div.
```jsx
const prefixCls = generateUniqueId();

<CountDown 
    className={`${prefixCls}__count-down`}
    start={beginTime}
    end={endTime}
    current={current}
/>

<style jsx global>{`
    .${prefixCls}__count-down {
        position: absolute;
        top: 0;
        left: ${Styles.wind};
    }
`}</style>
```

But this solution causes me to appear in two pages with exactly the same code and resulting in the following:

Page List
![1](https://user-images.githubusercontent.com/13514316/30527558-d834de64-9c5c-11e7-9745-7ebc2e4e9dda.png)

and goto the Page Detail
![tim 20170918101956](https://user-images.githubusercontent.com/13514316/30527562-edb9e52c-9c5c-11e7-8d30-0827913d4ccf.png)

now goBack to the Page List
![3](https://user-images.githubusercontent.com/13514316/30527575-103f4998-9c5d-11e7-9b31-8b58df995a35.png)

![tim 20170918102240](https://user-images.githubusercontent.com/13514316/30527595-27eb45a6-9c5d-11e7-9f3a-0aab052188b1.png)

styles-2__count-down has lost, so the left padding is 0
![tim 20170918102252](https://user-images.githubusercontent.com/13514316/30527600-2c3f5836-9c5d-11e7-8b44-9a9248bc30c6.png)


now I made two style a little different like one page is
```javascript
<style jsx global>{`
    .${prefixCls}__count-down-b {
        position: absolute;
        top: 0;
        left: ${Styles.wind};
    }
`}</style>
```
and became well

**Comment by czy0729** [comment]
@giuseppeg is there some config can disable the performance of `auto delete historical  styles` ?
