### ISSUE TITLE
Warning about static CSS

### ISSUE THREAD

**Issue by MFCo** [zeit/styled-jsx#282]
Just wanna ask if it's possible to add a warning in this case:

```javascript

var padding = '30px';
var width = '1200px';
export default function PageLayout({ children, change }) {
  if (change) {
    padding = '0px';
    width = '100%';
  }

  return (
    <div>
      <div className={`page-layout__body`}>
        {children}
      </div>
      <style jsx>{`
        .page-layout__body {
          max-width: ${width};
          margin: 0 auto;
          padding: 0 ${vars.paddingForPages} ${padding};
          min-height: calc(100vh - 150px);
        }
      `}</style>
  </div>
```
In this case  you don't get what you expect in every situation. When you swap from one page with 'change' activated to another one without 'change' activated, in client side, the style remains without any alteration, I mean with padding 0px and width 100%. But if you swap making a server side request this work as you expect. 

I think I understand why is it happening, I just managed this situation by changing the classname so I can target another style when I need to change both values.

But I just wanna ask if it's too difficult to add a warning when this kind of situations happen.

**Comment by giuseppeg** [comment]
As soon as you use props this is not static css anymore. It will be fixed with #81 which is ready for review so it might go out soon.
