### ISSUE TITLE
Trouble exporting styles as default

### ISSUE THREAD

**Issue by jesper-johansson** [zeit/styled-jsx#283]
I have a "Title" component that looks like this:
```
import style from './styles';

const Title = ({ children = '' }) => (
  <header className="title">
    <style jsx>{style}</style>
    <h1>
      {children}
    </h1>
  </header>
);
```
and a styles.js file that looks like this:
```
export const styles = `
  .title {
    color: red !important;
  }
`;

export default `
  .title {
    color: red !important;
  }
`;
```

For some reason this doesn't work: `import style from './styles'` and I get no data-jsx tag,
but this does work: `import { styles } from './styles'` and I get the data-jsx-ext tag.
(I also change to `<style jsx>{styles}</style>` then ofc)

I looked through the issues and according to this comment it should work with default exports?
https://github.com/zeit/styled-jsx/issues/215#issuecomment-304621954

**Comment by giuseppeg** [comment]
did you try to give the default export a different name?

**Comment by jesper-johansson** [comment]
@giuseppeg Sorry my bad. I must have done something else wrong because I can't reproduce this anymore...
