### ISSUE TITLE
[class*='class_name'] dont work

### ISSUE THREAD

**Issue by bouzoumita** [zeit/styled-jsx#285]
I'm writing a website with react and next.js.
I have some css to handle different screen size(responsive) witch is done like so:
```
 @media (min-width: 1px) and (max-width: 768px) {
      [class*='grid__col--'] {
        margin-top: 12px;
        margin-bottom: 12px;
      }
    }
```
the problem is that the inside ( [class*='grid__col--'] ) does not work but when i put some other thing it work i dont Know if it is an issue or some misunderstood by me.

**Comment by giuseppeg** [comment]
What do you mean by "it doesn't work"? Can you provide more details / the output?

**Comment by bouzoumita** [comment]
it seems that is not an issue i just used wrong i was putting the style tag inside the Head tag
