### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by sandyplace** [zeit/styled-jsx#29]
Is it possible to use this with typescript as I don't know if the typescript compiler integrates with babel? Or would you just need to do a pre-compilation step with babel?

**Comment by rauchg** [comment]
Yeah, unfortunately this is babel-only. I wonder if TypeScript can support a subset of the babel API to allow for this plugin to work.

Or alternatively, TypeScript could be re-implemented as babel transformations (pipedream)
