### ISSUE TITLE
Optional dynamic styles

### ISSUE THREAD

**Issue by jaydenseric** [zeit/styled-jsx#297]
What is the best way to write optional dynamic style rules? As in, rules that do not appear at all in the generated styles unless a value is proved via `props`.

The best I came up with so far is this monstrosity:

```jsx
const Para = ({ marginTop, marginBottom, maxWidth = '28', children }) => (
  <p>
    {children}
    <style jsx>{`
      p {
        ${marginTop ? `margin-top: ${marginTop}em;` : ''}
        ${marginBottom ? `margin-bottom: ${marginBottom}em;` : ''}
        max-width: ${maxWidth}em;
      }
    `}</style>
  </p>
)
```

Issues:

- The rules (e.g. `margin-top`) are not syntax highlighted.
- It's inelegant having the empty strings on else.
- The lines don't end with `;`, causing prettier to format like this:

```jsx
const Para = ({ marginTop, marginBottom, maxWidth = '28', children }) => (
  <p>
    {children}
    <style jsx>{`
      p {
        ${marginTop ? `margin-top: ${marginTop}em;` : ''} ${marginBottom
            ? `margin-bottom: ${marginBottom}em;`
            : ''} max-width: ${maxWidth}em;
      }
    `}</style>
  </p>
)
```

**Comment by giuseppeg** [comment]
I am not sure if there is a "best way to...". Frankly I would use inline styles in this case and in many other when it is about dynamic values (unless styles applies on hover, focus, media query and so on).

Inline styles are great!

Right now you have a few more options:

* declare the value outside of jsx and reference it:

```jsx
const Para = (props) => {
   const marginTop = `margin-top: ${marginTop}em;` : ''
   return (
      <p>{props.children}
          <style jsx>{`p { ${marginTop} max-width: ${props.maxWidth}em; }` }</style>
      </p>
   )
}
```

or 

* use a generic function `p { ${marginTopIfDefined(marginTop)} }`

It is worth to mention that expressions are not preprocessed so in some cases you might not get auto prefixing or (worse) scoped selectors if you interpolate a css block – I will probably add a warning at some point.

```jsx
const someStyles = `div { color: red }` // div won't be scoped
<style jsx>{`p {  font-size: 1em } ${someStyles}` }</style>
```

I put together a proposal for conditional `style` tags https://github.com/zeit/styled-jsx/issues/290 which should cover your use case and make things a bit more tidy.

**Comment by jaydenseric** [comment]
One thing I dislike about inline styles in this situation is how they bloat the SSR HTML with repeated style strings. With v2 dynamic values, if `Para` is used 30 times with similar padding props, are the class names shared? Or is the output even more repetitive than inline styles?

**Comment by giuseppeg** [comment]
> if Para is used 30 times with similar padding props, are the class names shared

Yes they are of course! Styles are deduped

**Comment by jaydenseric** [comment]
Great! So inline styles might add 1kb to the initial load of long pages with repeated components, in comparison to using v2 dynamic values.

**Comment by jaydenseric** [comment]
Ok, so it seems there is no consequence when leaving behind redundant `;` when certain props are undefined, so I think this might be the final syntax I refactor all my inline styles to:

```jsx
const Para = ({ marginTop, marginBottom, maxWidth = '28', children }) => (
  <p>
    {children}
    <style jsx>{`
      p {
        ${marginTop && `margin-top: ${marginTop}em`};
        ${marginBottom && `margin-bottom: ${marginBottom}em`};
        max-width: ${maxWidth}em;
      }
    `}</style>
  </p>
)
```
