### ISSUE TITLE
Concat of className seems to miss prefix?

### ISSUE THREAD

**Issue by slaskis** [zeit/styled-jsx#300]
Using the new beta (2.0.1-beta.5)...

We have external styles like this:

```js
export const verticalPadding = css`
  .verticalPadding { padding-top: 1em; padding-bottom: 1em; }
`

export const global = css`
  // reset css, font decl. etc
`
```

And then when we use it like this:

```js
import {verticalPadding} from "./styles.js"

const Section = ({}) => (
  <section className="verticalPadding">
    <style jsx>{verticalPadding}</style>
    <style jsx>{`
      section { margin: 1em; }
    </style>
  </section>
)
```

It renders like this:

```html
<section class="jsx-3588377366 1169594943 verticalPadding">
```

Which seems like it removed the `jsx-`-prefix from the external verticalPadding style (there's a `.verticalPadding.jsx-1169594943` selector in the DOM).

The result is that the external styles are not implemented at all. But if we change the class attribute to look like this:

```html
<section class="jsx-3588377366 jsx-1169594943 verticalPadding">
```

It seems to work again...

**Comment by giuseppeg** [comment]
@slaskis can you help me reproduce? Maybe you can create a simple Next.js app and push it on github?

From the snapshots it seems right 
https://github.com/zeit/styled-jsx/pull/301/files#diff-d88bcbd8d6ddd1946a5df67964db4227

Also here is where we are adding the `jsx-` prefix https://github.com/zeit/styled-jsx/blob/master/src/babel.js#L170-L181

**Comment by slaskis** [comment]
I can give it a shot. I've reproduced it in the snapshots of our app but I'll see if I can reduce it to something smaller.

**Comment by slaskis** [comment]
Super impressed by your quick turn around btw :)

**Comment by giuseppeg** [comment]
hah I've got notifications on and know the codebase by heart :) 
A failing test would be good too! You can clone the branch from my PR and try to add one there or prepare a separate PR

**Comment by slaskis** [comment]
Here's the simplest test I could make:

https://github.com/slaskis/styled-jsx-test

**Comment by slaskis** [comment]
![image](https://user-images.githubusercontent.com/5991/31342323-b0657fe0-ad0c-11e7-9f2c-10b7f4849222.png)

**Comment by giuseppeg** [comment]
the bug might be somewhere here https://github.com/zeit/styled-jsx/blob/master/src/_utils.js#L254

**Comment by slaskis** [comment]
🎉

**Comment by giuseppeg** [comment]
@slaskis I was in a rush and I didn’t have time but the bug was clear to me when I figured it out and your repo worked once I fixed it. I’ll see if I can add an adhoc test tomrrow
