### ISSUE TITLE
How to use const and this.props in dynamic styles?

### ISSUE THREAD

**Issue by tomsoderlund** [zeit/styled-jsx#307]
I'm trying to use `const`’s in [styled-jsx dynamic styles](https://github.com/zeit/styled-jsx#dynamic-styles):

	export default class Image extends React.Component {

		render () {
			const myColor = 'lime';

			return <div>
				<style jsx>{`
					div {
						background: ${myColor};
					}
				`}</style>
			</div>
		}

	}

...gives me:

	Module build failed: SyntaxError: Expected `myColor` to not come from the closest scope.
	Styled JSX encourages the use of constants instead of `props` or dynamic values which are better set via inline styles or `className` toggling. See https://github.com/zeit/styled-jsx#dynamic-styles

And when I try with `this.props`:

	export default class Image extends React.Component {

		render () {
			return <div>
				<style jsx>{`
					div {
						border: 3px solid tomato;
						background: ${this.props.style};
					}
				`}</style>
			</div>
		}

	}

...I get:

	Module build failed: SyntaxError: Expected a constant as part of the template literal expression (eg: <style jsx>{`p { color: ${myColor}`}</style>), but got a MemberExpression: this.props

What’s the proper approach?

**Comment by giuseppeg** [comment]
Which version of styled-jsx are you using? Are you using Next4?

**Comment by tomsoderlund** [comment]
@giuseppeg No, styled-jsx v1.0.11 and Next.js v3.2.2.

**Comment by giuseppeg** [comment]
v1.0.11 doesn't support dynamic styles

**Comment by timneutkens** [comment]
You need to upgrade to next v4 👍

**Comment by tomsoderlund** [comment]
OK, thanks, an upgrade to Next.js 4 solved this. Thanks @giuseppeg!
