### ISSUE TITLE
Unfortunately nesting is not supported by styled-jsx

### ISSUE THREAD

**Issue by J-Gallo** [zeit/styled-jsx#310]
Hi there !

`.a { 
    p {
      color: red;
    }
}`

The code above is throwing the error: Unfortunately nesting is not supported by styled-jsx

Is any plan to support nesting in styled-jsx ? Or is there a workaround to fix this ?

Thanks !

**Comment by J-Gallo** [comment]
Just saw https://github.com/zeit/styled-jsx/pull/190 but I think that the issue is still valid.

**Comment by Huvik** [comment]
You can use postcss in meanwhile

**Comment by giuseppeg** [comment]
styled-jsx is never going to support non standard CSS features, however soon (like this weekend) I will release a new version that introduces a plugin system which will allow to use SASS, PostCSS or really processing your styles as you please - I already wrote two sample plugins 
https://github.com/giuseppeg/styled-jsx-plugin-sass
https://github.com/giuseppeg/styled-jsx-plugin-postcss

**Comment by J-Gallo** [comment]
Thanks for the answer. I will try de sass plugin.

**Comment by corysimmons** [comment]
https://github.com/giuseppeg/styled-jsx-plugin-postcss + postcss-next = W3C spec nesting

```css
.foo {
  & .bar {
    background: blue;
  }
}
```

**Comment by scythargon** [comment]
Still can't setup this >< 
installed `styled-jsx-plugin-postcss`, added it to babel config, and `postcss-preset-env` (which replaces `postcss-cssnext` nowadays)

created `postcss.config.js`: 
```
module.exports = {
  parser: 'sugarss',
  plugins: {
    'postcss-plugin': {},
    'postcss-preset-env': {},
  }
}

```
Now I get:
![image](https://user-images.githubusercontent.com/1755870/51101827-316efc80-17fe-11e9-84f3-d7096d221155.png)

but still
![image](https://user-images.githubusercontent.com/1755870/51101848-4ba8da80-17fe-11e9-9a9c-2ee56fd390ad.png)

Can you please tell me where am I wrong?

**Comment by ekanant** [comment]
When I import bootstrap.css from node_modules It has error

`Error: Nesting detected at 31452:1. Unfortunately nesting is not supported by styled-jsx.`

I found that the error is from this style, It's from navbar bootstrap 4, How can I fix this?
```
.navbar-dark .navbar-toggler-icon {
  background-image: url("data:image/svg+xml,%3csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3e%3cpath stroke='rgba(255, 255, 255, 0.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e");
}

.navbar-light .navbar-toggler-icon {
  background-image: url("data:image/svg+xml,%3csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3e%3cpath stroke='rgba(0, 0, 0, 0.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3e%3c/svg%3e");
}
```

**Comment by itsthomas** [comment]
Yes, the problem happens if you try to use an svg image as background.
Is there any solution for this?
