### ISSUE TITLE
Disable warning about nesting when using plugins

### ISSUE THREAD

**Issue by connor-baer** [zeit/styled-jsx#315]
- [x] I have searched the [issues](https://github.com/zeit/styled-jsx/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Using plugins with `styled-jsx` should enable me to use nesting in my css without throwing errors.

## Current Behavior

Using `next@4.0.5` and `styled-jsx@2.1.1` and the new plugin system with `styled-jsx-plugin-postcss`, the following error is thrown: 

```
Nesting detected at 11:9. Unfortunately nesting is not supported by styled-jsx.
```

## Steps to Reproduce (for bugs)

The error is easily reproducible by running the [`with-styled-jsx-plugins`](https://github.com/connor-baer/next.js/tree/fix/example-styled-jsx-deploy/examples/with-styled-jsx-plugins) example. Here's the error log from my failed deployment: https://zeit.co/connor_baer/basic-css/dxyconjkcx/logs

## Your Environment

| Tech    | Version |
|---------|---------|
| next    | 4.1.0        |
| styled-jsx    | 2.1.1        |
| node    | 8.6.0        |
| OS      | macOS 10.13.1        |
| browser | Chrome 61        |

**Comment by timneutkens** [comment]
@connor-baer It actually works just fine. The problem is that the example still depends on next 4.0.4 instead of 4.1.0, will update it right now. A simple `yarn add next` will fix your issue 😄 I've tested postcss-nested with this and it worked perfectly 👌

**Comment by connor-baer** [comment]
@timneutkens Whoops, didn't check the dependency in the example. 😬 

However, the problem still occurs in my own code, even with Next 4.1.0. I'll investigate a bit more, and if I can't get it to work, I'll provide another test case 👍

**Comment by timneutkens** [comment]
Might be babel cache. Try removing `./node_modules/.cache`

**Comment by connor-baer** [comment]
I got it to work by adding `postcss-nested`. Initially I was only using `postcss-cssnext` which is [supposed to support nesting](http://cssnext.io/features/#nesting) (and it has worked in the past). Oh well, as long as it works now 🤷‍♂️

**Comment by timneutkens** [comment]
Strange that it didn't work with postcss-cssnext. Glad you figured it out though 🙌
