### ISSUE TITLE
Separate files with raw css code

### ISSUE THREAD

**Issue by IharKrasnik** [zeit/styled-jsx#317]
Hi!
There is an example of keeping css in separate files in the project's [Readme](https://github.com/zeit/styled-jsx#keeping-css-in-separate-files).
However it shows only how to keep js exports in a separate file using css`styled-jsx/css, but not a raw css code.
Is it possible to keep a raw css code in a separate file and import it by react components, probably with the help of babel-plugin-inline-import and other plugins?

---

Desired behavior

```js
// component.js
import styles from './styles.pcss';
export default () => {
  <div className="scoped-component">
    <style jsx> {styles} </style>
    <h1> Hello </h1>
  </div>
}
```

```css
/* styles.pcss */
.scoped-component {
  & h1 {
    color: red;
  }
}
```

(*.pcss is postcss with cssnext plugin, but it doesn't really matter)

**Comment by giuseppeg** [comment]
This is out of the scope of this plugin, I believe that you can turn regular files into js modules already with some tool/babel plugin or custom script
