### ISSUE TITLE
Prettier + eslint autofix issue

### ISSUE THREAD

**Issue by jasondonnette** [zeit/styled-jsx#320]
When using prettier with eslint integration, it turns this this:
```
<style jsx>{`
  p {
    color: red;
  }
`}</style>
```

Into this:
```
<style jsx>
  p {
    color: red;
  }
</style>`
```

I have to disable `react/jsx-closing-tag-location` and `react/jsx-curly-brace-presence` for it to work correctly. 

For me it was to set this in .eslintrc:
```
"rules": {
  "react/jsx-closing-tag-location": 0,
  "react/jsx-curly-brace-presence": 0
}
```

It's not necessarily a bug worth fixing, but I wanted to post this in case anyone runs into it - took me a while to realize it wasn't an issue with how prettier handles styled-jsx.

**Comment by particle4dev** [comment]
@jasondonnette thank you so much, you just save my day :)
This is why I love open source. People always want to share something to help others.
