### ISSUE TITLE
Styled jsx with plugins without next.js

### ISSUE THREAD

**Issue by Huvik** [zeit/styled-jsx#323]
Hey,
i am wondering how properly, implement styled-jsx with plugins in react project.
I made simple repo with `styled-jsx-plugin-postcss` and `postcss-nested`, but i wont work because error message `Unfortunately nesting is not supported by styled-jsx.` So its possible to debug if postcss plugin is loaded or how to debug it in general? 
Repo: https://github.com/Huvik/styled-jsx-test

**Comment by giuseppeg** [comment]
Makes sure that the path to the plugins is correct, in case try to resolve them like it is mentioned in the docs.

There is no way to debug this right now, if you have any ideas on how to improve this it'd be great. 
Maybe we can print out debugging info like "Loading styled-jsx plugins.. Plugin "plugin-name" loaded..." etc.

**Comment by Huvik** [comment]
Yea, it would be helpfull,because now i dont know if plugin is corrected loaded or not, because i tried sass and postcss plugins. Sass is working correctly, but i dont know if postcss is loaded or not. I tried adding full path and still god nested css, even that i have postcss nested.
