### ISSUE TITLE
Styles does not apply for elements rendered outside the render function

### ISSUE THREAD

**Issue by aviramga** [zeit/styled-jsx#328]
Hi,

I noticed that when calling a method that returns dom elements from the render the styles of the component does not apply for the elements returned.
For example:

```
renderAnotherElement() {
    return (<div className='another-class'></div>)
}
render() {
     <div className='some-class'>
        {renderAnotherElement()}
     <style jsx>{importedStyles}</style>
     </div>
}
```

styles defined on some-class will work, but for the another-class it wouldn't. Is this intentional behavior? I know styles are scoped so no nested components gets their father's styles,  but these are not nested components.....

Thanks for the help!

**Comment by giuseppeg** [comment]
It's always been like this and I don't think we will change any time soon. See https://github.com/zeit/styled-jsx/issues/42

**Comment by aviramga** [comment]
@giuseppeg is there a workaround for this?

**Comment by giuseppeg** [comment]
I don't think so, just split your component into smaller ones
