### ISSUE TITLE
Rewrite complex spread props breaks

### ISSUE THREAD

**Issue by ndreckshage** [zeit/styled-jsx#329]
Wasn't 100% sure how to title this, but...

compile error `Cannot read property '0' of null`
```
const Component = props => {
  return (
    <div>
      <div
        {...(props.something
          ? {}
          : {
              onClick: () => {
                alert(1);
              }
            })}
      >
        hello
      </div>
      <style jsx>{`
        div {
          color: blue;
        }
      `}</style>
    </div>
  );
};
```

no compile error:
```
const Component = props => {
  const sameThingAsVar = props.something
    ? {}
    : {
        onClick: () => {
          alert(1);
        }
      };

  return (
    <div>
      <div {...sameThingAsVar}>hello</div>
      <style jsx>{`
        div {
          color: blue;
        }
      `}</style>
    </div>
  );
};
```

**Comment by ndreckshage** [comment]
btw in my apps im just pulling up into a var. but wouldnt be surprised if others porting a reasonable big project from v1 to 2. but other than that seems to be a seamless upgrade - amazing!

**Comment by giuseppeg** [comment]
@ndreckshage thanks for the bug report. The issue is indeed with such a complex spread expression. 
I will try to make it work for complex cases like that too. In the meantime your solution is what I would I have gone for too

**Comment by guigrpa** [comment]
I have a simpler repro. Indeed there seems to be a problem with the spread operator, but also in simpler cases.

**This compiles:**

```js
import React from 'react';
const A = props => (
  <div className="a-component" {...props}>
    <style jsx>{`.a-component { color: red; }`}</style>
  </div>
);
export default A;
```

**But this doesn't:**

```js
import React from 'react';
class A extends React.Component {
  render() {
    return (
      <div className="a-component" {...this.props}>
        <style jsx>{`.a-component { color: red; }`}</style>
      </div>
    );
  }
}
export default A;
```

**A workaround that compiles again:**

```js
import React from 'react';
class A extends React.Component {
  render() {
    const { props } = this;
    return (
      <div className="a-component" {...props}>
        <style jsx>{`.a-component { color: red; }`}</style>
      </div>
    );
  }
}
export default A;
```

**Comment by giuseppeg** [comment]
good point @guigrpa @ndreckshage would you have time to at least fix the `{...this.props}` case? It shouldn't be hard.. here is the code which alterate the attributes https://github.com/zeit/styled-jsx/blob/master/src/_utils.js#L24-L78 

I think that the issue is here https://github.com/zeit/styled-jsx/blob/master/src/_utils.js#L33-L38
Basically it works only with identifiers eg. `props` while it should also work with MemberExpressions like `this.props` 

astexplorer.net and https://github.com/babel/babel/tree/master/packages/babel-types might be very helpful

**Comment by guigrpa** [comment]
I found a better workaround (notice the order of the props passed to the `div`):

```js
import React from 'react';
class A extends React.Component {
  render() {
    return (
      <div {...this.props} className="a-component">
        <style jsx>{`.a-component { color: red; }`}</style>
      </div>
    );
  }
}
export default A;
```

**Comment by giuseppeg** [comment]
yep it might be a workaround for your use case if you're never passing a `className` prop :)

**Comment by giuseppeg** [comment]
@ndreckshage I don't think that we are going to fix the original issue but @pudility fixed other common use cases like `{...this.props.something}` and `{...props.something}`
