### ISSUE TITLE
Question about optimizeForSpeed

### ISSUE THREAD

**Issue by callumlocke** [zeit/styled-jsx#330]
From readme:

> Beware that when using this option source maps cannot be generated and **styles cannot be edited via the devtools**.

I'm confused by this, what does it mean? I can still edit styles in devtools.

**Comment by giuseppeg** [comment]
In prod `optimizeForSpeed` is automatically set to true (unless you set it to false explicitly). This mode uses the CSSOM API which lets you insert only valid css rules (no comments) and makes styles read only (can’t be edited cia devtools)

**Comment by callumlocke** [comment]
Thanks but I still don't understand. I **can** still edit styles in devtools, even with this option enabled. In what sense are they 'read only'?

**Comment by giuseppeg** [comment]
@callumlocke please try https://jsfiddle.net/cgdmda0n inspect the `body` element. You shouldn't be able to change the `background-color` property
