### ISSUE TITLE
sourceMappingURL included in production build

### ISSUE THREAD

**Issue by chemzqm** [zeit/styled-jsx#332]
Hi, I'm using next.js version 3.2.2, after I use `NODE_ENV=production next build` I found `sourceMappingURL` still exists in javascript files:

<img width="1282" alt="screen shot 2017-10-23 at 3 41 11 pm" src="https://user-images.githubusercontent.com/251450/31877481-394a90f0-b809-11e7-90a5-0c3aa2031d7c.png">

I have configuration `config.devtool = dev ? 'cheap-module-eval-source-map' : false` in my `next.config.js`, please let me know if it's bug or there could be something wrong with my configuration, thanks.

**Comment by giuseppeg** [comment]
please open an issue on the Next repo

**Comment by chemzqm** [comment]
I found the latest next have the feature for setting styled-jsx options in .babelrc.
