### ISSUE TITLE
Cannot find module 'styled-jsx/style.js'

### ISSUE THREAD

**Issue by tflx** [zeit/styled-jsx#334]
I'm trying to use external styles with styled-jsx.
It's a simple test build on the "with-firebase-hosting" example. The error happens on development and when deployed to firebase.

In the "pages" index.js there is a Link to the about.js route.
The error only happens on reload of about page - NOT when clicking link from index.js to about.js

about.js has this "Test" component:
```
import React from 'react';
import PropTypes from 'prop-types' // eslint-disable-line no-unused-vars
import styles from './Test-style.js';

const propTypes = {
};

const defaultProps = null;

function Test() {
  return (
    <span>
      <div className="title">Test</div>
      <style jsx>{styles}</style>
    </span>
  );
}

Test.propTypes = propTypes;
Test.defaultProps = defaultProps;

export default Test;
```

Test-style.js:

```
import css from 'styled-jsx/css'

export default css`
  .title {
    color: green;
  }
`
```

| Tech    | Version |
|---------|---------|
| next    |    4.1.3     |
| node    |    8.6.0     |
| OS      |     macOS 10.12.6    |
| browser |    Chrome 61     |

**Comment by giuseppeg** [comment]
@tflx can you push an example on github so that I can clone and see what's going on?

**Comment by tflx** [comment]
Sorry for the late reply - thank you for looking at it. Here it is:

https://github.com/tflx/ssr-react

**Comment by shaiatias** [comment]
i had the same issue. and i just solved it:

install npm package:
`npm install --save styled-jsx`

add the plugin to your babelrc:
`"plugins": [["styled-jsx/babel", { "optimizeForSpeed": true }]]`

**Comment by giuseppeg** [comment]
well yea the issues is that you didn't install styled-jsx and you don't have it in your babel configuration

**Comment by ctrlaltdylan** [comment]
Old topic, but I had to upgrade from `next@12.2.2` to `next@12.3.2` to fix the issue.

**Comment by ARiyou2000** [comment]
I have this issue after upgrading to the NextJs v15.0.2

**Comment by mattoattacko** [comment]
Sorry mate. I don’t really work as a developer anymore and am unsure how things have been affected with any of the new software updates. Good luck!-matt mcquainOn Oct 31, 2024, at 9:19 AM, ARiyou Jahan ***@***.***> wrote:﻿
I have this issue on builds after upgrading to the NextJs v15.0.2
