### ISSUE TITLE
How to use px2rem-loader or px2rem？

### ISSUE THREAD

**Issue by Gavin1995** [zeit/styled-jsx#335]
I use Webstorm Next.js and styled-jsx, but would like to convert <style jsx>{``}</style jsx> inside px to rem, how should i do it? Thank you

    // package.json
    "dependencies": {
        "antd-mobile": "^1.7.0",
        "next": "4.1.0",
        "react": "^16.0.0",
        "react-dom": "^16.0.0",
        "styled-jsx": "^2.1.1",
        "px2rem-loader": "^0.1.7",
    }

    //next.config.js I want to achieve the results
    module.exports = {
      webpack: (config, { dev }) => 
        config.module.rules.push(
          {
            test: /\.css$/,
            loader: 'style!css!px2rem?remUnit=75&remPrecision=8'
          }
        );
        return config
      }
    }

**Comment by giuseppeg** [comment]
you can use a plugin like styled-jsx-plugin-postcss or make your own
