### ISSUE TITLE
Is this actually for React and not just JSX?

### ISSUE THREAD

**Issue by rssfrncs** [zeit/styled-jsx#336]
Going off of "Full CSS support for JSX without compromises" I expect that this library would work with my VueJS project which uses render functions and JSX instead of templates. 

However, after installing and adding a basic <style jsx> component to my render function I get the following error,

![image](https://user-images.githubusercontent.com/7808978/31945206-64e2ac30-b8c6-11e7-984c-01473c3c7e92.png)

Is this instead "Full CSS support for React JSX without compromises"? If this is the case i'd support for Vue! :+1:

**Comment by giuseppeg** [comment]
yes it depends on React too,m but if you have ideas to add support for Vue please let me know, tha would be awesome

**Comment by giuseppeg** [comment]
@rssfrncs by the way doesn't Vue have its own scoped styles system?

**Comment by rssfrncs** [comment]
@giuseppeg single file components (.vue) can have scoped css using `<style scoped>`. However this doesn't allow you to interpolate variables and isn't supported for those developers who prefer to use render functions and JSX. I'm currently using CSS modules but have started to look into css in js alternatives.

**Comment by giuseppeg** [comment]
Alright, I am not familiar with Vue but in order to use props and interpolation you need React right now.. although that part could be abstracted away very easily if Vue has similar concepts to lifecycle methods and so on. I am not sure I will have enough time to invest into this but I'll keep the issue open thank you :)

**Comment by giuseppeg** [comment]
Going to close this. Happy to reopen in case you have any idea how to make it work with Vue.
