### ISSUE TITLE
Passing parameters while loading CSS from external file

### ISSUE THREAD

**Issue by atulmy** [zeit/styled-jsx#337]
I'm trying to **load CSS from separate file** and also want to **pass some parameters** to make it dynamic but I'm getting this Error: `SyntaxError: Expected a template literal or String literal as the child of the JSX Style tag (eg: <style jsx>{`some css`}</style>), but got CallExpression` 

Component file
```
...
import styles from './style'
...

render() {
    const { children, theme } = this.props

    return(
        <div>
            <button>{ children }</button>

            <style jsx>{ styles(theme) }</style>
        </div>
    )
}
...
```

CSS File
```
import css from 'styled-jsx/css'

export default (theme) => (
    css`
        button {
            color: white;
            background-color: ${ theme === 'primary' ? 'red' : 'blue' };
        }
    `
)
```

**Comment by giuseppeg** [comment]
External styles dont work with dynamic styles. You may want to move the dynamic parts to inline style tags in your components

**Comment by atulmy** [comment]
😔 Abstracting away the entire CSS code provides much better code structuring and readability. Currently, since most of the CSS is dynamic (based on props) I'll have to clutter the Component code instead. Any chance of this to be implemented in future?

**Comment by atulmy** [comment]
CC: @rauchg @nkzawa

**Comment by jabacchetta** [comment]
I'd like to see this as well. I agree with @atulmy here and prefer to keep components clean.

**Comment by CGreenburg** [comment]
This is pretty old, but this is what I did to get by this error:

Component
```javascript
import styles from './style'
...

render() {
  const { children, theme } = this.props
  buttonStyle = styles(theme)
  return(
      <div>
          <button>{ children }</button>
          <style jsx>{ buttonStyle }</style>
      </div>
  )
}
```

style.js
```javascript
import css from 'styled-jsx/css'

export function style(theme) {
    return css`
        button{
            color: white;
            background-color: ${theme === 'primary' ? 'red' : 'white'};
        }
    `
}
```

**Comment by alabobriggs** [comment]
> This is pretty old, but this is what I did to get by this error:
> 
> Component
> 
> ```js
> import { style } from './style'
> ...
> 
> render() {
>     const { children, theme } = this.props
>     buttonStyle = style(theme)
>     return(
>         <div>
>             <button>{ children }</button>
>             <style jsx>{ buttonStyle }</style>
>         </div>
>     )
> }
> ```
> 
> style.js
> 
> ```js
> import css from 'styled-jsx/css'
> 
> export function style(theme) {
>     return css`
>         button{
>             color: white;
>             background-color: ${theme === 'primary' ? 'red' : 'white'};
>         }
>     `
> }
> ```

This worked for me
