### ISSUE TITLE
Doesn't work when returning an array - React 16

### ISSUE THREAD

**Issue by igor-ribeiro** [zeit/styled-jsx#338]
Code:
![image](https://user-images.githubusercontent.com/5148753/32054154-4072536a-ba3c-11e7-8091-e328ae9279c2.png)

Console:
![image](https://user-images.githubusercontent.com/5148753/32054089-0e231084-ba3c-11e7-99e6-b135850c55fe.png)

Compiled:
![image](https://user-images.githubusercontent.com/5148753/32054108-1e6a3878-ba3c-11e7-97e0-7cad2563706f.png)

**Comment by igor-ribeiro** [comment]
#284

**Comment by a-ignatov-parc** [comment]
I think this isn't an issue anymore after `React.Fragment` was introduced in [`react@16.2.0`](https://github.com/facebook/react/releases/tag/v16.2.0).

**Comment by giuseppeg** [comment]
what @a-ignatov-parc said
