### ISSUE TITLE
External files in with-styled-jsx-scss

### ISSUE THREAD

**Issue by ilionic** [zeit/styled-jsx#341]
Based on https://github.com/zeit/next.js/tree/master/examples/with-styled-jsx-scss
`styled-jsx-plugin-sass` plugin works fine if sass is inlined, but is it possible to load sass from a separate file?
Tried with webpack `raw-loader` to load file and inject but doesn't work.
```
import Styles from './style.scss';
...
      <style global jsx>
        {Styles}
      </style>
```

Previously in styled-jsx 1 we used `stylus-loader` and `raw-loader` in webpack to get compiled css and inject to styled-jsx ( similar example as above ) but doesn't work in styled jsx 2. 
Based on https://github.com/zeit/styled-jsx#keeping-css-in-separate-files 
Tried
```
export default css`${styles}`;
```
but no luck, if only would be possible to pass css string from variable.

**Comment by giuseppeg** [comment]
See https://github.com/zeit/styled-jsx/issues/322#issuecomment-338361918
