### ISSUE TITLE
[Question] Is it possible to include files when using external styled-jsx files?

### ISSUE THREAD

**Issue by aviramga** [zeit/styled-jsx#342]
Hi there,

I'm using styled-jsx with NextJs and separating my styled-jsx files from the rest of the code.
I would like to create a global file that will include all the possible colors in the app in variables.

I read the docs that says that constants are only available with inline styled-jsx but I was wondering if anyone came up with a workaround.

FYI Im using the  styled-jsx-plugin-sass plugin

Thanks!!

**Comment by giuseppeg** [comment]
Constants can be used in external files too, dynamic css (for example based on `props`) only in inline style tags.

This for example should work:

```js
import css from 'styled-jsx/css'
import colors from './constants'

export default css`
div { color: ${colors.primary} }
`
```
