### ISSUE TITLE
Problem with constants

### ISSUE THREAD

**Issue by Huvik** [zeit/styled-jsx#343]
Hey i discovered that `border-bottom: 1px solid ${colors.pink};` don't work. If i place normal color or hex code everything is works fine. I am using next 4.1.4 and styled-jsx 2.1.2.

**Comment by giuseppeg** [comment]
can you provide a more comprehensive example so that I can reproduce?

**Comment by Huvik** [comment]
Okey, i think its problem of `styled-jsx-plugin-sass`, because i was trying it now without plugin and it worked and with plugin it don't work. So maybe i should move issue here? I can share repo with issue.

**Comment by giuseppeg** [comment]
sure, please provide more info to reproduce the issue. Maybe make a sample repository.
