### ISSUE TITLE
Cannot get webpack to transpile the style element

### ISSUE THREAD

**Issue by alexyans** [zeit/styled-jsx#344]
I'm currently using the example from the docs.
```html
// component.styles.js
[...]
<div>
        <p>only this paragraph will get the style :)</p>
     
        <style jsx="true">{`
          p {
            color: red;
          }
        `}</style>
</div>
[...]
```

I changed `babel-loader`'s options in the webpack config as such:
```js
          // Process JS with Babel.
          {
            test: /\.(js|jsx|mjs)$/,
            include: paths.appSrc,
            use: {
              loader: require.resolve('babel-loader'),
              options: {
                babelrc: false,
                plugins: [require.resolve('styled-jsx/babel')],
              },
            },
          },
```
and my `package.json`looks like this
```json
    "styled-jsx": "^2.1.3",
```
The style element is simply dumped in the document, no processing takes place. The end result is that it is always globally scoped.

**Comment by giuseppeg** [comment]
@alexyans can you put together a sample (and minimal) repo?

**Comment by alexyans** [comment]
@giuseppeg I did and it turns out it was never a problem with the plugin, it was `create-react-app` that was messing with the config. I switched to my own webpack setup. Thanks for engaging
