### ISSUE TITLE
stlyled-jsx/css is not compatible with eslint-plugin-import

### ISSUE THREAD

**Issue by MrOrz** [zeit/styled-jsx#347]
Since stlyled-jsx/css do not actually exist, this confuses eslint-import, which checks if imports exist.

eslint-config-import would give errors like this:
```
Unable to resolve path to module 'styled-jsx/css'  import/no-unresolved
```

and this failed to pass our CI: https://travis-ci.org/cofacts/rumors-site/builds/300921835

Besides CI, I believe this would also confuse IDEs that checks for imports as well.

How about adding a stub file css.js (with a stub `css` function inside) so that it can be resolved correctly?

**Comment by ser111** [comment]
I keep ESLint quiet with `settings`:

```
// .eslintrc

{
  "parser": "babel-eslint",
  "extends": "airbnb",
  "env": {
    "node": true,
  },
  "settings": {
    "import/core-modules": ["styled-jsx", "styled-jsx/css"],
  },
  // ...
}
```

**Comment by MrOrz** [comment]
Cool I didn't know about `import/core-modules`. Thanks a million!
