### ISSUE TITLE
How do the three options for dynamic styles compare in performance?

### ISSUE THREAD

**Issue by callumlocke** [zeit/styled-jsx#351]
[From readme](https://github.com/zeit/styled-jsx#dynamic-styles):

> ### Dynamic styles
>
> To make a component's visual representation customizable from the outside world there are three options.

The readme explains these options:

- Via interpolated dynamic props
- Via `className` toggling
- Via inline `style`

How do they compare in performance?

**Comment by giuseppeg** [comment]
Ordered by "most performant":

1. className toggling
2. inline styles
3. interpolated dynamic props

If you are doing animations via JS you may want to use inline styles (although dynamic props should be fast enough anyway).

Hope this helps.

**Comment by callumlocke** [comment]
Thanks. It makes sense that interpolated dynamic props are the slowest. I guess I'll experiment.

Interesting you say class-toggling is faster than inline styles. I always thought the opposite. I guess maybe class-toggling is the quickest DOM operation, since it's one single change, but I think the subsequent work the browser engine does (painting or whatever) might be faster with inline styles, since it doesn't have to lookup the element against a list of CSS selectors.

**Comment by giuseppeg** [comment]
I just guessed to be honest, what you said might be true but I think that React adds the overhead of diffing to figure out what changed (in this case the `style` prop). While styles in styled-jsx are shared across instances (deduped) toggling one class might be faster than having to diff/patch (react) parse the new css and apply it (browser) for each instance. This is all cheap guessing and not backed by actual benchmarks so who knows. Let me know if you get to bench this :)
