### ISSUE TITLE
Injecting additional class unnecessarily

### ISSUE THREAD

**Issue by jeremenichelli** [zeit/styled-jsx#352]
I'm new to `styled-jsx` so I hope this is not spammy. 

I just created a _Hello World example_ using the package and I could notice that the same class is injected twice on each element. I will put here the exact component and congif to make sure I'm not doing anything wrong.

**hello world component**
```jsx
class HelloWorld extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <div>
        <h1 className="hello">Hello World!</h1>
        <style jsx>{`
          .hello {
            font-family: sans-serif;
            text-transform: uppercase;
          }
        `}</style>
      </div>
    )
  }
}
```

**generated markup**
```html
<div class="jsx-1694309378 jsx-1694309378">
  <h1 class="jsx-1694309378 jsx-1694309378 hello">
    Hello World!
  </h1>
</div>
```

**styles generated**
```html
<style type="text/css" data-styled-jsx="">
.hello.jsx-1694309378{font-family:sans-serif;text-transform:uppercase;}
/*# sourceMappingURL=... */</style>
```

**babel config**
```js
plugins: [
  [
    'styled-jsx/babel',
    {
      vendorPrefixes: true,
      sourceMaps: process.env.NODE_ENV === 'development'
    }
  ]
]
```

As you can see on the generated markup, **class names are injected twice**, and I was wondering if there was a reason I'm missing or if it could be a bug. _Note: I'm not server side rendering and it happens on both production and development._

**Comment by jeremenichelli** [comment]
Super weird, but it just stopped happening.

I will close the issue and comeback later with more findings if I see this again.

Sorry for the noise 📣

**Comment by davidvenin** [comment]
I've got the exact same problem. Any clue ?
