### ISSUE TITLE
Minification issue with at-keywords that are not rulesets

### ISSUE THREAD

**Issue by bathos** [zeit/styled-jsx#353]
Given input like:

    @import url("foo");
    html {
      color: red;
    } 

Output will look like this:

    @import url("foo")html{color:red;}

At the lexical level, the output is valid. But at the syntactic level, the production for an at-rule does not terminate until either a complete block is seen or a semicolon (outside a block) is seen. Therefore, `@import url("foo")html{color:red;}` is actually interpreted as a single (unrecognized) at-rule, terminating at `}`.

https://www.w3.org/TR/css-syntax-3/#consume-an-at-rule

As a result, both Chrome and Firefox (didn’t test others) correctly consider the resulting stylesheet to have no rules. Adding the semicolon fixes it. This is true regardless of whether the specifier portion is provided as an actual URL token (bare string in parens), functiontoken+string+paren, or string.

**Comment by giuseppeg** [comment]
@thysultan can this be a bug in the rule-sheet plugin?

**Comment by thysultan** [comment]
Yes it is... published a patch for it.

**Comment by giuseppeg** [comment]
Fixed #358
