### ISSUE TITLE
Stylesheet: `insertRule` error only on <style jsx global> with Jest

### ISSUE THREAD

**Issue by jthegedus** [zeit/styled-jsx#354]
## Summary
I'm using Next.js, styled-jsx with external css compiled through postcss and Jest with snapshot
testing. Scoped styles works as expected, global styles through styled-jsx do not. As far as Jest is concerned these should result in the same output, no?

## Explanation
Snapshot testing works as expected with the use of [`indentity-obj-proxy`](https://github.com/keyanzhang/identity-obj-proxy) and [`babel-jest`](https://github.com/facebook/jest/tree/master/packages/babel-jest) when using scoped `styled-jsx` Eg:

```js
// components/Footer.js
<style jsx>{footerStyles}</style>;
```
creates a correct snapshot.

However when adding `global` to the style element

```js
// from pages/index.js
<style jsx global>
  {stylesheet}
</style>;
```

`styled-jsx` throws the following error:

```shell
    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5533
      The above error occurred in the <JSXStyle> component:
          in JSXStyle
          in div (at index.js:11)
          in Unknown (at index.test.js:6)

      Consider adding an error boundary to your tree to customize error handling behaviour.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

  ● renders correctly › encountered a declaration exception

    StyleSheet: `insertRule` accepts only strings.

      at invariant (node_modules/styled-jsx/dist/lib/stylesheet.js:274:11)
      at Array.map (native)
      at Suite.<anonymous> (pages/index.test.js:6:42)
      at Object.<anonymous> (pages/index.test.js:5:1)
      at next (native)
      at next (native)
```

Removing the `global` from the style tag

```js
<style jsx>{stylesheet}</style>;
```

results with correctly running tests and snapshots, but the styles are thus scoped.

I can try and use global styles through the `<link>` in the head with Next.js `import Head from "next/head";` and scoped with `styled-jsx`, but it would be good to use a single method to include styles with JSX throughout my app, ideally just `<style jsx>` to include styles (and not mixing `<link>`s everywhere).

## Example Repo
https://github.com/jthegedus/nextjs-styled-jsx-external-css-with-jest

## Related
https://github.com/zeit/styled-jsx/issues/298

## Versions:
```json
"next": "^4.1.4",
"styled-jsx": "^2.2.0"
```

**Comment by giuseppeg** [comment]
Sorry man but there should be something wrong with your set up.
Try to add a `console.log` in `node_modules/styled-jsx/dist/lib/stylesheet.js:274`

**Comment by jthegedus** [comment]
I seem to be getting an empty object for the `rule` in the `key: 'insertRule'` case. Any ideas?

```shell
•100% ➜ yarn test
yarn run v1.3.2
$ NODE_ENV=test jest
 FAIL  pages/index.test.js
  ● Console

    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:125
      rule: {}
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:126
      index: undefined
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: false
    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5533
      The above error occurred in the <JSXStyle> component:
          in JSXStyle
          in div (at index.js:11)
          in Unknown (at index.test.js:6)

      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

  ● renders correctly

    StyleSheet: `insertRule` accepts only strings.

      at invariant (node_modules/styled-jsx/dist/lib/stylesheet.js:277:11)
      at Array.map (native)
      at Object.<anonymous> (pages/index.test.js:6:42)

 PASS  components/Footer.test.js
  ● Console

    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:125
      rule: __scoped
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:126
      index: undefined
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true

 PASS  components/Navbar.test.js
  ● Console

    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:125
      rule: __scoped
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:126
      index: undefined
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true
    console.log node_modules/styled-jsx/dist/lib/stylesheet.js:275
      invariant condition: true


Test Suites: 1 failed, 2 passed, 3 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   2 passed, 2 total
Time:        0.775s, estimated 1s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by andy-viv** [comment]
@jthegedus I am having the same issue. Did you ever figure out the solution?

**Comment by giuseppeg** [comment]
if you guys put together a minimal test case I can take a look

**Comment by jthegedus** [comment]
The minimal repo I linked is now out of date with next.js so I'm not sure it's relevant anymore.

https://github.com/jthegedus/nextjs-styled-jsx-external-css-with-jest/tree/master

---

I had a quick go at updating it to use Next.js 5.canary & next-sass plugin

https://github.com/jthegedus/nextjs-styled-jsx-external-css-with-jest/tree/nextjs5

but I started getting the insertRule error on the dev server (which I didn't have in the original example). This may be because I removed the styled-jsx babel plugin https://github.com/jthegedus/nextjs-styled-jsx-external-css-with-jest/commit/8163293fc4e45220c43c763cd82294639928402a

I haven't the time at the moment to tackle these config issues, if anyone has solutions to this then please provide an alt minimal example or PR changes to mine.

**Comment by andy-viv** [comment]
@jthegedus I cloned your repo and see what you mean about running into the error even on the dev server. After some fiddling with that, I tried to start a fresh project as a minimal test case but am having difficulties (I'm also completely new to react/next/babel/jest which doesn't help—I am seeing the error on a larger project I just joined).

I'll keep trying, but while I'm at it: What does this error even mean? That `myStyles` in `<style jsx global>{myStyles}</style>` has to be a string? If this is the case, perhaps the problem is that `styled-jsx-plugin-sass` is not being used correctly (or at all) in the jest environment?

**Comment by jthegedus** [comment]
@andy-viv It depends on which branch you try. I expect that the v5 branch is throwing the error because I am indeed missing the `styled-jsx-plugin-sass` stuff, however the master branch with the Nextv4 example also throws this error in Jest

**Comment by andy-viv** [comment]
While debugging I found that `props` was `{ css :undefined, styleId: undefined }` at [this point](https://github.com/zeit/styled-jsx/blob/8a7292da531d533a845aef53f1db6a08f05aae71/src/stylesheet-registry.js#L52) in the code. Perhaps this would help @giuseppeg understand what's happening... still trying to work something out.

**Comment by jthegedus** [comment]
@andy-viv I haven't had much time to test this out further, so thanks for taking a look. At this stage I'm thinking of waiting to use `next`5.1 with `styled-jsx` v3 (when it launches) and go from there. If you do find a solution for `next`v5 with `styled-jsx` v2 and the `sass` plugin, please do continue to share you results here.

**Comment by andy-viv** [comment]
@jthegedus @giuseppeg Some updates:

In our `package.json`, our jest config dictates that imported `.scss` files should instead import a [`Proxy` object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) from the package [`identity-obj-property`](https://github.com/keyanzhang/identity-obj-proxy):

```json
    "moduleNameMapper": {
      "\\.(css|scss)$": "identity-obj-property"
    },
```

For `<style jsx>{styles}</style>` tags (ones without the `global` attribute), this appears to work fine. However, for whatever reason in the `<style jsx global>{styles}</style>` case, the proxy object gets passed all the way down as the first argument to [the insertRule method here](https://github.com/zeit/styled-jsx/blob/next/src/lib/stylesheet.js#L104) (as the `rule` parameter).

Still no lead on a legitimate fix, but our temporary fix is [this commit](https://github.com/andy-viv/styled-jsx/commit/d677496d6cb5d37a0a890c90a2ca50337c56f574).

**Comment by giuseppeg** [comment]
@andy-viv do you need to test css at all? Can't you just remove styled-jsx from your `.babelrc` for tests?

That said, do you get the error when you use a styled-jsx plugin (like the sass one) or even without any plugins? Are you using `React.Fragment` by any chance?

**Comment by andy-viv** [comment]
@giuseppeg removing it from my `.babelrc` for the `test` environment does work for these unit tests, thanks for the tip. We'll obviously want css for our end-to-end tests so I'll have to make sure that `BABEL_ENV` is not `test` when building for the e2e. 

>do you get the error when you use a styled-jsx plugin (like the sass one) or even without any plugins?

It also happens without any plugins. I tested this by removing the `styled-jsx-plugin-sass` from my `.babelrc`, removing the `node_modules/styled-jsx-plugin-sass` folder, and replacing the imported `.scss` with an equivalent `.css` file. The same `insertRule` failure occurred.

>Are you using React.Fragment by any chance?

We are using it in other parts of our app, but not in the component under test in which the error occurs.

**Comment by andy-viv** [comment]
@giuseppeg I think the issue may have to do with [this ternary in babel.js](https://github.com/zeit/styled-jsx/blob/next/src/babel.js#L223-L224):

```js
            makeStyledJsxTag(
                id,
                isGlobal
                  ? css // <----- I think `css` is the Proxy object
                  : t.memberExpression(
                      t.identifier(css.name),
                      t.identifier('__scoped')
                    )
              )
```

However, for some reason (that I hope you know of), no amount of modification to `node_modules/styled-jsx/dist/babel.js` actually changes the behavior of my test (even deleting the file outright!!).

**Comment by giuseppeg** [comment]
@jthegedus master seems to be working, in the `nextjs5` branch you are not using styled-jsx-css-loader anymore

**Comment by giuseppeg** [comment]
@andy-viv please put together a minimal test case that I can clone and play with :)
