### ISSUE TITLE
Define and use styled-jsx/css template string within JS file without importing

### ISSUE THREAD

**Issue by jthegedus** [zeit/styled-jsx#355]
I wish to be able to separate my styles from JSX (but maintain co-location), as many styles makes the format of the JSX becomes difficult to read. Here's what I wish to do:

```js
// index.js
import css from "styled-jsx/css";

const styles = css`
  .apples {
    color: red;
  }
`;

export default () => (
  <div>
    <style jsx>{styles}</style>
    <p className="apples">Red apples!</p>
  </div>
);

```
Currently it throws this error:

```shell
The Identifier `styles` is either `undefined` or it is not an external StyleSheet reference i.e. it doesn't come from an `import` or `require` statement
```

Is this something that could be supported in the future?

This works, but obviously not ideal, I don't want to have to export each style.

```js
// index.js
import css from "styled-jsx/css";

// must export
export const styles = css`
  .apples {
    color: red;
  }
`;

// import but must renamed
import { styles as s } from "./index";

export default () => (
  <div>
    <style jsx>{s}</style>
    <p className="apples">Red apples!</p>
  </div>
);
```

I wanted to clarify if this was something that was even possible or, likely to be supported or accepted before tinkering with the codebase.

**Comment by giuseppeg** [comment]
Since v2.2.0 this is possible https://github.com/zeit/styled-jsx/releases/tag/v2.2.0

**Comment by jthegedus** [comment]
@giuseppeg Can you have a look at this minimal example and tell me if you can see where I'm going wrong? https://github.com/jthegedus/styled-jsx-test

I'm using styled-jsx v2.2.0 as far as I can tell. Still getting that same error output.

```json
{
  "name": "styled-jsx-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "next": "^4.1.4",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "styled-jsx": "^2.2.0"
  },
  "scripts": {
    "dev": "next"
  }
}
```
