### ISSUE TITLE
Custom components support

### ISSUE THREAD

**Issue by arsen** [zeit/styled-jsx#360]
Hello,
I am wondering why styled-jsx is not supporting custom components.
Let's say I have a custom Button component.

```
const Button = ({ children, className }) => {
  return <button className={className}>{children}</button>;
};
```

I want to style it the same way as a regular html5 element.
```
<div>
  <Button className="btn">Hello
    <style jsx>{`
      .btn {
        color: red;
      }
    `}</style>
  </Button>
</div>
```
or like this:
```
<div>
  <Button>Hello
    <style jsx>{`
        color: red;
    `}</style>
  </Button>
</div>
```

I know that it is saying that if you want to style custom components you have to use :global()
But in that case, there is no support for scoping.

It will be super amazing to support custom components.

**Comment by giuseppeg** [comment]
Duplicate / relates to https://github.com/zeit/styled-jsx/issues/147#issuecomment-337053924
