### ISSUE TITLE
Module build failed: TypeError: unknown: Duplicate declaration "_JSXStyle"

### ISSUE THREAD

**Issue by Leland-Kwong** [zeit/styled-jsx#361]
Looks like we no longer need to add the plugin to the babel configuration?

I noticed when this is added to the babel configuration
```
{
  "plugins": [
    "styled-jsx/babel"
  ]
}
```
we get the following error: 
<img width="530" alt="screen shot 2017-12-05 at 3 23 38 pm" src="https://user-images.githubusercontent.com/2934856/33636367-a91759a2-d9d0-11e7-9e52-37bc87750525.png">.

Perhaps we should update the docs to reflect this change?
[Example repo](https://github.com/Leland-Kwong/next-styled-jsx-issue) demonstrating the issue.

**Comment by giuseppeg** [comment]
Never been the case, Next.js comes with `styled-jsx` already

**Comment by kajic** [comment]
I ran into this issue when I erroneously installed `styled-jsx` and added it to my .babelrc plugins. 
I did that as I was following `styled-jsx`'s documentation on how to keep styles in a separate file. Where does one import the `styled-jsx` `css` tag from with Next.js?

**Comment by DearVikki** [comment]
@kajic Next.js has injected <style jsx></style> by default so we can use this tag without any import.

**Comment by Vitaminaq** [comment]
There is no need to use Babel and install style-jsx in next
