### ISSUE TITLE
Possible to do cascade normally?

### ISSUE THREAD

**Issue by corysimmons** [zeit/styled-jsx#368]
```
<style jsx cascade>{`
  * {
    &:not(:last-child) {
      margin-bottom: 40px;
    }
  }
`}</style>
```

..would be really handy as an alternative to the lobotomized owl technique.

**Comment by corysimmons** [comment]
This might also be converted to a feature request to "Control how many levels deep you can nest" via some syntax like `<style jsx levels="3">`

**Comment by giuseppeg** [comment]
You can get nesting with plugins/postcss. We are not planning to support it.

**Comment by corysimmons** [comment]
I think you're misunderstanding what I'm requesting, and I don't think postcss can't help with this.

styled-jsx has 2 modes: scoped and global.

global affects EVERYTHING

scoped only affects a specific component and doesn't leak into sub-components

I am requesting there be an attribute to purposefully _enable_ leaking.

I think the syntax should be flexible enough to enable leaking indefinitely `<style jsx leak="*">`, or by a certain number of levels `<style jsx leak="3">`.

Maybe PostCSS _can_ help with this(?) but it seems like styled-jsx is the one controlling leak.

There are some cases where leaking (particularly for a few levels) would be helpful.

Not a super important issue, but maybe others will stumble upon it with a similar need they can provide better examples for.

**Comment by giuseppeg** [comment]
> I think the syntax should be flexible enough to enable leaking... by a certain number of levels <style jsx leak="3">

This is impossible to implement because we cannot say just stop after 3 nested components since the current component `n` and the nested at `n+3` level don't have information about each other. In fact a component and its direct descendants (children) don't know anything about each other.

> <style jsx leak="*">

This can be implemented with `:global()`

**Comment by decimoseptimo** [comment]
@giuseppeg is this still "imposible"? react is all about composition.
From a design perspective, a `cascade` option would tell a component do not create a unique selector, but inherit it from the parent component.

```js

  //FULL ISOLATION
  //you can do: form {}, input {}
  <Form>                       //.jsx-0000000001
    <Input />                  //.jsx-0000000002
    <Button />                 //.jsx-0000000003
    <ButtonPrimary />          //.jsx-0000000004
  </Form>

  //CONTROLLED ISOLATION
  //you can do: form input {}
  <Form>                       //.jsx-0000000001
    <Input cascade />          //.jsx-0000000001
    <Button />         //.jsx-0000000002
    <ButtonPrimary cascade />  //.jsx-0000000001
  </Form>
```

**Comment by decimoseptimo** [comment]
This is along the lines of what `css.resolve` does, it generates an id (.jsx-xxxxxxx) in the parent, that you pass to the children. But that only gets you control of the children's topmost html tag. Parent and children do not become synced with the same id. That's not true composition.

**Comment by giuseppeg** [comment]
styled-jsx's model is similar to ShadowDOM and has the same limitations/constraints. styled-jsx makes things a bit easier with css.resolve and :global - those are the only tools you can leverage to opt is some sort of "cascade"
