### ISSUE TITLE
Rendering `property: value` rules within `<style jsx>`

### ISSUE THREAD

**Issue by corysimmons** [zeit/styled-jsx#371]
Seems like styled-jsx can only render a prop if it's just the value.

e.g.

```
// Site.js
<Wrap stylez="background: red;">
  <h1>hi</h1>
</Wrap>

// Wrap.js
<div>
  {children}
  <style jsx>{`
    div {
      ${stylez} // I would expect this to render background: red, but it doesn't.
    }
  `}</style>
</div>
```

My use case is wanting to make a wrapping element I can apply various styles to [within media queries as well].

**Comment by corysimmons** [comment]
Or to put it another way...

```js
const yo = 'background'
return (
  <div>
    <style jsx>{`
      ${yo}: red; // doesn't work
    `}</style>
  </div>
)
```

**Comment by corysimmons** [comment]
Point remains that you can't variable css properties.

**Comment by giuseppeg** [comment]
@corysimmons can you put together a testcase that I can clone and try out?

**Comment by corysimmons** [comment]
Sorry @giuseppeg I would but I'm swamped right now and tbh will probably forget to do it later. I can go ahead and close this and if I bump into it again I'll reopen with a very clear test case.
