### ISSUE TITLE
Theme support?

### ISSUE THREAD

**Issue by nmackey** [zeit/styled-jsx#376]
What is the preferred way to do theming with styled-jsx?  Some examples in the readme reference a theme and say that theming is supported, but there aren't any specific examples of how this should be done.

Most other css-in-js libraries use a ThemeProvider, would that be where styled-jsx is going?

**Comment by giuseppeg** [comment]
you can use this https://github.com/cssinjs/theming

**Comment by skitterm** [comment]
Along these same lines... the README mentions `Dynamic styles and theme support` but I don't see any examples or documentation about how to make themes work in styled-jsx out of the box. Can some documentation be added for this on the README?
