### ISSUE TITLE
[Question] CSS classes defined in component are not prefixed and global styles leak into it

### ISSUE THREAD

**Issue by arielschiavoni** [zeit/styled-jsx#377]
Hi there, first of all thanks for this great lib!

I am slowly introducing `styled-jsx` in a project that has Bootstrap.
The problem I have is that Bootstrap introduces a lot of global css classes like `label` and when
I try to use a react `className` with the same name in my component the `label` Bootstrap styles cascade into my component. 

I was expecting that `styled-jsx` will prefix all the classes defined in my component so I don't have to worry about the rest of the app and I can use whatever name I want and style the component in isolation.

![image](https://user-images.githubusercontent.com/1364564/34612052-5d226b3e-f228-11e7-9c92-82cd23ce0567.png)

Is this a design decision?

Is there a way to configure `styled-jsx` so it can bound class name only to the scope of the component?

I created this small example to to easily show what I am talking about :-)

https://codesandbox.io/s/m591vk86ry

Thanks!

**Comment by giuseppeg** [comment]
styled-jsx doesn't rewrite classnames in JSX but adds a prefixed one and then rewrites the selectors in CSS to bump (and scope) its specificity. Eg.

```css
.foo {}
/* becomes */
.jsx-123.foo {}
```
So yep other global css selectors will affect your styles.
