### ISSUE TITLE
Option to hashing class name on generated css

### ISSUE THREAD

**Issue by phongtattuan** [zeit/styled-jsx#378]
It's good if we can have an option to hashing class name on generated css, [same as `css-modules` does](https://github.com/zeit/next.js/blob/canary/examples/with-scoped-stylesheets-and-postcss/postcss.config.js)
It can help to output smaller generated css

```html
<div class="jsx-3116052526 hello">
  <span class="jsx-3116052526 text">Hello</span>
</div>
```
become
```html
<div class="abU1v Qr3Iv">
  <span class="abU1v a2Bnm">Hello</span>
</div>
```

Thanks so much.

**Comment by giuseppeg** [comment]
We only have control over the unique hashed classname `jsx-3116052526` the hash looks like that because of the hashing function... which I think is one of the fastest. Please take a look at the hashing function https://www.npmjs.com/package/string-hash I am open to consider another one if it is as fast.

**Comment by a-ignatov-parc** [comment]
I think using gzip/brotli will do a better job then choosing different hashing algorithm 🤔

**Comment by phongtattuan** [comment]
@giuseppeg I am discussing ability to hashing class name (such as hash `hello`, `text` classes above)

**Comment by joelcoluccinbc** [comment]
Hi, I second @phongtattuan . The jsx-asdfasdf is fine. We'd like the ability to hash `.hello`.  The unique`jsx-3116052526` is fine.

Reasoning, well named classes can be more verbose:
```
.my-longer-class-name { .. }
```

For large sites these longer class names inflate the size of CSS and can interfere with performance and AMP limitations.
Other webpack tools allows for the shorting of `my-longer-class-name` to something like a234a.

**Comment by phongtattuan** [comment]
@joelcoluccinbc which is the webpack tools to shorting the class name ?
