### ISSUE TITLE
Is there a way to control eslint quote config within <style jsx> blocks?

### ISSUE THREAD

**Issue by corysimmons** [zeit/styled-jsx#380]
Use case:

```jsx
<div data-foo="xyz">
  <style jsx>{`
    [data-foo="xyz"] { color: blue; }
  `}</style>
</div>
```
is being converted to
```jsx
<div data-foo="xyz">
  <style jsx>{`
    [data-foo='xyz'] { color: blue; } // these quotes aren't symmetrical
  `}</style>
</div>
```
even with `"react/jsx-quotes": "prefer-double"`

**Comment by giuseppeg** [comment]
Is eslint linting the content of the string? btw in the example you didn't include curly brackets 

```jsx
<style jsx>{``}</style>
```

**Comment by corysimmons** [comment]
Sorry, updated the example with curlies.

Apparently it is linting the content of the string (which I wouldn't expect either).

https://gfycat.com/VerifiableOddApe

I'm using Atom Prettier, but wasn't using Pretttier when I originally ran into this problem, so it's not an issue with Prettier. It has to be some ESLint weirdness.

It doesn't seem to do it in any other JSX expression or context, or even `<style>` tags, just within `<style jsx>` tags..

It's not a huge deal, just strange.

**Comment by vasco3** [comment]
It used to work fine but now I lost the syntax.. (using Atom latest).
