### ISSUE TITLE
Allow for generating prefixed global styles

### ISSUE THREAD

**Issue by Machiaweliczny** [zeit/styled-jsx#382]
In your example to tweak 3rd party (markdown) styles in such example:
```
const Test = (props) => (
    <Layout>
        <h1>{props.url.query.title}</h1>
        <div className="markdown">
            <Markdown source={`
This is our blog post.
Yes. We can have a [link](/link).
And we can have a title as well.

### This is a title

And here's the content.
     `} />
        </div>
        <style jsx global>{`
     .markdown {
       font-family: 'Arial';
     }

     .markdown a {
       text-decoration: none;
       color: green;
     }

     .markdown a:hover {
       opacity: 0.6;
     }

     .markdown h3 {
       margin: 0;
       padding: 0;
       text-transform: uppercase;
     }
  `}</style>
    </Layout>
)
```
I have to add `<style jsx global>`  which simply generates global style tag - so without carefully changing class name from "markdown" to something else in `Test2` it will break other part of application(Test2) which is bad idea IMO.

```
const Test2 = (props) => (
    <Layout>
        <h1>{props.url.query.title}</h1>
        <div className="markdown">
            <Markdown source={`
This is our blog post.
Yes. We can have a [link](/link).
And we can have a title as well.

### This is a title

And here's the content.
     `} />
        </div>
    </Layout>
)
```
^ This will also get styled like first example unless I change "markdown" to "markdown2" manually. See that I didin't attached `<style>` here.

Why not allow for:
```
        <style jsx global-prefixed>{`
     .markdown {
       font-family: 'Arial';
     }

     .markdown a {
       text-decoration: none;
       color: green;
     }

     .markdown a:hover {
       opacity: 0.6;
     }

     .markdown h3 {
       margin: 0;
       padding: 0;
       text-transform: uppercase;
     }
  `}</style>
```
Which would produce such global css:
```
    hashedPrefix  .markdown {
       font-family: 'Arial';
     }

    hashedPrefix   .markdown a {
       text-decoration: none;
       color: green;
     }

    hashedPrefix   .markdown a:hover {
       opacity: 0.6;
     }

    hashedPrefix   .markdown h3 {
       margin: 0;
       padding: 0;
       text-transform: uppercase;
     }
```
So styles are applied globaly but only to part of application I'm changing right now. Why burden developers with coming up with unique prefixes(class names) and when you can do it automatically.

**Comment by giuseppeg** [comment]
it is a bit annoying but you can already do this with `:global()`e.g.:

```css
.markdown :global(a) { ... }
```

**Comment by fchengpc** [comment]
hi @giuseppeg, can you prefix the same way with a given class? I was trying `  :global(.reactCard) {...}` to get the correct prefix.
![Screen Shot 2019-05-30 at 4 35 11 PM](https://user-images.githubusercontent.com/6640631/58662896-35a53d80-82f9-11e9-9edd-045d376decd3.png)

**Comment by giuseppeg** [comment]
@fchengpc if you want to style 3rd parties components you can use this technique https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent or this https://github.com/zeit/styled-jsx#the-resolve-tag

**Comment by fchengpc** [comment]
🤔 not working for me.  what am I doing wrong here? 

![Screen Shot 2019-06-05 at 6 01 36 PM](https://user-images.githubusercontent.com/6640631/58993624-0b9dc080-87bc-11e9-9173-3b09c19de086.png)
