### ISSUE TITLE
css template tag function in function call fails to transpile

### ISSUE THREAD

**Issue by jadengore** [zeit/styled-jsx#383]
Say the `resolveScopedStyles` from [this example](https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent) is used like so in a file:
```js
// styles.js
export default resolveScopedStyles(
    css`
        .borderButton {
            color: red;
        }
    `,
);
```
This fails with:
```
Property body[1] of BlockStatement expected node to be of a type ["Statement"] but instead got "CallExpression"
```

However, if I modify the above code to look like this:
```js
// styles.js
const styles = css`
    .borderButton {
        color: red;
    }
`;
export default resolveScopedStyles(styles);
```
it is transformed properly.

Is the `css` template tag function transformer not accounted for in function calls properly?

**Comment by giuseppeg** [comment]
the error is due to how we rewrite exports I think. Anyway I don't think that 

```js
// styles.js
const styles = css`
    .borderButton {
        color: red;
    }
`;
export default resolveScopedStyles(styles);
```

Give you the result you want since `styles` is not a react element. Can't you just do the following?

export default resolveScopedStyles(
 <scope><style jsx>{`.borderButton { color: red }`}</style></scope>
)

**Comment by giuseppeg** [comment]
anyway I am planning to add a new thing called `css.resolve` that would work like you said:

```js
const scoped = css.resolve`
   .borderButton {
        color: red;
    }
`

const { className, styles } = scoped
```

**Comment by giuseppeg** [comment]
cc @a-ignatov-parc what do you think?

**Comment by giuseppeg** [comment]
This would work only for static styles.  Unless we return a function that accepts `props`:

const getStyles = css.resolve`
  .borderButton {
    color: red;
  }
`

`getStyles(props)`

**Comment by a-ignatov-parc** [comment]
Sounds good, but if I remember correctly `css` can't handle dynamic values.

Maybe we can create something more helpful? 🤔

```jsx
const static = css.resolve`
  .border { color: red } 
`;

const dynamic = css.resolve(({ color }) => `
  .border { color: ${color} } 
`);

console.log(static); // { className, styles }
console.log(dynamic({ color: 'red' })) // { className, styles }
```

**Comment by a-ignatov-parc** [comment]
Also, it could be cool if returned value is react element than we can drop to rendering tree.

```jsx
const styles = css.resolve`
  .border { color: red } 
`;

function MyComponent() {
  return (
    <div className={`${styles.className} border`}>
      {styles}
    </div>
  );
}
```

**Comment by giuseppeg** [comment]
> it would be cool if returned value will be react element than we can drop to rendering tree

Although I like your API, I am not sure that it is a good idea to add a property to a React element.

For dynamic styles we can make use of https://github.com/zeit/styled-jsx/blob/master/src/style.js#L7-L14 which returns an array of classnames.

Anyway looking at your API (which I like) I started to have the feeling that we are basically making a new CSS in JS library 😅

**Comment by a-ignatov-parc** [comment]
> I am not sure that it is a good idea to add a property to a React element

What problems do you see in this approach?

> we are basically making a new CSS in JS library

`styled-jsx` is already css-in-js-library, no need to worry about it! We're just making things better and easier ;)

**Comment by giuseppeg** [comment]
I think we can use the simple version of it for dynamic styles too, the only constraint is that when there are dynamic values it can only used inside of the `render` method of a component.

```jsx
class Foo extends React.Component {
   render() {
      const { styles, className } = css.resolve`
         .border { color: ${this.props.color} } 
      `
   }
}
```

**Comment by a-ignatov-parc** [comment]
Sounds good 👍

**Comment by giuseppeg** [comment]
going to fix this in https://github.com/zeit/styled-jsx/issues/345
