### ISSUE TITLE
styled-jsx doesn't work with storybook

### ISSUE THREAD

**Issue by shibukawa** [zeit/styled-jsx#384]
I am using storybook with next.js. I can't resolve one issue.

* The following code doesn't work (got "ReferenceError: exports is not defined").
* I can use the component outside of storybook (regular next.js environment).
* If I remove ``export`` keyword from source code, it works.
* If I remove ``<style jsx>`` tag, it works too.

I got issue only when I use ``export`` keyword and ``<style jsx>`` tag at the same time on storybook. How can I work around the issue?

Thank you.

.babelrc
```json:
{
  "presets": [
    "next/babel",
    "env"
  ]
}
```

sample.stories.js
```js
import React, { Component } from "react";

import { storiesOf } from "@storybook/react";

export class Sample extends Component {
    render() {
        return <div className="test">test
            <style jsx>{`
                .test {
                    color: red;
                }
            `}</style>
        </div>;
    }
}

storiesOf("next.js", module)
    .add("with <style jsx>", () => {
        return <Sample />;
    });
```

<img width="674" alt="2018-01-15 19 51 55" src="https://user-images.githubusercontent.com/564612/34938997-9b920476-fa2d-11e7-95ea-a9fd0d441ad1.png">

**Comment by shibukawa** [comment]
I can work around by myself. I added ``{ modules: false }`` to ``.storybook/.babelrc`` then it works. Could you add document about it?

```
{
  "presets": [
    "next/babel",
    ["env",  { modules: false }]
  ]
}
```

**Comment by giuseppeg** [comment]
@shibukawa the problem is that Next doesn't transpile any dependency I think. So exports/imports are not transpiled
