### ISSUE TITLE
<style jsx> just works if inside same render function

### ISSUE THREAD

**Issue by euharrison** [zeit/styled-jsx#385]
I'm using next 4.1.4 and have a component with some render methods like `renderSection1()` and `renderSection2()`.

But I can't use a unique `<style jsx>` in main `render()` to share some className between `renderSection1()` and `renderSection2()` methods.

Here is the minimal code to reproduce it.

```jsx
import React from 'react';

class Container extends React.Component {
  renderContainer = () => (
    <div className="container">
      Container1
    </div>
  )

  render() {
    return (
      <div>
        {this.renderContainer()}
        <div className="container">
          Container2
        </div>
        <style jsx>{`
          .container {
            text-align: center;
          }
        `}
        </style>
      </div>
    );
  }
}

export default Container;

```
![screen shot 2018-01-15 at 1 25 57 pm](https://user-images.githubusercontent.com/557598/34949972-dd3bdf94-f9f8-11e7-841a-3c2e6489ba37.png)

Just if I duplicate the `<style jsx>` code, it will works as expected:
```jsximport React from 'react';

class Container extends React.Component {
  renderContainer = () => (
    <div className="container">
      Container1
      <style jsx>{`
        .container {
          text-align: center;
        }
      `}
      </style>
    </div>
  )

  render() {
    return (
      <div>
        {this.renderContainer()}
        <div className="container">
          Container2
        </div>
        <style jsx>{`
          .container {
            text-align: center;
          }
        `}
        </style>
      </div>
    );
  }
}

export default Container;
```
![screen shot 2018-01-15 at 1 35 17 pm](https://user-images.githubusercontent.com/557598/34950035-1202c558-f9f9-11e7-9d68-97ac21a1cbb5.png)

**Comment by a-ignatov-parc** [comment]
You can use `css` module to create reusable styles (but only for static styles)

```jsx
import css from 'styled-jsx/css'

const styles = css`
  .container {
    text-align: center;
  }
`;

class Container extends React.Component {
  renderContainer = () => (
    <div className="container">
      Container1
      <style jsx>{styles}</style>
    </div>
  )

  render() {
    return (
      <div>
        {this.renderContainer()}
        <div className="container">
          Container2
        </div>
        <style jsx>{styles}</style>
      </div>
    );
  }
}
```

**Comment by euharrison** [comment]
Thanks for fast reply @a-ignatov-parc.

This will help to reuse code, but we still need to duplicate `<style jsx>{styles}</style>`.

Do you know another method to write styles for the whole component, instead of write for each render method?

**Comment by a-ignatov-parc** [comment]
This is the best way to do what you want. 

Another option is to use [`resolveScopedStyles`](https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent) helper 🤔

```jsx
const scoped = resolveScopedStyles(
  <scope>
    <style jsx>{`
      .container {
        text-align: center;
      }
    `}
    </style>
  </scope>
)

class Container extends React.Component {
  renderContainer = () => (
    <div className={`container ${scoped.className}`}>
      Container1
    </div>
  )

  render() {
    return (
      <div>
        {this.renderContainer()}
        <div className={`container ${scoped.className}`}>
          Container2
        </div>
        {scoped.styles}
      </div>
    );
  }
}
```

**Comment by euharrison** [comment]
Thanks!

`resolveScopedStyles` is the best option for me.

**Comment by Vadorequest** [comment]
Where does `resolveScopedStyles` come from?

**Comment by euharrison** [comment]
@Vadorequest with the new Next 5 I suggest you to use the plugin next-sass that resolve this situation easier: https://github.com/zeit/next-plugins/tree/master/packages/next-sass

**Comment by Vadorequest** [comment]
Well, I have many variables from JS I need to use in my CSS, this doesn't seem to be a good fit for me. I'm using https://github.com/giuseppeg/styled-jsx-plugin-sass
