### ISSUE TITLE
Async safe SSR

### ISSUE THREAD

**Issue by a-ignatov-parc** [zeit/styled-jsx#389]
`styled-jsx` is awesome but it handles style generation during SSR in a very unsafe way. It uses side effects that can lead to style collision when user will try to render something async (say hello to `renderToStream` and `react@17` in future).

So I want to propose a better solution to this problem. 

Instead of using `flush` from `styled-jsx/server` and internal stylesheet singleton we need to be able to provide custom `styleSheetRegistry` to controlled virtual tree.

This can be done with react.js context.

```jsx
// server.js
import { StyleSheetRegistryProvider, StyleSheetRegistry } from 'styled-jsx/server';

const registry = new StyleSheetRegistry();

const app = ReactDOM.renderToString((
  <StyleSheetRegistryProvider registry={registry}>
    <App />
  </StyleSheetRegistryProvider>
));

const styles = registry.toHTML(); // or .toComponents()

const html = `
  <!doctype html>
  <html>
    <head>${styles}</head>
    <body>
      <div id="root">${app}</div>
    </body>
  </html>
`;
```

More details:

- If no registry is provided to `StyleSheetRegistryProvider` then the default one will be used. This can be useful on the client side.
- If no `StyleSheetRegistryProvider` is provided then `<style jsx />` must be noop. This will be useful when you need to do something that is not related to rendering markup. Something like [data resolution](https://github.com/ericclemmons/react-resolver) for the final render when you don't want to do extra work that you don't need.
- `StyleSheetRegistryProvider` can be combined but children provider should not share its styles with a parent provider.
- `StyleSheetRegistryProvider` can be used as config for handled styles.

@giuseppeg what do you think?

**Comment by giuseppeg** [comment]
I don't have a lot of experience with `renderToStream` yet but I see the problem. I think this is related (if not the same issue as) #64. 

I have two questions, which I am asking without having thought about those issues yet:

1) Would it be possible to have a default where users can use styled-jsx like they are doing right now (without a provider?). I want to keep it simple and let advanced users use advanced features (which should be opt-in).

2) With context, would we have to deal with the classic issue where a `shouldComponentUpdate` returns `false` and the provider changes won't reach to the styled-jsx component?

Would it be hard to see a prototype? In case could you use the new Context proposal https://github.com/reactjs/rfcs/pull/2 ? You can see an example  here https://github.com/ReactTraining/react-broadcast/tree/next

**Comment by a-ignatov-parc** [comment]
Answering your questions:

1. We can make it backward compatible with current usage with deprecation warnings for SSR.

1. It's not a problem when your context api is an observer. But I don't think that we should now rely on new context proposal.

I'll try to work on this on weekends 😉

**Comment by a-ignatov-parc** [comment]
Checked details in https://github.com/zeit/styled-jsx/issues/64. These issues are definitely related 👍

**Comment by giuseppeg** [comment]
2) I think we should use the new Context API https://twitter.com/acdlite/status/956390180637650944 maybe even `react-broadcast` if applies

**Comment by a-ignatov-parc** [comment]
> I think we should use the new Context API 

It's not a good idea because users with `react<16.3` won't be able to use it 🤔

**Comment by steida** [comment]
@a-ignatov-parc There is a React polyfill https://github.com/jamiebuilds/create-react-context

**Comment by a-ignatov-parc** [comment]
Thanks, already saw it. I'm pretty sure that we don't need v2 context to fix async SSR. But it might help with some features on the client side.

Nevertheless, I still can't find enough free time to invest in this issue. Maybe we should break it into two parts:

1. Fix SSR.
1. Add features like attaching partial stylesheets to custom documents.

**Comment by a-ignatov-parc** [comment]
I overestimated my free time and I'm afraid I won't find it in near 1-2 months. So it's up to you 👍 

Sorry about that 😞

**Comment by giuseppeg** [comment]
no worries.
As we discussed in the other issue streaming SSR should work already.
Now this issue seems to be #64 i.e. we want to be able to pass a custom stylesheet registry.
