### ISSUE TITLE
before, after selector support?

### ISSUE THREAD

**Issue by katopz** [zeit/styled-jsx#39]
Hi,

I'm not sure `before`, `after` selector are support? In case it will never support, what is replacement or workaround.

Thanks!

**Comment by katopz** [comment]
Oh it did, my bad! sorry for the noise.

**Comment by nkzawa** [comment]
It seems this is not correctly supported.

```css
hr::before {}
```

is transpiled to 

```css
hr::before[data="12345"]
```
