### ISSUE TITLE
Passing variables

### ISSUE THREAD

**Issue by Topthinking** [zeit/styled-jsx#395]
The first CSS is without any style characters, and the second one, you look at the compilation results of these two forms, how do you return the correct form without the style character, just like this?
```js
_react2.default.createElement(_style2.default, {
    styleId: '3568575022',
    css: '{' + _index3.default + _index5.default + ';}',
    css: _index3.default + ' ' + _index5.default + ' .m{a:2;}'
})
```

```js
<style jsx global>{`
   ${style_scss}
   ${style_css}
`}</style>
```

```js
<style jsx global>{`
   ${style_scss}
   ${style_css}.m{a:2}
`}</style>
```

```html
<style id="__jsx-1267422777">{.name{color:red}.name:hover{font-size:120px};}</style>
```

You look at the style tag with multiple curly braces.

```js
import css from 'styled-jsx/css'
import style_scss from './index.scss'

console.log(style_scss)
const styles = css`${style_scss}`
```

**Comment by giuseppeg** [comment]
@Topthinking if you are using external styles like https://github.com/zeit/styled-jsx#keeping-css-in-separate-files or with a loader like https://www.npmjs.com/package/styled-jsx-css-loader then just use a style tag per object

```js
<style jsx global>{style_scss}</style>
<style jsx global>{style_css}</style>
```
Other modes are not supported or guaranteed to work.
