### ISSUE TITLE
[2.2.2] Screen flicker on initial page load

### ISSUE THREAD

**Issue by joncursi** [zeit/styled-jsx#396]
I'm using `styled-jsx` with Next.js and I noticed that when upgrading to `2.2.2`, all of my initial page loads have a flicker. It looks like the CSS rules are being applied after the page paints, so you visually see things snap into place.

This doesn't happen for me on `2.2.1`. Any suggestions on what to do? I don't see any relevant errors in the console, so I'm not sure what has changed to cause this behavior.

Thanks!

**Comment by nickdandakis** [comment]
Can confirm that this happens to my setup as well, on `2.2.2` but not on `2.2.1`. Looks like `flush` from `styled-jsx/server` is crapping out.

**Comment by a-ignatov-parc** [comment]
Guys, do you have nested style tags? Because this issue could be related to https://github.com/zeit/styled-jsx/pull/260

**Comment by nickdandakis** [comment]
I don't think so. Unless if it's something along the lines of a `render` function calling a separate `renderX` function that contains a `styled-jsx` tag.

Would be helpful to see an error of some kind, if that's the case. I also wasn't aware that nesting `styled-jsx` tags is prohibited.

**Comment by giuseppeg** [comment]
@nickdandakis can you prepare a minimal testcase? Maybe a Next.js app that I can clone and try out?

**Comment by nickdandakis** [comment]
@giuseppeg, here ya go:
https://github.com/nickdandakis/styled-jsx-fouc-2-2-2

Unsure if the `postcss` setup is part of this issue, but wanted to replicate my setup as closely as possible. I did however discover that removing `pages/_document.js` also fixes the issue.

**Comment by giuseppeg** [comment]
@nickdandakis before I spend some time on this I would like to ask you to try to reproduce without postcss, just plain CSS.

**Comment by nickdandakis** [comment]
@giuseppeg for sure. Removed the `postcss` stuff from my repo. FOUC is still reproduced.

**Comment by giuseppeg** [comment]
@joncursi @nickdandakis unfortunately with Next.js you can't upgrade styled-jsx like that. 
Dependencies are pinned in Next.js so the framework won't use the version of styled-jsx that you installed by hand to collect styles on the server. 

If you install a different version of styled-jsx its styles registry will be empty when you import and call `flush` in your `_document.js`. That's why the FOUC (styles are not rendered on the server).

The solution is to upgrade Next.js or submit a PR to it to bump the styled-jsx version.

**Comment by nickdandakis** [comment]
I see. I'm pretty sure I explicitly added `styled-jsx` to my `package.json` because of my linter complaining.

Thanks for looking into this!
