### ISSUE TITLE
Warnings that 'jsx' is not a boolean with some usages in render props

### ISSUE THREAD

**Issue by majelbstoat** [zeit/styled-jsx#398]
A simple test case for using styled jsx with a theme render prop works quite nicely:

```jsx
const theme = {
  colors: {
    accent: 'red',
  },
}

class WithTheme extends React.Component {
  render() {
    const { children } = this.props
    return children(theme)
  }
}

const Title = ({ question }) => (
  <WithTheme>
    {({ colors }) => (
      <h1>
        {question.title}
        <style jsx>{`
          h1 {
            color: ${colors.accent};
          }
        `}</style>
      </h1>
    )}
  </WithTheme>
)

export default Title
```

Assuming `theme` has a `colors.accent` property, this will render as expected, which is cool. However, if I modify the definition of the Title component, such that `<WithTheme>` only wraps the style component:

```jsx
const Title = ({ question }) => (
  <h1>
    {question.title}
    <WithTheme>
      {({ colors }) => (
        <style jsx>{`
          h1 {
            color: ${colors.accent.text.normal};
          }
        `}</style>
      )}
    </WithTheme>
  </h1>
)
```

It still works, but React gives the warning:

```
Warning: Received `true` for a non-boolean attribute `jsx`.

If you want to write it to the DOM, pass a string instead: jsx="true" or jsx={value.toString()}.`
```

I would quite like to use this pattern, where there is good locality, and only the CSS rules are wrapped by the theme system, but those warnings make it a non-starter. If I modify the style component to be `jsx="jsx"`, the warning goes away, but then editor syntax highlighting goes away on the CSS rules. I'm not sure where in the chain of transpiling, loading, rendering, etc. this all gets parsed and processed, so I don't know if this is feasible, and obviously can live without it, but would be nice to have.

In use with NextJS 4.2.3, if that matters.

**Comment by a-ignatov-parc** [comment]
I think your issue with the second example is related to https://github.com/zeit/styled-jsx/issues/364. So until fix will lend in future releases you should use the first approach or create HOC to provide theme

```jsx
const Title = withTheme({ question, colors }) => (
  <h1>
    {question.title}
    <style jsx>{`
      h1 {
        color: ${colors.accent.text.normal};
      }
    `}</style>
  </h1>
)
```

**Comment by giuseppeg** [comment]
Yeah style tags need to be children of a `JSXElement` to be transpiled. Eg.

```jsx
<div>
  <style jsx>{....}</style>
</div>
```

**Comment by giuseppeg** [comment]
@majelbstoat for the record when you get that warning it means that your styles were not transpiled by styled-jsx https://github.com/zeit/styled-jsx#warning-unknown-jsx-prop-on-style-tag

**Comment by majelbstoat** [comment]
That's a shame, but I understand. (And I think I understand why it has to be that way. I'm guessing due to the local scoping.) Thanks!

**Comment by RusinovAnton** [comment]
This is still happens to me also. 

My build script:
```
"build": "NODE_ENV=production babel src -d dist",
```
.babelrc:
```json
{
  "presets": ["env", "react"],
  "plugins": [
    "transform-class-properties",
    "transform-object-rest-spread",
    "transform-react-jsx",
    ["styled-jsx/babel", { "plugins": ["styled-jsx-plugin-less"] }]
  ]
}

```

Problem is gone when I remove  "transform-react-jsx" or reorder plugins like so: 
```
["styled-jsx/babel", { "plugins": ["styled-jsx-plugin-less"] }],
...
"transform-react-jsx"
```

**Comment by giuseppeg** [comment]
yep `transform-react-jsx` rewrites jsx and then styled-jsx cannot do its transformations. The solution is to reorder as you said or remove it (or use the undocumented and unstable `passPerPreset: false` babel option)
