### ISSUE TITLE
Communicate tradeoffs

### ISSUE THREAD

**Issue by rauchg** [zeit/styled-jsx#4]
Run benchmarks to accurately communicate the performance tradeoffs involved in:
  - the usage of attribute selectors (varies per browser?)
  - the extra burden of diffing one more attribute per element (React)

**Comment by code-punkt** [comment]
Performance of using attribute selectors opposed to what? class selectors?

**Comment by smashercosmo** [comment]
Original implementation of Angular Material layout engine was based on attribute selectors. And they faced with terrible performance in IE10/IE11.

**Comment by rauchg** [comment]
@smashercosmo any pointers to their benchmarks or discussion thread?

**Comment by rauchg** [comment]
@code-punkt performance of attr selectors vs class, considering also that we'd have to have a runtime class prefixer.

The transformation we might have to use would look like this:

```js
<div className={ a ? 'b' : 'c' }></div>
```

becomes

```js
import _styledJsxPrefix from 'styled-jsx'
<div className=_styledJsxPrefix('r4nd0m', { a ? 'b' : 'c' })></div>
```

and the implementation of `_styledJsxPrefix` would perform class manipulations :)

It's something we already do at https://zeit.co, but only because we hadn't thought of the attribute selector trick :)

So, it's obviously tractable, I just want to know if it's necessary.

**Comment by smashercosmo** [comment]
@rauchg this is the original issue https://github.com/angular/material/issues/1771 and this is a most valuable comment https://github.com/angular/material/issues/1771#issuecomment-133268555

**Comment by rauchg** [comment]
Fascinating. Creating an issue since IE10/IE11 are probably here to stay for a while?

**Comment by rauchg** [comment]
Thank you btw!
