### ISSUE TITLE
Custom mount element

### ISSUE THREAD

**Issue by rmdort** [zeit/styled-jsx#400]
Hi, We have been using styled-jsx for some of the web app. And now trying to use it for Iframe Widgets with https://github.com/ryanseddon/react-frame-component

The issue is styles are always injected in parent `document`. Is there any way we can provide a custom mount element prop

````
<style jsx mountElement={iFramedocument}>{`
  .header {
    color: black;
  }
`}
</style>
````

**Comment by giuseppeg** [comment]
Hi @rmdort yes we will provide support for this at some point https://github.com/zeit/styled-jsx/issues/64
Tracking the issue in https://github.com/zeit/styled-jsx/issues/389

**Comment by rmdort** [comment]
Noted. FYI, for anyone, i have added a fork with support for `react-frame-component`, so that styles can be rendered in an iframe - https://github.com/rmdort/styled-jsx/tree/iframe

**Comment by scottccoates** [comment]
Has there been any update on this? What is the best way to mount inside an iframe?
