### ISSUE TITLE
Issue with compiler

### ISSUE THREAD

**Issue by leoalves** [zeit/styled-jsx#405]
I am just starting with nextjs and styled-jsx.  Sorry if I am not understanding how it works.

I have this code:

```
render() {
    const myStyle = 'html { background-color: white; }'
    const style = `${myStyle}`
    return (
      <div>
        <style global jsx>
          {`
            ${myStyle}
          `}
        </style>
        <style global jsx>
          {style}
        </style>
      </div>
    )
  }
```

The first <style> tag gets compiled into: 
`<style id="__jsx-1409857949">{html { background-color: white; };}</style>`

The second gets compiled into:
`<style id="__jsx-undefined">html { background-color: white; }</style>`

The second is the correct one, without the brackets.  

Shouldn't they both compile to the same thing?

Thanks

**Comment by giuseppeg** [comment]
if you want to define styles outside of the `style` tag you need to use `css`

```jsx
import css from 'styled-jsx/css'
const myStyle = css`html { background-color: white; }`
// ...
render() {
    return (
      <div>
        <style global jsx>{myStyle}</style>
      </div>
    )
  }
```
