### ISSUE TITLE
Duplicate class names

### ISSUE THREAD

**Issue by Echelpoel** [zeit/styled-jsx#407]
Looks like styled-jsx is generating duplicate class names. Any ideas why?

![screen shot 2018-02-09 at 14 28 00](https://user-images.githubusercontent.com/7335810/36030560-04f1e660-0da8-11e8-9d71-76c2c8fb0d0f.png)

**Comment by giuseppeg** [comment]
Can I see the styles? or (better) an example app?

**Comment by giuseppeg** [comment]
@Echelpoel ping

**Comment by Echelpoel** [comment]
Nothing special about the styles. Will try to reproduce in an example app.
```
<style jsx>{`
    .navigation {
        height: ${TOP_BAR_HEIGHT}rem;
        background-color: ${theme.colorTopBar};
        color: white;
    }

    .maxWidthContainer {
        position: relative;
        height: 100%
        max-width: ${theme.maxWidth}rem;
        margin: 0 auto;
        display: flex;
    }
`}</style>
```

**Comment by giuseppeg** [comment]
@Echelpoel I tried to use that css but I couldn't get the duplicated `className`. Can you provide a test case?

**Comment by Echelpoel** [comment]
Been trying to reproduce this without success so it must be something specific to our build. We're using a monorepo with yarn workspaces and I got a gut feeling it has to do something with that.

**Comment by znarf** [comment]
Easy to reproduce in the end, just add `styled-jsx/babel` in the plugins section of your `.babelrc`:

```
  "plugins": [
    [
      "styled-jsx/babel", { "plugins": ["styled-jsx-plugin-postcss"] }
    ]
  ]
```

The problem even happens with `styled-jsx/babel` not loading any plugins:

```
  "plugins": [
    [
      "styled-jsx/babel"
    ]
  ]
```

**Comment by giuseppeg** [comment]
@znarf  that's because  `next/babel` includes `styled-jsx/babel` and Next.js will use that version instead of yours.

**Comment by znarf** [comment]
@giuseppeg Ok, my understanding with the configuration I shared: `styled-jsx/babel` will be loaded 2 times (the one included in `next/babel` and the one from `plugins`  `styled-jsx/babel`). Leading to duplicate class names. Right?

Now, If I want to customize my Next.js installation with a `.babelrc` loading a plugin such as `styled-jsx-plugin-postcss`, how would you suggest to do that?

**Comment by znarf** [comment]
@danielr18 thanks, looks good.

**Comment by znarf** [comment]
@Echelpoel can you share your Babel configuration? Perhaps, it's the same than what we had.

Otherwise, from our side, we can close the ticket.

**Comment by giuseppeg** [comment]
seems like this was figured out, I am going to close but glad to reopen if necessary
