### ISSUE TITLE
Cannot render styles from self-contained method

### ISSUE THREAD

**Issue by ryall** [zeit/styled-jsx#408]
If I try to render JSX in a self-contained method, the JSX is output directly into the DOM instead of being processed.

Works:
```jsx
export default class SomeComponent extends React.Component {
  render() {
    return (
      <header>
        <span>test</span>
        <style jsx>{`
          header {
            background-color: #f88;
            span {
              background-color: #000;
            }
          }
        `}</style>
      </header>
    );
  }
}
```

Doesn't work (style is output literally as-is):
```jsx
export default class SomeComponent extends React.Component {
  render() {
    return (
      <header>
        <span>test</span>
        {this.renderStyle()}
      </header>
    );
  }

  renderStyle() {
    return (
      <style jsx>{`
        header {
          background-color: #f88;
          span {
            background-color: #000;
          }
        }
      `}</style>
    );
  }
}
```

Any reason for this and is there a fix/workaround?

**Comment by a-ignatov-parc** [comment]
Your last example won't work. `styled-jsx` transpiles styles in build type and there is nothing to style in `renderStyle`.

But there are some options:

1. If your styles are static and you want to define them outside your component's markup then you're good to go with [`css` template tag](https://github.com/zeit/styled-jsx#styles-outside-of-components).

1. If you have dynamic styles then you should try [`resolveScopedStyles`](https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent).

1. The least preferred option is to use global styles.

**Comment by ryall** [comment]
Thanks a bunch, I'll take a look now
