### ISSUE TITLE
Global SASS variables with styled-jsx

### ISSUE THREAD

**Issue by oskari** [zeit/styled-jsx#409]
I've been trying to find a way for this but can't figure it out. I'm using styled-jsx in my next.js -project and I want to use some global sass variables for things like colors  but can't figure out how to define them so that my components can use the variables. I don't want to define the variables again and again in every `<style jsx>` block, but just once. Any ideas? I have `styled-jsx-plugin-sass` in use and working.

**Comment by a-ignatov-parc** [comment]
I think you can import file with global variables using `@import` rule 🤔

**Comment by oskari** [comment]
So to use something like variables for colors I would have to import the sass file on every component?

**Comment by a-ignatov-parc** [comment]
Maybe there is a better way but I haven't found any api to provide variables to parser like you can do with `stylus`:

```jsx
const vars = require('stylus-var');

['styled-jsx/babel', {
  plugins: [
    ['styled-jsx-plugin-stylus', {
      use: vars([
        {
          name: `$global-color`,
          value: '#ccc',
        },
      ]),
    }],
  ],
}],

function MyComponent() {
  return (
    <div className='foo'>
      <style jsx>{`
        .foo
          background-color $global-color
      `}</style>
    </div>
  );
}
```

**Comment by giuseppeg** [comment]
I am going to close this since sass doesn't directly relate to styled-jsx. styled-jsx-plugin-sass should support imports now

**Comment by vishnunarayanan** [comment]
@oskari Did you find the fix/workaround? If so please share the solution

**Comment by littlepoolshark** [comment]
@oskari Did you find the fix/workaround? If so please share the solution.

**Comment by oskari** [comment]
@vishnunarayanan @littlepoolshark It works as it's supposed to do, nothing to "fix".  You can import a sass file on every styled-jsx block that has the variables.
