### ISSUE TITLE
render styled jsx after static css file 

### ISSUE THREAD

**Issue by fadiquader** [zeit/styled-jsx#410]
I have a custom document, and i have static css file
![image](https://user-images.githubusercontent.com/23264052/36209118-86e0bd46-11a3-11e8-882b-03696fe84635.png)

and i have jsx style like this
![image](https://user-images.githubusercontent.com/23264052/36209411-53d861be-11a4-11e8-950a-50469c517fa7.png)
and  on browser style jsx always above static style, is there any way to put style jsx below static css ?
![image](https://user-images.githubusercontent.com/23264052/36209506-93ce6d68-11a4-11e8-8ebc-c8b11c43fa97.png)

**Comment by giuseppeg** [comment]
I am not exactly familiar with the implementation of `Head` and the document in Next.js but chances are that you need to render the server side styles before see https://github.com/zeit/next.js#custom-document

You may want to ask them if you need help.
