### ISSUE TITLE
use classes from 'utility libraries' like tailwindcss in styled-jsx

### ISSUE THREAD

**Issue by ryandeussing** [zeit/styled-jsx#417]
I'd like to do something like what [babel-plugin-tailwind](https://github.com/andrewdelprete/babel-plugin-tailwind) or [tachyons-js](https://github.com/jongold/tachyons-js) makes possible, namely using utility classes from a  library like tailwindcss directly in my components.

I've gone down a rabbit hole trying to understand what is necessary to make that possible with styled-jsx and would appreciate any suggestions.

**Comment by ryandeussing** [comment]
I'm closing this b/c I'm pretty sure what https://github.com/joecohens/next-with-tailwindcss enables is exactly what I need.

**Comment by AryanJ-NYC** [comment]
For those of you that stumbled upon this and wished there was a link to the example mentioned above:

https://github.com/zeit/next.js/tree/canary/examples/with-tailwindcss

**Comment by oldo** [comment]
For those that still want to use `@apply` in `styled-jsx` blocks, see here: https://github.com/tailwindlabs/tailwindcss/issues/1234#issuecomment-631817677
