### ISSUE TITLE
renderToNodeStream support

### ISSUE THREAD

**Issue by a-ignatov-parc** [zeit/styled-jsx#418]
Despite not being able to render styles in async (see https://github.com/zeit/styled-jsx/issues/389) there is also no proper support for streamable rendering (see [`renderToNodeStream`](https://reactjs.org/docs/react-dom-server.html#rendertonodestream) and [`renderToStaticNodeStream`](https://reactjs.org/docs/react-dom-server.html#rendertostaticnodestream)).

Currently `styled-jsx` accumulates styles during rendering phase and at the end, we can properly compose final page with styles prepended at the beginning to avoid FOUC.

If we talking about streamable rendering we can say that app is fully rendered only when the last bite is sent to the user. The main issue here is that we can't prepend rendered styles to markup that is already sent.

Here is an example:

```jsx
import { flushToHTML } from 'styled-jsx/server'

server.route('/', (req, res) => {
  res.write('<!doctype html><html><head><title>My Page</title></head><body><div id='content'>');

  const stream = renderToNodeStream(<App />);

  // Lets assume that `flushToHTML()` supports async SSR.
  // There are no styles here because we haven't rendered anything yet.
  // flushToHTML() -> ''

  // Starting rendering app by piping rendering stream to the response.
  stream.pipe(res, { end: false });

  stream.on('end', () => {
    // Styles will be generated only here when app is fully rendered. 
    // The problem is that they are useless here ¯\_(ツ)_/¯
    res.write(`</div>${flushToHTML()}</body></html>`);
    res.end();
  });
});
```

One of the options is to render styles right where they are defined in rendering tree.

```jsx
function App() {
  return (
    <div className='app'>
      <style jsx>{`
        .app {
          background: #ccc;
          padding: 10px;
        }
      `}</style>
    </div>
  );
}
```

Should render as:

```jsx
<div class="jsx-XXXX app">
  <style id="__jsx-XXXX">.app.jsx-XXXX{background: #ccc;padding: 10px;}</style>
</div>
```

This will reduce FOUC to the minimum.

Implementing styles deduplication during SSR and styles consolidation on the client side shouldn't be a big problem.

But there will be issues with some styles:
```jsx
<div class="container">
  <style>
    .item:first-child {
      background: #ccc;
    }
  </style>
  <div class="item">test1</div>
  <div class="item">test2</div>
</div>
```

> There will be no background on `test1`.

We can note this in readme or implement workaround with [chunks reordering](https://github.com/styled-components/styled-components/blob/81f1a20019eb6b2a6de9fe6d6a1882638c1183b1/src/models/ServerStyleSheet.js#L77-L91) like in `styled-components`.

@giuseppeg what do you think?

**Comment by giuseppeg** [comment]
Do you think that it is possible to stream by hand? Like 

```js
stream.on('data', chunk => { res.send(`${flushToHTML()} ${chunk}`) })
```

**Comment by a-ignatov-parc** [comment]
Elements in chunks are not broken apart so I think this could work 👍

**Comment by a-ignatov-parc** [comment]
But only after implementing async-safe rendering because now it could mix styles from different rendering contexts

**Comment by a-ignatov-parc** [comment]
But if chunks are rendered synchronously this could work even now 🤔

Need to check this moment

**Comment by a-ignatov-parc** [comment]
Yeap! it's [synchronous right now](https://github.com/facebook/react/blob/45c1ff348e1c7d03567f5bba6cb32cffa9222972/packages/react-dom/src/server/ReactPartialRenderer.js#L534-L569).

**Comment by giuseppeg** [comment]
@a-ignatov-parc on the server rendering will always be synchronous I guess. Can we close this?

**Comment by a-ignatov-parc** [comment]
I hope they will make it async eventually. Nevertheless, this topic isn't related to this issue. I guess everyone who is interested in using `styled-jsx` with streamable renders will be able to find this issue and use it as guidance. So, yeah, let's close it 😉

**Comment by giuseppeg** [comment]
we can add it to the FAQ section in the readme
