### ISSUE TITLE
Styling root container doesn't work, generated class doesn't get injected in root, only in children

### ISSUE THREAD

**Issue by Vadorequest** [zeit/styled-jsx#419]
How do you style a container? I can style everything inside but not the `.block` class.

```jsx
class Bloc extends Component {
  render() {
    const {children, className, style} = this.props;

    return (
      <Container
        className={classnames("block", className)}
        style={style}
      >
        <div className="content">
          {children}
        </div>
        {/*language=CSS*/}
        <style jsx>{`
          .block {
            background: red;
          }
        `}
        </style>
      </Container>
    );
  }
}
```
Am I missing something obvious or is it not possible?

**Comment by Vadorequest** [comment]
I read https://www.npmjs.com/package/styled-jsx#targeting-the-root but it just won't work for me. Is that a regression?

The generated class doesn't get applied to the container, that's why the styling isn't applied.

**Comment by Vadorequest** [comment]
Here is my config:

`.babelrc`
```
{
  "plugins": [
    "source-map-support",
    "transform-runtime"
  ],
  "presets": [
    ["env", {
      "targets": {
        "node": "6.10"
      }
    }],
    "stage-3",
    [
      "next/babel",
      {
        "styled-jsx": {
          "optimizeForSpeed": true,
          "vendorPrefixes": true,
          "sourceMaps": true,
          "plugins": [
            "styled-jsx-plugin-sass"
          ]
        }
      }
    ]
  ]
}

```

`_document.js`
```jsx
import React from 'react';
import Document, { Head, Main, NextScript } from 'next/document';
import flush from 'styled-jsx/server';

export default class MyDocument extends Document {
  static getInitialProps({ renderPage }) {
    const { html, head, errorHtml, chunks } = renderPage();
    const styles = flush();
    return { html, head, errorHtml, chunks, styles };
  }

  render() {
    const { styles } = this.props;

    return (
      <html>
        <Head>
          <style>{styles}</style>
        </Head>
        <body className="loan-advisor">
          <Main/>
          <NextScript/>
        </body>
      </html>
    )
  }
}

```

`next.config.js`
```js
// const { PHASE_DEVELOPMENT_SERVER } = require('next/constants');

module.exports = (phase, {defaultConfig}) => {
  return {
    webpack: (config, { buildId, dev, isServer, defaultLoaders }) => {
      // XXX https://github.com/evanw/node-source-map-support/issues/155
      config.node = {
        fs: 'empty',
        module: "empty",
      };
      return config;
    },
  };
};

```

**Comment by giuseppeg** [comment]
Please read https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent

**Comment by Vadorequest** [comment]
Well, it's supposed to work out of the box, isn't? That's what the doc shows anyway @giuseppeg

**Comment by giuseppeg** [comment]
You can't style components simply because we (and you) don't know which API they expose. Not every component accepts a `className` props for example. So if you want to target a component with the current version of styled-jsx the only way is to do what is written in the FAQ. In the future we will make the syntax a bit more user friendly.

**Comment by Vadorequest** [comment]
I understand what you're saying, but the doc at https://github.com/zeit/styled-jsx#targeting-the-root make believe it's possible, which isn't the case from what I've experienced.

**Comment by a-ignatov-parc** [comment]
@giuseppeg I think we should add an explicit note about DOM elements because I agree with @Vadorequest that just saying "element" can be confusing. `<Container />` is an element too.
