### ISSUE TITLE
Support for nested <style jsx>

### ISSUE THREAD

**Issue by rauchg** [zeit/styled-jsx#42]
I haven't had the need myself to do this, but it might be interesting to be able to sub-scope:

```js
<div>
  {
    stuff.map((child) => (
      <div>
         <style jsx /> /* scoped to sub-div */
      </div>
    ))
  }
  <style jsx />
</div>
```

**Comment by ericf** [comment]
I ran into this limitation my first try using `styled-jsx` 😄 Here's what I tried to do:

```js
<div className='root'>
  <header className='header'>
    ...
    <style jsx>{`
      .header {}
    `}</style>
  </header>

  <style jsx>{`
    .root {}
  `}</style>
</div>
```

I wanted to group the styles related to `<header>` and its children inside the `<header>` element itself, but got a compilation error when trying to do so.

**Comment by giuseppeg** [comment]
This looks like a single component to me why would you group styles like that instead of using selectors?

**Comment by ericf** [comment]
Because I was thinking of it as `<style scoped>`, and wanted to group styles with their relevant elements. This would also make it quicker to refactor later. The situation I had here was an entire document with a few main sections and my first thought was that I could co-locate my styles within the element tree.

**Comment by rauchg** [comment]
Use selectors, or separate into a different component.

Not supporting that might actually end up encouraging good practices 🤔

**Comment by giuseppeg** [comment]
yup also the following already works:

```jsx
export default class {
  renderHeader() {
    return (
      <header className='banner'>
        ...
        <style jsx>{`
          .banner {}
        `}</style>
      </header>
    )
  }

  render () {
    return (
      <div className='root'>
        {this.renderHeader()}
        <style jsx>{`
          .root {}
        `}</style>
      </div>
    )
  }
}
```

**Comment by rauchg** [comment]
Very cool. Great example @giuseppeg

**Comment by ericf** [comment]
I do like the restriction of not supporting nested `<style jsx>` contexts within a JSX syntax tree, and 👍 on the example of the style scoping working when separate JSX syntax trees are used and composed together via render functions.

I think where this lands is probably a better error message for the example I posted above. I got an error about trying to iterate on a non-iterable iirc.

**Comment by rauchg** [comment]
I was about to say the same. The key is having really good error messages (as always)

**Comment by katopz** [comment]
Refer to https://github.com/zeit/styled-jsx/issues/50#issuecomment-269089363
The first one is `Preact` and it work as expected, but `NextJS` seem to have problem there. For workaround I have to copy css to inner component and it's look not quite right to me.

**Comment by gravitypersists** [comment]
I think I'm seeing this issue in a different way with HOC, so hopefully this is accounted for in a solution:

```
const Color = color => props => (
  <div className='color-container'>
    {color}
    <div>{props.children}</div>
    <style jsx>{`
      .color-container {
        display: inline-block;
        min-width: 50px;
        padding: 5px;
        margin-right: 10px;
        background-color: ${color};
      }
    `}</style>
  </div>
)

const Blue = Color('blue')
const Red = Color('red');
```

so performing `<Red><Blue /></Red>` should give me this:

<img width="98" alt="screen shot 2017-05-28 at 2 54 52 am" src="https://cloud.githubusercontent.com/assets/231863/26527816/0c532eb8-4351-11e7-9655-42f42c5d3311.png">

but instead gives me:

<img width="96" alt="screen shot 2017-05-28 at 2 54 17 am" src="https://cloud.githubusercontent.com/assets/231863/26527818/12ae6994-4351-11e7-9328-aa3fe2a378b2.png">

**Comment by giuseppeg** [comment]
@gravitypersists right now you can only use constants in styled-jsx. That's why you get two blue boxes. We'll make it possible to use dynamic values soon.

**Comment by alexofob** [comment]
Hi there,
I am using nextjs 3 beta and I am getting this issue when I separate my styles into another file
as described in the link below:

https://www.npmjs.com/package/styled-jsx#keeping-css-in-separate-files

Thanks.

BR
Alex

**Comment by hulufei** [comment]
Hi @alexofob, same problem here, and I just spend hours to find out what's cause the problem, it's really tricky.

If the <style> write like this:

```
<style jsx>
  {styles}
</style>
```
then the error raised. The point is the left `{` should write immediately after `>` like this：`<style jsx>{styles}</style>`

Hope this may help you.

**Comment by hulufei** [comment]
@rauchg this maybe a new issue?

**Comment by giuseppeg** [comment]
@hulufei it is, there is an open issue already.

**Comment by mattfysh** [comment]
Latest version of `prettier` now nests contents of `<style>` on a newline, creating this error. A better error message would be helpful, now just to find out what the syntax is for getting prettier to ignore a line

**Comment by mattfysh** [comment]
This also works:

```jsx
<style jsx>{`
  ${myStyles}
`}</style>

**Comment by giuseppeg** [comment]
Closing since I think that in order to stay close to the ShadowDOM behavior we should support this. Styles within a component affect the entire component.

**Comment by moatorres** [comment]
Not sure if that's related to this issue either if that's the right place to ask, but how do we account for when we'd like to compose classes defined in different components/style blocks?

As in:
```js
const Sidenav = ({ children }) => {
  return (
    <nav className="sidenav">
    {children}
    <style jsx>{`
      .sidenav{
        color: red;
      }
      .sidenav.sidenav-item {
        color: blue;
      }
    `}</style>
    </nav>
  )
}
```

```js
const SidenavItem = ({ children }) => {
  return (
    <div className="sidenav-item">
    {children}
    <style jsx>{`
      .sidenav-item {
        border: 1px solid rgba(255, 255, 255, 0.9);
      }
    `}</style>
    </div>
  )
}
```

That doesn't seem to work as I imagine each class will have a random name like:

```js
<nav class="jsx-2032940618"</nav>
```

We could do something like `.sidenav a {...` but what if we can't select all `<a></a>` blocks? 🤔

**Comment by moatorres** [comment]
Nevermind, just figured out that we can simply add the class on the child component without defining styles and will be caught by the parent' nested-class definitions.
