### ISSUE TITLE
!important breaks CSS when used with jsx-scss plugin

### ISSUE THREAD

**Issue by Vadorequest** [zeit/styled-jsx#420]
I followed https://github.com/zeit/next.js/tree/canary/examples/with-styled-jsx-scss example.

I just noticed that when using `!important`, it breaks the rendered css.

```css
        <style jsx global>{`
          .loan-advisor {
            * {
              font-family: ${theme.font};
            }

            b {
             color: ${theme.primaryColor} !important;
            }

        `}</style>
```

![image](https://user-images.githubusercontent.com/3807458/37263692-89531bf4-25a9-11e8-9985-07b31cb37316.png)

I also just noticed I don't need to use !important (due to the way styled-jsx works), but if that's the expected behaviour then a note in the README would be great :)

By removing all `!important` rules, everything worked as expected.

**Comment by giuseppeg** [comment]
This is an issue with styled-jsx-plugin-sass not styled-jsx itself. I just published a new version of styled-jsx-plugin-sass with a fix

**Comment by Vadorequest** [comment]
Thanks @giuseppeg I'll try it ASAP!
