### ISSUE TITLE
Combining styles into one scope

### ISSUE THREAD

**Issue by lgordey** [zeit/styled-jsx#426]
When I run `flushToHTML` I've got multiple style tags like this:
```jsx
<style id="123">{styles123}</style>
<style id="456">{styles456}</style>
<style id="789">{styles789}</style>
```
But for [AMP](https://www.ampproject.org/docs/fundamentals/spec#stylesheets) version I need to reduce multiple styles to one special and place all styles inside.
I can do it this way:
```jsx
<style amp-custom>
   flushToHTML().replace(/<.*?>/g, '');
</style>
```

But may be there is some better solution from box?

**Comment by giuseppeg** [comment]
you can import `flush` from 'styled-jsx/style' :)
