### ISSUE TITLE
css is undefined

### ISSUE THREAD

**Issue by Tekkromancer** [zeit/styled-jsx#428]
I'm attempting to implement the [External CSS and styles outside of the component](https://github.com/zeit/styled-jsx#external-css-and-styles-outside-of-the-component)  feature).
```
/* styles.js */
import css from 'styled-jsx/css'
// Scoped styles
export const button = css`button { color: hotpink; }`

// Resolved styles
export const link = css.resolve`a { color: green; }`
...
```
This throws the error "ReferenceError: css is not defined".

Naturally, `css.resolve` won't work because of this issue.

Am I missing something?

**Comment by giuseppeg** [comment]
Hi unfortunately that feature hasn't been released yet. The branch is `next` and a new release will come later this month with those features.

From the docs: 

> Code and docs are for v3 which we highly recommend you to try. Looking for styled-jsx v2? Switch to the v2 branch.

**Comment by bevinhex** [comment]
this css seems to be still a problem, in latest v5
`import css from 'styled-jsx/css'` works in some components, while returning undefined in another component
