### ISSUE TITLE
StyleSheetRegistry is added to bundle when using babel

### ISSUE THREAD

**Issue by shlomokraus** [zeit/styled-jsx#429]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behavior?
StyleSheetRegistry is bundled along with the code the exported file when bundling a component with webpack and babel plugin: styled-jsx/babel

#### What is the expected behavior?
When bundling a component library with styled-jsx as peerDeps, shouldn't be added. It is causes flash on unstyled content when using component from libraries.

#### Environment (include versions)

* styled-jsx (version): 2.6.6

#### Did this work in previous versions?
No

**Comment by shlomokraus** [comment]
#225

**Comment by giuseppeg** [comment]
can you share your setup to compile the component?

**Comment by giuseppeg** [comment]
could you use https://webpack.js.org/configuration/externals/ ?

**Comment by shlomokraus** [comment]
I tried the externals but it didn't work, the problem is that externals need to be setup like this: 

`externals: {
    "styled-jsx/style": { commonjs: "styled-jsx/style", commonjs2: "styled-jsx/style" }
  },`

That is: "styled-jsx/style" and not just "styled-jsx". 

Also, styled-jsx must be ommited out from the project's node_modules so the one from parent's node_modules will be picked up by the resolver.
