### ISSUE TITLE
Transpiled error only when I execute jest--coverage

### ISSUE THREAD

**Issue by frankPairs** [zeit/styled-jsx#430]
#### Do you want to request a *feature* or report a *bug*?
Bug
#### What is the current behavior?
When I execute jest --coverage, tests launch the next error only in files where I import styled-jsx/css:

"styled-jsx/css: if you are getting this error it means that your `css` tagged template literals were not transpiled."

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1. execute command "node_modules/.bin/jest --coverage"

#### What is the expected behavior?
Test shouldn't fail for styled-jsx transpile problems.

#### Environment (include versions)

* OS: macOS Sierra
* Browser: -
* styled-jsx (version): 2.2.6

#### Did this work in previous versions?
I don't know

**Comment by bensaufley** [comment]
Are you using babel in your Jest workflow? If not, that would be your issue. Babel is required to transpile `styled-jsx/css` and there's no non-transpiled functionality.

**Comment by frankPairs** [comment]
oh ok! yeah, I'm not using babel to run tests. make sense, then probably that is the error, I'll test it, thx so much!

**Comment by giuseppeg** [comment]
@frankPairs did you solve this issue?

**Comment by damusnet** [comment]
Hi @giuseppeg, I am having the exact same issue. Can we reopen please?

I am using babel when running tests, with the `"presets": [["next/babel", { "preset-env": { "modules": "commonjs" } }]]` configuration. I tried adding a bunch of babel presets/plugins, but nothing worked. Really not sure where to search.

Also, again, it only happens with `--coverage`, not with regular tests.

**Comment by damusnet** [comment]
this seems like a duplicate of #436 ; I'll continue there ; no need to reopen.
