### ISSUE TITLE
"*" selector is rewritten to invalid CSS

### ISSUE THREAD

**Issue by atombender** [zeit/styled-jsx#435]
#### What is the current behavior? The following CSS:

```
.MyComponent > * { ... }
```

is transpiled into:

```
.MyComponent.jsx-1941991312>*.jsx-1941991312{...}
```

This is of course not valid CSS, and will never work.

#### What is the expected behavior?

I would expect this to transpile to either `.MyComponent.jsx-1941991312>*`, or something `.MyComponent.jsx-1941991312>.jsx-1941991312-child` if the class name could be attached to children automatically (they aren't, though).

#### Environment (include versions)

* styled-jsx (version): 2.2.6

**Comment by giuseppeg** [comment]
`*.classname` is valid css. There are other ways to style child components https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent

If you then want `.MyComponent.jsx-1941991312 > *` you should use `:global()`: 

```css
.MyComponent > :global(*) { ... }
```
