### ISSUE TITLE
ReferenceError: element is not defined

### ISSUE THREAD

**Issue by iamawebgeek** [zeit/styled-jsx#442]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behavior?
Getting exception on runtime - `ReferenceError: element is not defined`

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

```js
// component
class Tabs extends React.Component {
  renderLink = (element) => {
    console.log(element.props.width) // gives - 200
    return (
      <a
        className="link"
        {...element.props.linkProps}
      >
        <style jsx={true}>
          {/* language=SCSS */ `
          .link {
            display: inline-block;
            height: 30px;
            line-height: 30px;
            text-decoration: none;
            text-align: center;
            width: ${element.props.width}px; // <- this line causes an error
          }
          `}
        </style>
        {element.props.text}
      </a>
    )
  }
  renderLinks() {
    return (
      <div className="header">
        {React.Children.map(this.props.children, this.renderLink)}
      </div>
    )
  }
  renderContent() {
  }
  render() {
    return (
      <div className="tabs">
        {this.renderLinks()}
        {this.renderContent()}
      </div>
    )
  }
}

class Tab extends React.Component {
  static defaultProps = {
    width: 200,
    linkProps: {},
  }
  render() {
    return (
      <React.Fragment>
        {this.props.children}
      </React.Fragment>
    )
  }
}

// usage
<Tabs>
  <Tab text="test">
    <p>Content</p>
  </Tab>
  <Tab text="test 2">
    <p>Content 2</p>
  </Tab>
</Tabs>
```

#### What is the expected behavior?
Render link with given width

#### Environment (include versions)

* OS: Linux
* Browser: latest Chrome & Firefox
* styled-jsx (version): 2.2.6

#### Did this work in previous versions?
No

**Comment by giuseppeg** [comment]
can you try without the `React.Fragment` because the transpiled code looks good

```js
_defineProperty(this, "renderLink", element => {
  console.log(element.props.width); // gives - 200

  return (
    <a
      {...element.props.linkProps}
      className={
        _JSXStyle.dynamic([["232076454", [element.props.width]]]) +
        " " +
        ((element.props.linkProps.className != null &&
          element.props.linkProps.className) ||
          "link")
      }
    >
      <_JSXStyle
        styleId={"232076454"}
        css={`
          .link.__jsx-style-dynamic-selector {
            display: inline-block;
            height: 30px;
            line-height: 30px;
            -webkit-text-decoration: none;
            text-decoration: none;
            text-align: center;
            width: ${element.props.width}px;
          }
        `}
        dynamic={[element.props.width]}
      />
      {element.props.text}
    </a>
  );
});

```

**Comment by iamawebgeek** [comment]
@giuseppeg I have removed `React.Fragment` and still getting the same error:
![err](https://user-images.githubusercontent.com/8792609/39569231-098fbfd6-4ede-11e8-961c-25071451d8cf.png)
If I remove dynamic style, it works ok again

**Comment by iamawebgeek** [comment]
@giuseppeg neither of them. Used CRA with eject

**Comment by giuseppeg** [comment]
@iamawebgeek please try to debug your application or setup, we have never had this issue. I will close the issue in one week if there is no update.

**Comment by iamawebgeek** [comment]
@giuseppeg I couldn't figure out what is the root of the problem debugging my code, so I have create a gist and pasted there piece of `bundle.js` and my component's source code. I think this line causes an error: https://gist.github.com/iamawebgeek/ce3c1f3283c55a5dae922bcc5d853f05#file-bundle-js-L159

**Comment by giuseppeg** [comment]
@iamawebgeek the code in that gist is different from the one you posted in the original message. Please create a **minimal** testcase using Next.js or something. I'll close the issue in 1 week if I don't hear back by then
