### ISSUE TITLE
hot reload in non-next.js apps breaks when changing <style jsx> tag

### ISSUE THREAD

**Issue by rgbkrk** [zeit/styled-jsx#443]
We share some components between next.js apps and some standalone apps (backed by Python) that all use `styled-jsx`. 🎉 

Recently we added hot module reloading to the python app and noticed that editing any `<style jsx>` elements will cause an error (and also fail reload). 

<img width="1552" alt="screen shot 2018-05-04 at 1 15 08 pm" src="https://user-images.githubusercontent.com/836375/39650892-b429280e-4f9e-11e8-8000-ba0849b13a94.png">

Is there a certain way we should configure things for styled-jsx + HMR on non-next.js app?

#### Do you want to request a *feature* or report a *bug*?

Bug

#### What is the current behavior?

HMR in non-next.js apps using styled-jsx will break when changes affect a `<style jsx>` tag.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1. TODO (I'll come back to doing this)

#### What is the expected behavior?

✨ Live updating components and no errors  ✨ 

#### Environment (include versions)

* OS: MacOS
* Browser: Chrome
* styled-jsx (version): 2.2.6

#### Did this work in previous versions?

N/A

**Comment by josiahwiebe** [comment]
The same issue seems to be occurring in Next.js apps as well. See https://github.com/zeit/styled-jsx/issues/425#issuecomment-386204155 as it could be related.

**Comment by giuseppeg** [comment]
yea react-hot-loader v4 doesn't reload properly. Use react-hot-loader v3 until we chat with the RHL people and see how we can fix it
