### ISSUE TITLE
Multi-level descendant selectors break with when using global and split across lines

### ISSUE THREAD

**Issue by masad-frost** [zeit/styled-jsx#444]
#### Do you want to request a *feature* or report a *bug*?
bug

#### What is the current behavior?
Splitting descendants across multi lines with a global ancentor breaks the style, it ends up creating a simple single class selector.

```
:global(.a)
  .b
  .c {
    color: blue;
}
```
Produces `.c.jsx-123` removing new lines makes it work fine.

I ran into this issue after prettier split my selector into multiple lines and I ended up with a broken webpage :man_shrugging: 

Repro next app, logic is in `pages/index.js`
https://repl.it/@masfrost/StyledJsxGlobalDecendant

#### What is the expected behavior?
 it produces `.a .b-jsx123 .c-jsx123` instead

#### Environment (include versions)
Any

#### Did this work in previous versions?
Breaks on the previous major version as well.

**Comment by giuseppeg** [comment]
can you file an issue on https://github.com/thysultan/stylis.js ? It is the css compiler that processes our styles and resolves selectors

**Comment by masad-frost** [comment]
Will do thanks.

**Comment by masad-frost** [comment]
Done https://github.com/thysultan/stylis.js/issues/104

**Comment by giuseppeg** [comment]
@masad-frost published 2.2.7
