### ISSUE TITLE
Making styled-jsx work better with Jest snapshots

### ISSUE THREAD

**Issue by callumlocke** [zeit/styled-jsx#459]
### Do you want to request a *feature* or report a *bug*?

A feature.

### What is the current behavior?

Most people don't want to include tons of `jsx-******` classnames in their Jest snapshots, nor lots of vendor prefixed CSS properties. It just makes the snapshot harder to read, and provides no useful information. There's no need to test styled-jsx's functionality every time you test your own components.

To make things worse, whenever you change your CSS, you end up with a lot of diff noise as all your DOM nodes get new classnames. All you really need to see in the diff is the lines of CSS that changed.

**Current best workaround**

As outlined in this [blog post](https://kevinjalbert.com/jest-snapshots-reducing-styled-jsx-noise/), you can simply switch off the `styled-jsx/babel` plugin for the `test` [environment](https://babeljs.io/docs/en/babelrc/#env-option) in your .babelrc. So your snapshots end up containing uncompiled `<style jsx>...</style>` elements, which is what you want.

**Problems with the workaround**

When rendering with enzyme or react-test-renderer, you end up with a tons of `console.error` noise coming from React when running your tests:

```
Warning: Received `true` for a non-boolean attribute `jsx`.
(...followed by a long stack)
```

Another problem is, when using something like enzyme's `wrapper.text()` to make an assertion about the rendered text content of your component, you get the component's raw CSS concatenated onto the end of the real text content, because the content of a `<style>` tag technically counts as a text node. (You can avoid this by selecting a descendant instead of the wrapper, but that sometimes means you have to add extra structural elements purely to work around this issue, which isn't ideal.)

### What is the expected behavior?

I suggest exposing an alternative Babel plugin entrypoint at `"styled-jsx/babel-test"` — or alternatively adding some kind of 'test mode' option on the regular `"styled-jsx/babel"` plugin to use this behaviour.

This would just do a light-touch conversion of `<style jsx>...</style>` elements, just enough to make them suitable for snapshotting. Like this:

```jsx
<div className="foo">
  <style jsx>{`
     .foo { transition: all 1s ease; }
  `}</style>
</div>

// ...would compile to something like:
<div className="foo">
  <style data-styled-jsx="{`
     .foo { transition: all 1s ease; }
  `} />
</div>
```

- The plain `jsx` boolean attribute is removed to prevent React warnings.
- The raw CSS should not be prefixed/modified in any way.
- There should be no `jsx-*****` classnames generated anywhere, so the rest of the component remains untouched.
- The CSS is moved into a data attribute so it doesn't count as a text node.

**Comment by giuseppeg** [comment]
hi thanks for the detailed description, I agree with you and making a simple `styled-jsx/babel-test` plugin to remove the `jsx` is very straightforward https://astexplorer.net/#/gist/39a246d5f4e5e8907303ee23dcfd5158/981e9936b1f13dd066fa4e8cb8184f5d0a508fe9

I am not sure about moving the CSS to an attribute though, I think that this can be solved in user land with an utility function (I am not familiar with enzyme's text() but in JS I would make an utility that clones the tree and removes the `style` block from the tree before calling text)

**Comment by giuseppeg** [comment]
it would be great if you could make a PR for `styled-jsx/babel-test`. Maybe against the `next` branch which is the upcoming v3

**Comment by giuseppeg** [comment]
by the way are you using styled-jsx at Financial Times by any chance?

**Comment by giuseppeg** [comment]
I think that we should just remove the `jsx` attribute and leave the rest as-is.

> I left in January. Just updated my bio. I was using styled-jsx there myself (via Next.js) for a couple of small things, not sure if they still are still using it!

Oh I see, good luck then with what's next :)

**Comment by giuseppeg** [comment]
funny enough once I interviewed at the FT and got an offer but then I also go another in SF too and I accepted the latter :)

**Comment by nickluger** [comment]
I was thinking about a Jest serializer for styled-jsx (https://github.com/zeit/styled-jsx/issues/488) but will wait for this here.

**Comment by etiennejcharles** [comment]
I've probably missed something: I'm still getting "jsx-element" in my snapshots even though I included the styled-jsx/babel-test plugin in my configuration,  

Could you help point in the right direction? @nickluger or @callumlocke  ? 

![image](https://user-images.githubusercontent.com/2872476/85931756-b932b480-b894-11ea-8c48-508fc75222fc.png)

This based on: https://github.com/vercel/next.js/tree/canary/examples/with-jest
