### ISSUE TITLE
media queries missing curly braces

### ISSUE THREAD

**Issue by krisdante** [zeit/styled-jsx#467]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behavior?

I have following style tag:
```
<style global jsx>
{`html {
    font-size: 16px;
    font-size: 4.3vw;
}

@media (min-width: 481px) {
    html {
        font-size: 1.145vw;
    }    
}

@media (min-width: 1368px) {
    html {
        font-size: 16px;
    }
}`}
</style>

```
this produces following CSS:
```
<style id="__jsx-821446881">html{font-size:16px;font-size:4.3vw;}@media (min-width:481px) html{font-size:1.145vw;}@media (min-width:1368px) html{font-size:16px;}
</style>
```

As you can see mediaqueries are missing curly braces and that is invalid CSS (at least according to CSS Validator) and also do not owrk in Chrome. 

#### What is the expected behavior?

When I add (with inspector) missing brackets - everything works fine.
Expected:
```
<style id="__jsx-821446881">html{font-size:16px;font-size:4.3vw;}@media (min-width:481px) {html{font-size:1.145vw;}}@media (min-width:1368px) { html{font-size:16px;}}
</style>
```

#### Environment (include versions)

* OS: Windows
* Browser: Chrome
* styled-jsx (version): 2.2.6

#### Did this work in previous versions?

I don't know

**Comment by krisdante** [comment]
This drives me crazy. It happens also for normal styles sometimes. I can not find a pattern.

**Comment by jlmitch5** [comment]
@krisdante updating next to the latest next.js 7.0 canary fixed media queries (generally) for me (this also updates styled-jsx to the 3.0 canary)
