### ISSUE TITLE
Compile away styled-jsx/server when styled-jsx is not used

### ISSUE THREAD

**Issue by timneutkens** [zeit/styled-jsx#468]
#### Do you want to request a *feature* or report a *bug*?

feature

#### What is the current behavior?

If there's not a single usage of `<style jsx>` styled-jsx/server can be compiled away as it won't have any result in an app. This is specifically the case when using Next.js + another css-in-js or css imports library, as it won't need styled-jsx's server-side runtime to execute. 

#### What is the expected behavior?

This behavior can be optimized by compiling away usage of the `flush` method, by turning:

```
import flush from 'styled-jsx/server'
const styles = flush()
console.log(styles)
```

Into:
```
const styles = []
console.log(styles)
```

When no styled-jsx tags are used throughout the app.

**Comment by giuseppeg** [comment]
We chatted about this and I think we agree that it should be implemented in user-land since it is a Next.js specific behavior.
