### ISSUE TITLE
Constants do not work with TypeScript (Babel 6)

### ISSUE THREAD

**Issue by ssylvia** [zeit/styled-jsx#471]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behavior?
[Constants](https://github.com/zeit/styled-jsx#constants) do not work with TypeScript unless TypeScript is compiled with Babel 7.

Is there any way to use constants while using tsc then babel 6? There are many libraries (including Storybook) that do not support Babel 7.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

Sample Repo here: https://github.com/ssylvia/styled-jsx-constants-example.

Under this monorepo there are two packages with the same `src` components and constants:
- **styled-jsx-ts-then-babel**: Compiles typescript with `jsx: preserve` using `tsc` and then runs the compiled js files through babel-cli (v6.x)
- **styled-jsx-ts-with-babel**: Compiles typescript with babel 7 beta.

When compiling `styled-jsx-ts-then-babel` package, the babel-cli fails with the following error:

```
SyntaxError: build/components/Button.jsx: Expected a template literal or String literal as the child of the JSX Style tag (eg: <style jsx>{`some css`}</style>), but got BinaryExpression
  22 |         var primaryTextColor = "white";
  23 |         var primaryBackgroundColor = "blue";
> 24 |         return (<Fragment>
     |                 ^
  25 |         <button type="button">Button</button>
  26 |         <style jsx>{"\n          button {\n            color: " + primaryTextColor + ";\n            background: " + primaryBackgroundColor + ";\n          }\n        "}</style>
  27 |       </Fragment>);
```

#### What is the expected behavior?
style-jsx should compile constants in compile typescript.

#### Environment (include versions)

* OS: MacOS
* Browser: NA
* styled-jsx (version): 2.2.7

**Comment by giuseppeg** [comment]
can you upgrade to styled-jsx v3.1.0 and let me know if this is still an issue?

**Comment by ssylvia** [comment]
Yep, this is still an issue in the current version, repo update: https://github.com/ssylvia/styled-jsx-constants-example.

Our team switched over to compiling typescript with babel so not a current blocker for us.

**Comment by aleksspeaker** [comment]
@giuseppeg why's that issue is closed?
Is it fixed?

**Comment by giuseppeg** [comment]
Hi @aleksspeaker I thought the OP gave up on styled-jsx and we now support Babel 7. 
Do you have a test case that uses the latest version of styled-jsx?
