### ISSUE TITLE
StyleSheetRegistry in optimizeForSpeed mode should keep track of invalid rules

### ISSUE THREAD

**Issue by rgbkrk** [zeit/styled-jsx#474]
#### Do you want to request a *feature* or report a *bug*?

Feature (to report on user level issues)

#### What is the current behavior?

Same as #319 (which is closed and locked), there's a persistent issue we're facing when developing component libraries using styled-jsx that later get used in next.js apps. If the browser rejects the sheet (with a warning), styled jsx doesn't notice and later causes an error when trying to delete that style sheet.

![image](https://user-images.githubusercontent.com/836375/43859413-62a983a4-9b05-11e8-9188-4fce68784161.png)

![image](https://user-images.githubusercontent.com/836375/43859417-6645ead4-9b05-11e8-820d-c45dba1be92e.png)

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

Example to reproduce with, along with steps: https://github.com/nteract/nteract/pull/3212

There is always the chance that the optimizer is just _wrong_ and isn't validating it's output! Not sure where that happens though.

#### What is the expected behavior?

What I'd _love_ is for styled-jsx to be able to detect when a stylesheet is bad _in advance_. I can't tell from how styled-jsx operates when something is going to be wrong as a contributor is adding it. I need tooling to let us know what to fix / change.

#### Environment (include versions)

* OS: macOS
* Browser: Chrome
* styled-jsx (version): 2.2.6

#### Did this work in previous versions?

¯\\\_(ツ)\_/¯

**Comment by rgbkrk** [comment]
One thing that I know we're doing for our built components is that we set `NODE_ENV=production` while running the babel build. That affects styled-jsx as far as I'm aware.

**Comment by giuseppeg** [comment]
it seems that you have source maps in production and those don't work when `optimizeForSpeed` is `true`: https://github.com/zeit/styled-jsx#optimizeforspeed let me know if this helps (set it to `false` explicitly)

**Comment by rgbkrk** [comment]
We are currently setting `optimizeForSpeed` to false explicitly. I'm a bit surprised about the source maps being enabled in production, we're not enabling them in our next config. How do we detect this problem in advance at build time? When modifying webpack config for next, does this have to be explicitly set somehow?

**Comment by giuseppeg** [comment]
you can pass styled-jsx options to Next as explained here https://github.com/zeit/next.js/#customizing-babel-config

**Comment by giuseppeg** [comment]
in your sample repo `optimizeForSpeed` is set to `true` https://github.com/nteract/nteract/pull/3212/files#diff-445d46616d10bd0a08537927862f0087R14 when it is set to `true` source maps should be disabled, you can do that by passing `sourceMaps: false`. If that doesn't work probably we have a bug with in the options logic. I'd need to try your branch out, right now I can't unfortunately

**Comment by giuseppeg** [comment]
@rgbkrk any update?

**Comment by rgbkrk** [comment]
We've set `optimizeForSpeed` to false. In that pull request I'm setting it to true on purpose to showcase what happens. We're not blocked.

I'm unsure how to communicate that this issue is about finding a way to surface what stylesheets are problematic. I love being able to recommend styled-jsx and just want to make sure the developer experience gets better and better.

**Comment by giuseppeg** [comment]
Fair enough, this in fact seems to be a bug. See:

https://github.com/zeit/styled-jsx/blob/9f53a7411318aff0c4a5f8d73bf6aed83ed2fdf7/src/stylesheet-registry.js#L60-L77

I believe that we can fix it by removing the check at L65 since this https://github.com/zeit/styled-jsx/blob/9f53a7411318aff0c4a5f8d73bf6aed83ed2fdf7/src/stylesheet-registry.js#L85-L86 will still work because `this._indices[styleId]` is either an empty array or anyway contains only the indices of valid inserted rules.

Would you have some time to put together a simple patch?

**Comment by rgbkrk** [comment]
Sure I just submitted https://github.com/zeit/styled-jsx/pull/476

**Comment by giuseppeg** [comment]
fixed in #476
