### ISSUE TITLE
styled-jsx flickers on initial load

### ISSUE THREAD

**Issue by schulke-214** [zeit/styled-jsx#477]
#### The Bug im Facing:

On the inital-load of my page, the styles don't get applied instantly, they come in after a short delay, which causes flickering. Ive expierienced this behavior in my own project, and thought it was the way   
i work with the _document.js file etc, but as i where able to reproduce this in a fully blank next.js project, this seems to be something different.

I've created a repo with a project-setup that should allow u to reproduce the bug:
https://github.com/schulke-214/styled-jsx-ssr-bug

I think it might be the way i outsource the styles.

#### The Expected Behavior

The Styles should be applied instantly with the Pageload, and there shouldn't be a delay between the Painting of the HTML and the Styles.

#### Environment (include versions)

* OS: Mac OS High Sierra 10.13.5
* Browser: Chrome 67.0.3396.99
* styled-jsx (version): 3.0.2
* next.js: 6.1.1

#### Did this work in previous versions?

I already tried to install older versions, it seems to make no difference.

**Comment by giuseppeg** [comment]
Can you try to use `next@7.0.0-canary.0`? 

I believe that Next.js uses another version even if you install `3.0.2` because the `next/babel` preset points to that one. Basically in order to upgrade styled-jsx in a Next.js project you either need to patch the configuration by hand or wait for them to upgrade.

**Comment by schulke-214** [comment]
@giuseppeg 
I tried it now, it changes nothing.

Behaves the same as with a `next@6.x.x` version.
In the meantime, i found a _workaround_?
The way that works for me is manually rendering the styles into style tags using flush from `styled-jsx/server`. 

Here is my _document.js (a little modified for example purposes):

```javascript
import Document, { Head, Main, NextScript } from 'next/document';
import flush from 'styled-jsx/server';

class AppDocument extends Document {
    static async getInitialProps(ctx) {
        const initialProps = await Document.getInitialProps(ctx);
        const styles = flush();
        return { ...initialProps, styles }
    }

    render() {
        return (
            <html lang="de">
                <Head>
                    <link rel="stylesheet" href="/static/fonts/fonts.css" />
                    { this.props.styles }
                </Head>
                <body className="loading main-bg-color" >
                    <Main />
                    <NextScript />
                </body>
            </html>
        )
    }
}
```

I dont know if its meant to be used like this, or just for a different usecase, since its build in `styled-jsx`, but friends of mine, were able to use styled-jsx without doing this.

And: this broke my way to use styled-jsx ( at least kind of ), since now, as i believe, because i cant conditionally render styled-jsx blocks ( i need to check this again, if it really does, i will open a seperate issue since these are not related ).

**Comment by schulke-214** [comment]
i just figured out, that im double inserting the styles with my `{ this.props.styles }`, i removed it now.

**Comment by giuseppeg** [comment]
this should be working on v3.1.0 (or latest Next.js canary)
