### ISSUE TITLE
Received `true` for a non-boolean attribute `jsx`.

### ISSUE THREAD

**Issue by jan0991** [zeit/styled-jsx#481]
I installed `styled-jsx` and `styled-jsx-plugin-sass`, changed my .babelrc to:
```
{
  "plugins": [
    "react-hot-loader/babel",
    [
      "styled-jsx/babel",
      { "plugins": ["styled-jsx-plugin-sass"] }
    ]
  ],
  "presets": [
    "env",
    "stage-0",
    "react"
  ]
}
```

It fails to parse style tag with 

> Received `true` for a non-boolean attribute `jsx`. 

Code looks like
```
<div>
{/* language=CSS */}
        <style jsx global>
{`...`}
</style>
</div>
```

What am I missing?

**Comment by jan0991** [comment]
My bad, webpack local config overwrote .babelrc. Closing.

**Comment by yasintz** [comment]
@jan0991  How did you solve it?

**Comment by Virgil-N** [comment]
I had the same problem with vite and sass installed. How to solve it?
