### ISSUE TITLE
Upgrading to v7.0.0.-10 NextJS Throws "_JSXStyle" has already been declared error

### ISSUE THREAD

**Issue by ssylvia** [zeit/styled-jsx#487]
#### Do you want to request a *feature* or report a *bug*?
Bug
#### What is the current behavior?

Styled-jsx

<img width="1094" alt="screen shot 2018-09-03 at 11 13 16 am" src="https://user-images.githubusercontent.com/1211360/44993922-632ba900-af6a-11e8-8cb7-40d8837e8f6d.png">

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

Steps to reproduce the behavior, please provide code snippets or a repository:
1. Clone this repo: https://github.com/ssylvia/styled-jsx-multi-declare
2. It's a monorepo, `yarn install` from root.
3. `cd packages/app`
4. `yarn dev`
5. Open browser at `localhost:3000`

#### Environment (include versions)

* OS: Mac
* Browser: Chrome
* styled-jsx (version): styled-jsx@3.0.3-canary.0

#### Did this work in previous versions?

Yes

Cross-posted in NextJS Issues: https://github.com/zeit/next.js/issues/5080

**Comment by timneutkens** [comment]
Explained here: https://github.com/zeit/next.js/issues/5080#issuecomment-418151172

**Comment by Vitaminaq** [comment]
There is no need to use Babel and install style-jsx in next
