### ISSUE TITLE
How to style non-DOM components?

### ISSUE THREAD

**Issue by ianstormtaylor** [zeit/styled-jsx#49]
All of the examples only show how to style core DOM nodes in JSX, like `<p>`:

```js
  <div>
    <p>only this paragraph will get the style :O</p>
    { /* you can include <Component />s here that include
         other <p>s that don't get unexpected styles! */ }
    <style jsx>{`
      p {
        color: red;
      }
    `}</style>
  </div>
```

Is it possible to use `styled-jsx` to pass styles into components, like `<Button>`? Having a hard time understanding how that would work, or how this library is a true solution to CSS without that? Would I need to require one of the other CSS-in-JS solutions to theme things?

**Comment by rauchg** [comment]
1. `<Button>` would have its own `<style jsx>`. To customize components, we pass props which configure inline styles in addition to the static CSS
2. To override 3rd-party components, many admit a class. You can pass an [unprefixed class](https://github.com/zeit/styled-jsx#global-selectors) for that.

**Comment by rauchg** [comment]
In general what we find is that you most likely pass properties like `<Button large>` and then toggle a class name, and your CSS contains both classes.  This is much more performant than dynamic CSS, since the CSS gets parsed and compiled once, and toggling is much faster

**Comment by ianstormtaylor** [comment]
Would be awesome to see an example in the Readme showing a property like `primary` or `large` inside a common "core" component like `<Button>` being toggled, to understand what the idiomatic way to do that with `styled-jsx` is. Right now the only mention of scoped classes was for targeting the root node, so it wasn't immediately obvious to me that I'd use a bunch of classes in a single `<styled jsx>` and then use something like `classnames` to toggle things on and off.

**Comment by rauchg** [comment]
Yes for sure. This is one way:

```jsx
const Button = (props) => (
  <button className={ 'large' in props && 'large' }>
     <style jsx>{`
        button {
          padding: 20px;
          background: #eee;
          color: #999
        }
        .large {
          padding: 50px
        }
     `}</style>
  </button>
)
```

Inline `style` for overrides is another.

**Comment by rauchg** [comment]
that's if you like the shorthand value-less `large`, otherwise just pass a bool and things are much easier :D

**Comment by rauchg** [comment]
I just realized you could also have a little HOC that converts short-hands to bools:

```jsx
export default withBools(({ large, small, children }) => (
  <button className={large ?  'large' : small ? ' small' : ''}>
    {children}
  </button>
))
```

**Comment by rauchg** [comment]
Added a section describing the two main techniques:
https://github.com/zeit/styled-jsx#dynamic-styles

@ianstormtaylor does it LGTY?

**Comment by ianstormtaylor** [comment]
@rauchg yup that is perfect, thank you!

**Comment by damusnet** [comment]
Hi. Correct me if I'm wrong, but this wouldn't work, unless we use global styles, right?

```javascript
const Button = ({ href, onClick, children }) => {
  const Component = href ? 'a' : 'button';
  const params = href ? { href } : { onClick };
  return (
    <Component
      className="button"
      {...params}
    >
      {children}
      <style jsx>{`
      .button {
        display: block;
        border-radius: 1px;
        width: 100%;
      }
    `}</style>
    </Component>
  );
};
```
