### ISSUE TITLE
css.resolve does not appear to work according to example

### ISSUE THREAD

**Issue by Sakarisson** [zeit/styled-jsx#491]
#### Bug report

The `css.resolve` example in the Next 7 announcement does not appear to pass styles down to child components. 

https://nextjs.org/blog/next-7#styled-jsx-v3

#### What is the current behavior?

Styles to not pass to Child Component as expected

#### To replicate

`npm i -S next react react-dom`

Create this file in /pages/index.js

```javascript
import css from 'styled-jsx/css'

const ChildComponent = ({className}) => <div className={className}>
  <p>This text should have a red background</p>
</div>

const { className, styles } = css.resolve`p { background-color: red }`

export default () => <div>
  <ChildComponent className={className} />
  {styles}
</div>
```

Below is a link to test repository.

 https://github.com/Sakarisson/styled-jsx-resolve-demo

#### What is the expected behavior?

I would expect ChildComponent to get the properties defined in the css.resolve statement.

Instead it doesn't get any CSS passed to it.

#### Environment (include versions)

* OS: MacOS High Sierra 10.13.6
* Browser: Firefox 62.0, Chrome 69.0.3497.100
* styled-jsx (version): 3.0.3-canary.0

**Comment by Yankovsky** [comment]
Same problem

**Comment by giuseppeg** [comment]
sorry there is a mistake in the example. `className` should be set on the `p`:

```jsx
import css from 'styled-jsx/css'

const ChildComponent = ({className}) => <div>
  <p className={className}>This text should have a red background</p>
</div>

const { className, styles } = css.resolve`p { background-color: red }`

export default () => <div>
  <ChildComponent className={className} />
  {styles}
</div>
```

I'll update the blog post. Thank you for reporting this!
