### ISSUE TITLE
The `global` prop is not being honored when importing from .css files

### ISSUE THREAD

**Issue by ryanfitzer** [zeit/styled-jsx#495]
#### Do you want to request a *feature* or report a *bug*?

Bug.

#### What is the current behavior?

The `global` prop is not being honored when importing from .css files as the [docs state](https://github.com/zeit/styled-jsx#styles-in-regular-css-files):

> To consume the styles in your component you can import them from your CSS file and render them using a <style jsx> tag. Remember to add the global prop if you want your styles to be global.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1. Clone example repo from https://github.com/ryanfitzer/styled-jsx-global-prop
2. Run `npm run dev` to start the server.
3. Visit <http://localhost:3000/>
4. The nav in the black outline should have a `red` background instead of white.
5. See line 35 in `components/head.js`: `<style jsx global>{ css }</style>`

#### What is the expected behavior?

The nav in the black outline should have a `red` background.

#### Environment (include versions)

* OS: macOS Sierra v10.12.6
* Browser: Chrome v69.0.3497.100 (Official Build) (64-bit)
* styled-jsx (version): v3.0.3-canary.0 (ships with next v7.0.0

#### Did this work in previous versions?

Feature wasn't available in previous versions.

**Comment by giuseppeg** [comment]
you need to tell the webpack loader to compile those styles as global, in this case you can add a comment at the top of the file `/* @styled-jsx=global */`

More info https://github.com/zeit/styled-jsx#styles-in-regular-css-files

**Comment by ryanfitzer** [comment]
That’s not the issue. The docs state:

> Remember to add the global prop if you want your styles to be global.

Adding a comment to the file or configuring the webpack loader works fine.

Adding the `global` prop does not.

From your response, I’m assuming that the docs have to be updated to say that the `global` prop is useless when importing from regular css files.

**Comment by giuseppeg** [comment]
You need both, mind sending a PR to clarify??

**Comment by ryanfitzer** [comment]
You need both what? Does my example repo not illustrate the bug/docs issue well enough?

**Comment by giuseppeg** [comment]
You need to add the `/* @styled-jsx=global */` comment at the top of the file (head.css) and the `global` prop to the `style` tag `<style jsx global>{ css }</style>` (head.js)

**Comment by giuseppeg** [comment]
> the global prop is useless when importing from regular css files

it is not

**Comment by ryanfitzer** [comment]
What technical aspect the the `global` prop serve? It has no effect from I can see.

Ultimately, the docs regarding the `global` prop in relation to the new feature of importing regular CSS files is misleading/confusing.

I can submit a PR for updating the docs to clarify. Can you give me an understanding as to what the purpose is of the `global` prop in this scenario?

**Comment by giuseppeg** [comment]
That'd be great! styled-jsx transpiles external styles to string objects eg. 

```js
const _defaultExport = new String('div  { color: red }')
_defaultExport.__hash = '123'
export default _defaultExport
```

To each of those objects we also add property called `__hash` that is an hash of the styles. We use it to identify each ruleset, mount and unmount styles, avoid duplicates and in the case of scoped styles to actually scope them eg. rewrite the css string above to`div.jsx-123 { color: red }`

When we detect a `style` tag that has the `jsx` attribute we use this information to add a scoped class to every JSX tag. 

so this:

```jsx
import styles from '../my-external-styles'

export default () => (
   <div> howdy
       <style jsx>{styles}</style>
   </div>
)
```

is transpiled to

```jsx
import JSXStyle from 'styled-jsx/style'
import styles from '../my-external-styles'

export default () => (
   <div className={`jsx-${styles.__hash}`}> howdy
       <JSXStyle styleId={styles.__hash} css={styles} />
   </div>
)
```

In the case of global styles this is not necessary, but we need that `global` prop on the `style` tag to differentiate between the two cases. Hope this is clear enough.
