### ISSUE TITLE
Properly Scoped Styling of Root External Components

### ISSUE THREAD

**Issue by eliasthompson** [zeit/styled-jsx#496]
Hi,

I've run into an issue (and it looks like [I'm not the only one who has](https://github.com/zeit/styled-jsx/issues/197)) where I'm unable to properly use styled-jsx to style the root element of a component if the root element is an external component:

```
import { Link } from 'react-router-dom';

export default function StyledLink(props) {
  return (
    <Link { ...props }>
      <style jsx>{ `
        a {
          color: red;
        }
      ` }</style>
    </Link>
  );
}
```

The easy way to get around this would be to change `a` to `:global(a)`, however that would apply the style to every `a` tag in the DOM instead of just `a` tags generated locally in the scope of this component. Is there any way to do this properly or does this functionality not yet exist?

**Comment by giuseppeg** [comment]
since v3 it is possible to do this https://github.com/zeit/styled-jsx#the-resolve-tag Hope this helps
