### ISSUE TITLE
Member expression not allowed in style tag as <style jsx>{external.styles}</style> ?

### ISSUE THREAD

**Issue by athrunsun** [zeit/styled-jsx#497]
#### Do you want to request a *feature* or report a *bug*?
Report a potential *bug* (I'm not sure if this is a bug or WAD).

#### What is the current behavior?
MemberExpression is not allowed in style tag, e.g. `<style jsx>{external.styles}</style>`.

#### Steps to reproduce

1. I have some external styles in `appStyles.js`.
```javascript
const siderStyles = css`
    .top-column {
        flex: none;
        flex-basis: 5rem;
    }
    .middle-column {
        flex: 1;
    }
    .bottom-column {
        flex: none;
        flex-basis: 6rem;
        align-self: center;
    }
`;

export { siderStyles };
```

2. Now I want to import and use it in a component.
```javascript
import * as appStyles from './appStyles';

class App extends React.Component {
    render() {
        return (
            <React.Fragment>
                <div className="container">
                    <div className="top-column" />
                    <div className="middle-column" />
                    <div className="bottom-column" />
                </div>
                <style jsx>{appStyles.siderStyles}</style>
            </React.Fragment>
        );
    }
}
```

3. After compilation with webpack, I got the following error:
```
Expected a template literal or String literal as the child of the JSX Style tag (eg: <style jsx>{`some css`}</style>), but got MemberExpression
```

#### What is the expected behavior?
I am expecting member expression to work in style tag just fine in this case.

#### Environment (include versions)

- OS: LinuxMint 19
- Browser: Chrome 69
- styled-jsx (version): 3.0.2

#### Did this work in previous versions?
I don't know, this is the first version I tried styled-jsx.

**Comment by giuseppeg** [comment]
Right now they are not supported. You'd need to `import { siderStyles } from './appStyles'`.

Do you want to submit a PR to add support for member expressions? If not I will close this issue as I don't have time to do that :)

**Comment by giuseppeg** [comment]
@athrunsun sorry for the late reply. This is the relevant part https://github.com/zeit/styled-jsx/blob/a9167122eb72a824a866cd9f1bcf45fd50305610/src/babel.js#L108-L122

**Comment by giuseppeg** [comment]
you can use astexplorer.net and https://babeljs.io/docs/en/babel-types to analyze the ast and fix this. You will likely need to check `t.isMemeberExpression(expression)` too and do some work to support those. 

Honestly I think that it'd be easier to just alias or use named imports outside of a components and don't spend time trying to implementing this :) Also because a that point you'd open a can of worms since you'd need so support `foo.bar.baz` etc not just `foo.bar`

**Comment by athrunsun** [comment]
@giuseppeg Ah yes, you're right... Thank you for your explanation, now I understand why member expression support is not implemented, and it does seem not worth the effort.

I'll close this issue.
