### ISSUE TITLE
.foo p + p not process?

### ISSUE THREAD

**Issue by katopz** [zeit/styled-jsx#50]
To reproduce
```js
  render () {
    return (
        <div>
          <dl className="foo">
            <style jsx>{`
              .foo {
                color: red; 
              }
              .foo p {
                color: green; 
              }
              .foo p + p {
                color: blue; 
              }
              `}
            </style>
            red<p>green</p><p>blue</p>
          </dl>
        </div>
    )
  }
```

`Preact` (Working)
![screen shot 2016-12-22 at 18 10 29](https://cloud.githubusercontent.com/assets/97060/21423950/5a77e192-c872-11e6-9a95-063e4f5bbbeb.png)

`React` via https://github.com/zeit/next.js/commit/cae706d7b76f8e13e47854df54c0cf5161f8dc86 (Not working)
![screen shot 2016-12-22 at 18 10 19](https://cloud.githubusercontent.com/assets/97060/21423960/6a91a838-c872-11e6-808d-7e14886364be.png)

Also sometime hot reload refuse to process CSS (all appear no colour just black) and will need full refresh.
Is it a bug? Thanks.

**Comment by katopz** [comment]
@rauchg Thanks. It's work now but maybe it's not cover this case?

```js
// Bar.js
export default () =>
<div>
	<dd className='bar'>
		red<p>green</p><p>blue</p>
	</dd>
</div>;
```
```js
// Foo.js
import React from 'react'
import Bar from './Bar'

export default Foo => {
	return (
		<div>
			<dl className="foo">
				<style jsx>{`
					.foo {
						color: red; 
					}
					.foo p {
						color: green; 
					}
					.foo p + p {
						color: blue; 
					}
					`}
				</style>
				red<p>green</p><p>blue</p>
				{
					[0,1,2].map(item => <Bar key={item}/>)
				}
			</dl>
		</div>
	)
};
```
Expected
![screen shot 2016-12-24 at 22 39 18](https://cloud.githubusercontent.com/assets/97060/21467714/42ba80b4-ca2a-11e6-959e-0a00ab9f8088.png)

But get
![screen shot 2016-12-24 at 22 39 02](https://cloud.githubusercontent.com/assets/97060/21467717/4aaeecce-ca2a-11e6-98b7-9173b2242739.png)

Do tell me if I need to open new issue.

Thanks

**Comment by nkzawa** [comment]
@katopz that'a bit different issue, see https://github.com/zeit/styled-jsx/issues/42
