### ISSUE TITLE
snapshot format for style is weird

### ISSUE THREAD

**Issue by oahehc** [zeit/styled-jsx#502]
#### Do you want to request a *feature* or report a *bug*?
bug

#### What is the current behavior?
the snapshot for style should be a string, but be formatted as an object.
![image](https://user-images.githubusercontent.com/13633490/46568765-301b7180-c97d-11e8-9777-13d0168fcc66.png)

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

1. use [with-jest](https://github.com/zeit/next.js/tree/canary/examples/with-jest) example
2. split style to `styles.js` and adjust pages/index.js as below
```
import styles from './style';

export default () => (
  <div>
    <p>Hello World!</p>
    <style jsx>{styles}</style>
  </div>
)

```
3. use enzyme for snapshot test
```
const app = shallow(<App />)
expect(app).toMatchSnapshot()
```

#### What is the expected behavior?
originally, the snapshot for style should be a string as below
![image](https://user-images.githubusercontent.com/13633490/46568800-c3ed3d80-c97d-11e8-91a8-24de06663b34.png)

#### Environment (include versions)

* OS: macOS
* styled-jsx (version): 3.0.2

#### Did this work in previous versions?
no, roll back to the previous version unable to fix this problem.

**Comment by giuseppeg** [comment]
we don't have an official serializer for styled-jsx. Usually I recommend to not use styled-jsx in tests, after all you don't need to test that styled-jsx works. See https://github.com/zeit/styled-jsx#rendering-in-tests and mock `styled-jsx/css`

**Comment by oahehc** [comment]
I try to use `styled-jsx/babel-test`, but unable to remove style.
![image](https://user-images.githubusercontent.com/13633490/46583139-76a7c380-ca84-11e8-82d1-12297c430b0e.png)

**Comment by oahehc** [comment]
create a [repo](https://github.com/oahehc/jest-snapshot-test/tree/master) to reproduce this error, I think this start at next 7.

In my project, apply [babel-test](https://github.com/zeit/styled-jsx#rendering-in-tests) is not able to solve the problem.

One solution is to follow (with-jest)[https://github.com/zeit/next.js/tree/canary/examples/with-jest] example, use `react-test-renderer` for snapshot test rather than `enzyme`.

But hope someone can help to find the root cause, or provide some idea for me to dig deeper, thanks.

**Comment by Darep** [comment]
We're also running into this problem while upgrading to Next.js 7 😄 Basically the snapshots change into these "monsters" :joy: with crazy amount of lines as there's a newline after each character inside JSXStyle:

![image](https://user-images.githubusercontent.com/218910/53627863-3a7f2600-3c12-11e9-81a3-2327bf4d264f.png)

next/babel preset seems to force(?) styled-jsx/babel into the mix and adding styled-jsx/babel-test into babelrc or babel.config.js doesn't seem to fix this. There's another person wondering about this also: https://github.com/zeit/next.js/issues/6205 – might make sense to move discussion there as?

**Comment by Darep** [comment]
@giuseppeg Thanks for the tip on the other issue 😊 

I managed to add styled-jsx/babel-test to plugins, though I still get the [weird snapshot](https://user-images.githubusercontent.com/218910/53640111-ed13b080-3c33-11e9-96c3-d38cde1a9884.png) where each character is on their own line, it's just now a `<style>`-element instead of `<JSXStyle>` o_O Not sure if this is caused by styled-jsx at this point...

Anyways, I made a separate repo for this, if anyone happens to have interest in this 😊 I will be trying to figure this out on that repo at least!

https://github.com/Darep/next-js-styled-jsx-jest-snapshot

```
git clone https://github.com/Darep/next-js-styled-jsx-jest-snapshot.git
cd next-js-styled-jsx-jest-snapshot
```

Run tests with Next.js 7 in master branch and see strange snapshots:

```
git checkout master
rm -rf node_modules && yarn && yarn test --no-cache
```

Run tests with Next.js 6 and tests pass with the older, sensible snapshot:

```
git checkout next6
rm -rf node_modules && yarn && yarn test --no-cache
```

(sorry for yarn...)

**Comment by Darep** [comment]
I forced Next.js 6 to use styled-jsx@3.0.0 and that seems to break the snapshot test in this weird way: https://github.com/Darep/next-js-styled-jsx-jest-snapshot/commit/1c39d0abc6a75eb773717b00dbee18149c3d9695

...so not Next.js version specific, just the styled-jsx 3.0.0 changes breaking our snapshots in this way 🤔

**Comment by Darep** [comment]
Tried to get .babelrc + styled-jsx/babel-test + Next.js working, but I wasn't successful (for now) 😄 Unfortunately in a bit of a hurry here, so gonna take the quick route for now and apply a dirty patch for styled-jsx/babel.js for our project

Patch here in the example repo: https://github.com/Darep/next-js-styled-jsx-jest-snapshot/commit/038660e461271eb13aa3bbf22efda9dbe5357f5f

This enables babel-test in test env and all the `<JSXStyle>`s get replaced with empty `<style />` and still seems to work fine in dev (and prod) for us :)
