### ISSUE TITLE
CSS URL being escaped when rendering server-side in Next.js

### ISSUE THREAD

**Issue by EiZei** [zeit/styled-jsx#505]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behavior?

When using a styled jsx element like this:
```
<style jsx="true">{`
          .tag-list__background {
            background-image: url("http://foo.bar?buz=bax");
          }
        `}</style>
```

The server-side css is url escaped but the client-side css is not resulting in this error:
```
index.js:2178 Warning: Text content did not match. Server: "
          .tag-list__background {
            background-image: url(&quot;http://foo.bar?buz=bax&quot;);
          }
        " Client: "
          .tag-list__background {
            background-image: url("http://foo.bar?buz=bax");
          }
        "
```

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

See above.

#### What is the expected behavior?

The url is not escaped I guess?

#### Environment (include versions)

* OS: MacOs 10.14
* Browser: Chrome 69
* styled-jsx (version): 3.1.0, Babel 7.1.0, next 7.0.1 and typescript 3.0.3

#### Did this work in previous versions?

First time trying this library.

**Comment by giuseppeg** [comment]
Hi this might be a bug in Stylis, the css processor we use to scope selectors. Can you report the issue to them https://github.com/thysultan/stylis.js ?
