### ISSUE TITLE
CSS grid-template-areas causing "text content did not match" error

### ISSUE THREAD

**Issue by jasonbarone** [zeit/styled-jsx#508]
Hello, looks like grid-template-areas trigger an error on styled-jsx.

#### What is the current behavior?
Using code like this inside of styled-jsx:
```
grid-template-areas: "one two three four";
```

Results in this:
<img width="597" alt="screen shot 2018-10-20 at 9 33 07 pm" src="https://user-images.githubusercontent.com/545055/47263109-c12b3600-d4af-11e8-9f3d-c9bef0a07b43.png">

#### Environment (include versions)
* styled-jsx 3.1.0:

**Comment by giuseppeg** [comment]
can that be an issue with Next? Can you put a testcase together?

**Comment by themagickoala** [comment]
Is there any chance this can be reopened? I'm having the same issue using Next.js and it's causing a flash of unstyled content on load.
