### ISSUE TITLE
`flush()` will include extra styles server side if server is hosting multiple client side apps

### ISSUE THREAD

**Issue by jwalton** [zeit/styled-jsx#512]
---

#### What is the current behavior?

Calling into [`flushToReact()`](https://github.com/zeit/styled-jsx/blob/a9167122eb72a824a866cd9f1bcf45fd50305610/src/server.js#L4) or `flushToHtml()` server side will call into [`flush()`](https://github.com/zeit/styled-jsx/blob/master/src/style.js#L51-L55) which will retrieve all styles from the [`styleSheetRegistry` global variable](https://github.com/zeit/styled-jsx/blob/master/src/style.js#L4).

Global variables are bad.

In my app, I have two distinct UIs; a client-facing UI for end-users, and a manager-facing UI.  These are two separate react apps (I have these in two separate private npm packages), but they are both run from the same node.js process, which routes requests to one or the other based on the URL (so visiting "/" will get you the client-facing UI, and visiting "/manager" will get you the manager UI).

However, since styled-jsx relies on this single `styleSheetRegistry` global variable, styles from one project will cross-contaminate the other - I'll get client styles in my manager UI, and vice versa, which wastes precious bytes.

#### What is the expected behavior?

styled-jsx should probably use the [React Context API](https://reactjs.org/docs/context.html).  Clients can write server side code that looks something like:

```js
import React from 'react'
import ReactDOM from 'react-dom/server'
import { flush, StyleSheetRegistry, StyledProvider } from 'styled-jsx/server'
import App from './app'

// Create a styleSheetRegistry for this app.
const styleSheetRegistry = new StyleSheetRegistry();

export default (req, res) => {
  const app = ReactDOM.renderToString(
    <StyledProvider styleSheetRegistry={styleSheetRegistry}>
      <App />
    </StyledProvider>
  )
  const styles = flush(styleSheetRegistry)
  const html = ReactDOM.renderToStaticMarkup(<html>
    <head>{ styles }</head>
    <body>
      <div id="root" dangerouslySetInnerHTML={{__html: app}} />
    </body>
  </html>)
  res.end('<!doctype html>' + html)
}
```

Which allows the client to specify a styleSheetRegistry to cache styles in, eliminating the single global variable.

**Comment by jwalton** [comment]
Should be possible to do this as a non-breaking change even - try to fetch the styleSheetRegistry from the context, if it isn't there, fall back to the global one.

**Comment by jwalton** [comment]
I just started looking into `styled-components`, and they solve this problem [exactly like I described](https://www.styled-components.com/docs/advanced#server-side-rendering).  :)

**Comment by giuseppeg** [comment]
yup we already had an issue for this https://github.com/zeit/styled-jsx/issues/64 would you like to give a stab at it? I won’t have time in the near future
