### ISSUE TITLE
Imported constants used in `styled-jsx` template strings are not defined in Jest, after upgrading to Babel 7.

### ISSUE THREAD

**Issue by nschomberg** [zeit/styled-jsx#516]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What is the current behavior?

After upgrading to Babel 7 (via [`babel-upgrade`](https://github.com/babel/babel-upgrade)), imported constants used in `styled-jsx` template strings are not defined in Jest.

>    ReferenceError: color is not defined

      11 |           {`
      12 |             div {
    > 13 |               color: ${color};
      14 |             }
      15 |           `}
      16 |         </style>

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

https://github.com/nschomberg/styled-jsx-issue-repro

#### What is the expected behavior?

The expected behavior is the imported constant gets resolved correctly and the unit test passes.

#### Environment (include versions)

* OS: Mac OS High Sierra
* Browser: Jest/JSDom
* Node: 8.11.1
* styled-jsx (version): 2.2.6 and 3.1.0

#### Did this work in previous versions?

This worked before upgrading Babel (see [here](https://github.com/nschomberg/styled-jsx-issue-repro/commit/2e972d0678d5dbce88b93a2c9b47e0b8eb2197c3) for working unit test)

**Comment by giuseppeg** [comment]
You might want to remove styled-jsx when running tests https://github.com/zeit/styled-jsx#rendering-in-tests

**Comment by nschomberg** [comment]
Thanks, this fixes the issue!

It also changes the output of our snapshot tests. Instead of adding a `jsx-` class to each element, it adds the generated CSS. I like this new behavior better, but updating every Jest snapshot is a big migration for our codebase.

Just curious, is there a way to fix the issue without changing our snapshots?

**Comment by giuseppeg** [comment]
This might be an issue with how styled-jsx transforms your code, probably it reuses nodes and when babel-jest rewrites the imports then it fails at rewriting the references. At some point I hope to have the time to migrate to Babel 7. I believe that will fix your issue.

Relates to #486

**Comment by nschomberg** [comment]
Thanks for the explanation. I'll stay tuned!

**Comment by giuseppeg** [comment]
hi this should be fixed in the latest version
