### ISSUE TITLE
Dot notation for external styles do not work

### ISSUE THREAD

**Issue by ssylvia** [zeit/styled-jsx#517]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behavior?
Using dot notation of variable within a style tag throws the following error in compile:

```
Expected a template literal or String literal as the child of the JSX Style tag (eg: <style jsx>{`some css`}</style>), but got MemberExpression
```

when using this:

```
import React, { Component } from 'react';
import Themes from './';

export interface Props {
  title: string;
}

export class SampleComponent extends Component<Props> {
  constructor(props: Props) {
    super(props);
  }

  public render() {
    return (
      <div>
        {this.props.children}
        <style jsx global>
          {Themes.darkTheme}
        </style>
      </div>
    );
  }
}

export default SampleComponent;

```

This works:

```
const darkTheme = Themes.darkTheme;

... 

<style jsx global>
  {darkTheme}
</style>
```

Themes exports

```
import css from 'styled-jsx/css';

export defaults {
  lightTheme: css.global`...`
  darkTheme: css.global`...`
}
```

but this doesn't:

```
<style jsx global>
  {Themes.darkTheme}
</style>
```

#### What is the expected behavior?
Should be able to use dot notation to get variable of styles.

#### Environment (include versions)

* OS: Mac Mojave
* Browser: na
* styled-jsx (version): 3.1.0

**Comment by giuseppeg** [comment]
yep that's on purpose to keep it simple and avoid edge cases :) You can use your solution or even use named exports/imports
