### ISSUE TITLE
Plugin Logging Causes Invalid Webpack JSON Profile

### ISSUE THREAD

**Issue by eliasthompson** [zeit/styled-jsx#520]
Webpack has a nice feature that allows you to generate a JSON file of your app structure that tools can use to analyze your app for chunking and such. When I run `webpack --profile --json > ./stats.json` to export a stats file to analyze in a tool, the JSON file is invalid because `[styled-jsx] Loading plugin from path: styled-jsx-plugin-sass` is printed at the top of the file. Only after manually opening the file and removed the log does the JSON become valid.

Is there a way to exclude this log from webpack JSON profiling or otherwise insert it to make it the file valid JSON?

**Comment by giuseppeg** [comment]
🤔 interesting, I can't believe that this is the first module that prints a message to the console. Maybe we can only print the message when `process.env.NODE_ENV === 'development'` would that help?

**Comment by eliasthompson** [comment]
I usually prepend the analysis command with `NODE_ENV=production `, so that would definitely help me, but I'm not sure if that command always generates a production bundle regardless, if `rocess.env.NODE_ENV !== 'production'` would be better, or how any other potentially console printing packages handle that Webpack feature, if they do at all.

**Comment by morinted** [comment]
Hi, I'm running into this issue when generating a profile. Is it possible to implement it so that under NODE_ENV==='production' omits the log?
