### ISSUE TITLE
Scoping is Intermittently Missing from `<style jsx>` Tags

### ISSUE THREAD

**Issue by ryanfitzer** [zeit/styled-jsx#524]
#### Do you want to request a *feature* or report a *bug*?

Bug.

#### What is the current behavior?

Scoping is intermittently missing from `<style jsx>` tags. It happens in both `development` and `production` and irrespective of SSR vs. client-side rendering. Hard refreshes do not fix the issue (server restart does fix it, until it happens again).

The `.css` is `import`ed via the `styled-jsx/webpack` `loader` in `next.config.js` file. Not sure if that is a contributor to the problem.

I searched the issues and haven't found any other reports is this behavior. Any advice on how to debug this would be much appreciated.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

Still haven't found a way to reliably reproduce the issue. Also not sure if it is a Next.js issue or `styled-jsx` issue.

#### What is the expected behavior?

CSS is consistently scoped. 

#### Environment (include versions)

* OS: macOS >= 10.12.6
* Browser: Chrome Version 70.0.3538.77
* styled-jsx (version): 3.1.0 (via Next.js v7.0.1)

#### Did this work in previous versions?

I never saw this issue in Next.js <= `6.x.x` (`styled-jsx` <= `2.x.x`?), but `import`ing `.css` files was not an option in previous versions.

**Comment by ryanfitzer** [comment]
(Adding more info as I come across it)

The issue just showed up again. Here's what I observed:

- Issue first showed during client-side navigation and remained after a hard-refresh (un-scoped css shows in both the dev tools *Elements* panel and when viewing the page source via `⌘U`)

- Scoping is missing for:
  - All `.css` files imported into the page (`pages/name/index.js`).
  - Multiple child components that the page imports (but not all of them).
  - Only one `.css` file of the two imported by a particular child component. The other imported `.css` is properly scoped.

**Comment by giuseppeg** [comment]
thanks Ryan! I have 0 to little time to work on styled-jsx recently so if you can put together a test case I can take a look

**Comment by ryanfitzer** [comment]
@giuseppeg Totally understand. I'll put a test case up once I can pin down the cause and reproduce it reliably.

We have found that this issue is related to using the option comment `/* styled-jsx=global */`. When this comment is present in any `.css` file, it seems to cause other files to also have the same option. So far, we have not been able to pin down what relationship the affected files share with the files that contain the comment. But removing all the comments and instead using the `:global()` function fixes the issue.

**Comment by ryanfitzer** [comment]
I'm closing this since we were never able to track down, or reliably able to reproduce the issue.

**Comment by giuseppeg** [comment]
@ryanfitzer hey thanks for the update and sorry if I couldn't help - unfortunately atm I don't have a lot of time or energy to invest on the project after work
