### ISSUE TITLE
Can use variable with styles in it

### ISSUE THREAD

**Issue by hipstersmoothie** [zeit/styled-jsx#527]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What is the current behavior?

Can't get css stored in a variable to work correctly. I would expect to to be inserted as normal. I am using `babel-plugin-inline-import` to import my css as strings.

Just the style block:
```ts
export const Button: React.FC<IButtonProps> = ({ children, size, color }) => {
  const buttonClass = makeClass('button', `is-${color}`, {
    'is-large': size === 'large'
  });

  return (
    <React.Fragment>
      <button className={buttonClass}>{children}</button>
      <style jsx>{`
          ${css}
      `}</style>
    </React.Fragment>
  );
};

Button.defaultProps = {
  size: 'medium'
};
```

Using css.resolve. still no dice
```ts
export const Button: React.FC<IButtonProps> = ({ children, size, color }) => {
  const { styles, className } = styled.resolve`
    ${css}
  `;
  const buttonClass = makeClass(className, 'button', `is-${color}`, {
    'is-large': size === 'large'
  });

  console.log(styles);

  return (
    <React.Fragment>
      <button className={buttonClass}>{children}</button>
      {styles}
    </React.Fragment>
  );
};
```

#### What is the expected behavior?

Should work?

#### Environment (include versions)

* OS: mac 10.13.6
* Browser: Chrome
* styled-jsx (version): 3.1.2

#### Did this work in previous versions?

Probably not (IDK)

# More

It's really super close. 

if I do:

```js
<style jsx>{`
   * ${css}
`}</style>
```

Then the css is in the style tag but not as a correct rule

<img width="502" alt="screen shot 2018-11-20 at 12 48 35 am" src="https://user-images.githubusercontent.com/1192452/48761676-16e53080-ec5e-11e8-8700-12526b1a6fee.png">

**Comment by hipstersmoothie** [comment]
Even simper:

```js
const css = "button { background-red; }"

const Button = () => (
  <>
    <button>foo</button>
    <style jsx>{css}</style>
  </>
)
```

**Comment by giuseppeg** [comment]
Interpolations are not transpiled or scoped so the following is not scoped:

```js
css.resolve`
    ${css}
`
```

This should work:
```
const styles = css`button { background-red; }`

const Button = () => (
  <React.Fragment>
    <button>foo</button>
    <style jsx>{styles}</style>
  </React.Fragment>
)
```
 but I assume you don't have the styles inline like that. `</>` is not yet supported. 

If you want to load CSS from files you can use our webpack loader see https://github.com/zeit/styled-jsx#styles-in-regular-css-files
