### ISSUE TITLE
extra div to override children style?

### ISSUE THREAD

**Issue by thian4** [zeit/styled-jsx#528]
I have a common button component
```export const MyButton = () => <div><button>{children}</button><style jsx>{`button{color: black}`}</style></div>```

Then when I use it I have to wrap it with a div to override the children's style
```<div className="confirmBtn"><MyButton>Confirm</MyButton><style jsx>{`.confirmBtn { color: red }`}</style></div>```

Any better way to solve this? I can't override the style by passing class like ```<MyButton className="confirmBtn" />```

**Comment by giuseppeg** [comment]
if you are using styled-jsx v3 you can do this:

```jsx
export const MyButton = ({ children, className }) => (
  <button className={className}>
    <style jsx>{`button { color: black }`}</style>
    {children}
  </button>
)

// ...

const overrides = css.resolve`
  button {
    color: red
  }
`

<MyButton className={overrides.className}>
  Confirm
  {overrides.styles}
</MyButton>
```

hope this helps
