### ISSUE TITLE
Styles minification

### ISSUE THREAD

**Issue by royeeshemesh** [zeit/styled-jsx#529]
Hi guys!

I'm trying to understand if any of the `sytled-jsx` should be minified for production and I can't find any good answer.

I see the exact (long) names for all of my selectors in the global head tag when I deploy to production (using Next.js next-build command).

What am I missing here?

Thanks!

**Comment by giuseppeg** [comment]
Hi Royee! Nope styled-jsx doesn't minify CSS. I don't think that Next.js does that eitherr
