### ISSUE TITLE
Document using styled-jsx with TypeScript

### ISSUE THREAD

**Issue by rgbkrk** [zeit/styled-jsx#532]
How should typescript users be working with styled-jsx? There are a bunch of closed issues, all which point to #90 (which is also closed). I'd love to see some documentation in the README that outlines what TypeScript developers should be using.

Questions I'd love to have answered:

* Are we required to use typescript through babel (so the styled-jsx transform happens)?
* If we're in a full `tsc` setup, are there explicit calls we should use with styled-jsx directly (all the stylesheet creation steps, etc.)?

**Comment by rgbkrk** [comment]
@DanielRosenwasser -- would you see a way ahead for using styled-jsx in typescript? It uses a babel transform, comes as a built in within [next.js](https://github.com/zeit/next.js). Ideally, we'd like to be on `tsc` proper without using the typescript babel setup, though we'd still need some sort of hook to happen here.

**Comment by giuseppeg** [comment]
if you can [skip jsx transpilation](
https://github.com/zeit/styled-jsx/issues/90#issuecomment-386913263) probably you can run tsc first and then Babel with styled-jsx. Would tha work? I’ve never used TypeScript so I am afraid I can’t be of much help here

**Comment by rgbkrk** [comment]
I guess that means we'd be having babel do both the react and styled-jsx portions at that point. I'm unsure we want to do that as an extra build process, especially since we have multiple components in different packages across a monorepo.

**Comment by DanielRosenwasser** [comment]
Hey all, I'm not familiar with the exact workflow here but Babel is definitely an option if there's a custom build step involved. Alternatively one could build a transform for TypeScript as well, but that's not usable from plain `tsc` right now. It *would*, however, usable from ts-loader. Not sure if that helps.

**Comment by DanielRosenwasser** [comment]
CC @weswigham for exposing transforms in tsc.

**Comment by rgbkrk** [comment]
We're not running into type definition issues with styled-jsx. The main issue is figuring out how we should rewrite our current suite of styled-jsx backed components and apps (ref:  https://github.com/nteract/nteract/issues/3849) when we're relying on `tsc`.

Would there be a way for us to use the `JSXStyle` element directly, computing our `styleId`:

```
import Style from "styled-jsx/style";

export const Cell = props => {
  const children = props.children;
  const styleId = generateIdFromSomewhere();

  const jsxClassName = `.jsx-${styleId}`;

  return (
    <div
      className={`${jsxClassName} cell ${props.isSelected ? "focused" : ""} ${
        props._hovered ? "overrideHover" : ""
      }`}
    >
      <Style
        styleId={styleId}
        // Somehow we'd need to create this css using styled-jsx directly
        css={`
          .cell${jsxClassName} {
            position: relative;
            background: var(--theme-cell-bg, white);
            transition: all 0.1s ease-in-out;
          }
          ...more
        `}
      />
      {children}
    </div>
  );
};
```

**Comment by giuseppeg** [comment]
yes you could do that. `styleId` is an hash of the css string. In production you should pass an array of rules to `css` to get all the optimizations.

**Comment by rgbkrk** [comment]
It turned out to be much easier for us to switch over to `styled-components`, so we've done just that. Thanks for `styled-jsx` over the last couple years!

**Comment by zkimyes** [comment]
@types/styled-jsx.d.ts 

import 'react';

declare module 'react' {
  interface StyleHTMLAttributes<T> extends HTMLAttributes<T> {
    jsx?: boolean;
    global?: boolean;
  }
}
