### ISSUE TITLE
styled-jsx/babel-test in combination with styled-jsx/css

### ISSUE THREAD

**Issue by klaemo** [zeit/styled-jsx#537]
Hey there!
Thank you for your work on styled-jsx :)

#### Do you want to request a *feature* or report a *bug*?
bug

#### What is the current behavior?
When using `styled-jsx/babel-test`, `styled-jsx/css` throws the following error:

```
styled-jsx/css: if you are getting this error it means that your `css` tagged template literals were not transpiled.
```

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

I tried to setup a minimal test case here:
https://github.com/klaemo/styled-jsx-bug

Basically this pattern doesn't seem to work when using the babel-test plugin.
```jsx
const React = require('react')
const css = require('styled-jsx/css')

const styles = css`
  p {
    color: red;
  }
`

module.exports = () => (
  <div>
    <p>only this paragraph will get the style :)</p>

    <style jsx>{styles}</style>
  </div>
)
```

#### What is the expected behavior?
I was expecting to be able to use `styled-jsx/babel-test` during tests while also leveraging the advanced features of `styled-jsx/css`.

#### Environment (include versions)

* OS: macOS
* Browser:
* styled-jsx (version): 3.1.3

#### Did this work in previous versions?

I don't know

**Comment by giuseppeg** [comment]
@klaemo hi! You should mock that module. See https://kevinjalbert.com/jest-snapshots-reducing-styled-jsx-noise/
https://github.com/zeit/styled-jsx/issues/469#issuecomment-423243758
https://github.com/zeit/styled-jsx/issues/434#issuecomment-415801021

**Comment by antoniojps** [comment]
Since my solution is a little different to whats reffered [in this article ](https://kevinjalbert.com/jest-snapshots-reducing-styled-jsx-noise/)I will leave it here since it might help someone else.

To solve this I had to create a `__mocks__/styled-jsx/css.js` file with the following (this is whats different):
```js
export default {
  resolve: () => ({ className: '', styles: '' }),
  global: () => '',
};

```

The solution provided in the article did not work, while that did.
