### ISSUE TITLE
v3.1.3 throws TypeError in Storyshots

### ISSUE THREAD

**Issue by ssylvia** [zeit/styled-jsx#538]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What is the current behavior?

All storyshots render to JSON as expected (v3.1.2)

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

Run `yarn test` with Jest and storyshots addon to Storybook

Produces the following type error on every storyshot that includes styled-jsx:

<img width="1091" alt="screen shot 2019-01-10 at 3 18 40 pm" src="https://user-images.githubusercontent.com/1211360/51003440-a33c0300-14eb-11e9-9d46-452ce5218861.png">

Only change was updating styled-jsx from `3.1.2` to `3.1.3`.

#### What is the expected behavior?

Render snapshot without failing

#### Environment (include versions)

* OS: MacOS
* Browser: Node (Jest)
* styled-jsx (version): 3.1.3

#### Did this work in previous versions?
Yes, it works as expected in v3.1.2

**Comment by giuseppeg** [comment]
Hi @ssylvia sorry but I am not familiar with Storyshots. Can you put together a sample repo that I can clone and try out? By the way we recommend to not include styled-jsx in test environments see https://github.com/zeit/styled-jsx#rendering-in-tests

**Comment by ssylvia** [comment]
@giuseppeg Is there a way to disable styled-jsx in tests when using the `next/babel` preset?

**Comment by giuseppeg** [comment]
@ssylvia you need to filter the preset plugins. This is how a preset looks like https://babeljs.io/docs/en/presets#creating-a-preset
