### ISSUE TITLE
Issue when using Spread Operator in JSX

### ISSUE THREAD

**Issue by samholmes** [zeit/styled-jsx#539]
There seems to be an issue with spread props and style-jsx:

```jsx
const Home = () => (
  <div>
    <div {...{ id: 'foo' }}>test</div>

    <style jsx>{`
      #foo {
        background: blue;
      }
    `}</style>
  </div>
)

export default Home
```

Gives an error:

```
./pages/index.js
Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
TypeError: Cannot read property '0' of null
```

The only fix for this bug is to remove the `<style jsx>` element altogether.

Related: https://github.com/zeit/next.js/issues/6057

**Comment by giuseppeg** [comment]
Yeah this is an edge case. Would you like to make a PR?

**Comment by samholmes** [comment]
I’d love to however I’m not familiar enough with the code base to begin to understand what the issue could be. Any thoughts?

**Comment by doniyor2109** [comment]
@giuseppeg Hi. Can I take this issue?

**Comment by AnatoleLucet** [comment]
I found something that is probably related.

When you spread an object returned by a function, the prop `className` is overwritten.

I made an example:
https://codesandbox.io/s/nifty-jennings-dl164?file=/pages/index.js

If you inspect the div, you'll see that it doesn't have the class `my-class`.
