### ISSUE TITLE
Prettier doesn't work in `css.global` or `css.resolve`

### ISSUE THREAD

**Issue by robertu7** [zeit/styled-jsx#548]
#### Do you want to request a *feature* or report a *bug*?
bug

#### What is the current behavior?
`css.global` or `css.resolve` wrapped CSS cannot be formatted with Prettier, only `css` wrapped's work.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

```ts
// styles.global.ts

const globalStyles = css.global`
  html {font-size: 14px;}
`

export default globalStyles
```
```tsx
import Head from 'next/head'

import globalStyles from './styles.global'

export const Layout: React.SFC = ({ children }) => (
  <main>
    <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta charSet="utf-8" />
    </Head>

    <style jsx global>
      {globalStyles}
    </style>

    {children}
  </main>
)

```

#### What is the expected behavior?
```ts
// styles.global.ts

const globalStyles = css.global`
  html {
    font-size: 16px;
  }
`

export default globalStyles
```

#### Environment (include versions)

* styled-jsx (version): 3.2.0
* prettier (version): 1.16.4

#### Did this work in previous versions?
`null`

**Comment by RoberMac** [comment]
I used [CSS Preprocessing via Plugins](https://github.com/zeit/styled-jsx#css-preprocessing-via-plugins) for temporarily fix formatting issue. :)

**Comment by giuseppeg** [comment]
yup somebody should submit a PR to Prettier to add support for these :)

**Comment by hongrich** [comment]
This should be fixed with https://github.com/prettier/prettier/pull/6089
