### ISSUE TITLE
Upgrading to 3.1.3 throws error in snapshot tests

### ISSUE THREAD

**Issue by ssylvia** [zeit/styled-jsx#553]
#### Do you want to request a *feature* or report a *bug*?*
Bug

#### What is the current behavior?
Snapshots test in jest throw the following errors when upgrading to v3.1.3:

https://github.com/ssylvia/styled-jsx-snapshots/blob/master/test-output.md

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

Sample Repo:
https://github.com/ssylvia/styled-jsx-snapshots

Also tried the following fixes:
- Deleting `node_modules` and reinstalling npm packages. 
- Deleting all snapshot tests and recreating all snapshots with new version
- `yarn test --no-cache` (fixes StyleSheetRegistry: styleId: `jsx-undefined` not found. issue)

#### What is the expected behavior?

All snapshots render without error

#### Environment (include versions)

* OS: Mac OS 10.14.3
* Browser: Node 10.13.0
* styled-jsx (version): 3.1.3 (first affected version) still present in 3.2.1

#### Did this work in previous versions?
Yes, everything worked as of 3.1.2

This is related to #538 (now with sample repo)

**Comment by ssylvia** [comment]
@NathanielHill Seems like this may be related to your comment here: https://github.com/zeit/styled-jsx/issues/542#issuecomment-460483781.

**Comment by ijjk** [comment]
@ssylvia I just tried cloning your sample repo and running `yarn test --verbose` from `test-output.md` and I'm not getting any of the errors shown. Let me know if I'm missing a step or something and I can try again. 

Steps I took to try reproducing:
```sh
git clone https://github.com/ssylvia/styled-jsx-snapshots
cd styled-jsx-snapshots
yarn
yarn test --verbose
```

I also tried deleting the snapshots and re-running the command and it still appears to run ok.

I tested it with:
- OS mac OS 10.14.3
- yarn v1.12.3 and v1.13.0
- node v8.11.1 and v10.15.1 and v11.9.0

I get the below output. I also attached [the snapshot](https://github.com/zeit/styled-jsx/files/2863431/storyshots.test.js.snap.txt) which appears to be correct also. 

```sh
yarn test --verbose                                   
yarn run v1.13.0
$ jest --verbose
 PASS  src/components/Button/index.test.tsx
  Button
    ✓ Button handles click (43ms)

 PASS  src/storyshots.test.js
  Storyshots
    Button
      ✓ with text (27ms)
    IconClose
      ✓ Default (4ms)
      ✓ With Class (2ms)
      ✓ With Color (1ms)
      ✓ With a11y Title (2ms)
    IconSearch
      ✓ Default (2ms)
      ✓ With Class (1ms)
      ✓ With Color (2ms)
      ✓ With a11y Title (1ms)
    SearchBox
      ✓ Default (4ms)

Test Suites: 2 passed, 2 total
Tests:       11 passed, 11 total
Snapshots:   10 passed, 10 total
Time:        2.662s
Ran all test suites.
✨  Done in 4.17s.
```

**Comment by ssylvia** [comment]
@ijjk Thanks for helping debug. I just tried this again on a clean clone of the repo and think I have steps to reproduce. It looks like there might be some bug happing with something stuck in the `styled-jsx` cache.

**Steps to repoduce**

1. `git clone https://github.com/ssylvia/styled-jsx-snapshots`
2. `cd styled-jsx-snapshots`
3. Change line 40 in package.json from "next/styled-jsx": "3.1.3" to "next/styled-jsx": "3.1.2"
4. `yarn install`
5. `yarn test --verbose`
3. Change line 40 in package.json back to "next/styled-jsx": "3.1.3" from "next/styled-jsx": "3.1.2"
4. `yarn install`
5. `yarn test --verbose`

**Comment by ijjk** [comment]
@ssylvia changing the `next/styled-jsx` resolution version between `3.1.2` and `3.1.3` after running a test got the errors. This appears to be due to `jest`'s caching and not `styled-jsx`'s since `styled-jsx` does not keep a persistent cache of its own. 

I would recommend running `yarn jest --clearCache` while in the project directory after changing a package version.
