### ISSUE TITLE
Problem in setting up styled-jsx

### ISSUE THREAD

**Issue by danielsimao** [zeit/styled-jsx#555]
Hi, I couldn't find anything related to my problem so here we go. I just installed the module and I'm not able to fix the following problem.

version : "styled-jsx": "^3.2.1"

Line 34:  Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?

**Comment by ijjk** [comment]
This isn't a `styled-jsx` error, it is a JSX error. See [here](https://stackoverflow.com/a/33385872) for more info. Also, note `<></>` is just shorthand for `<React.Fragment></React.Fragment>`

**Comment by giuseppeg** [comment]
If you are using it with Next.js then you need to
