### ISSUE TITLE
"Cannot read property 'name' of undefined" error from isStyledJsx in _utils.js

### ISSUE THREAD

**Issue by TxHawks** [zeit/styled-jsx#556]
#### Do you want to request a *feature* or report a *bug*?
Report a bug

#### What is the current behavior?
When using Next 8.0.1 and styled-js 3.2.1 (installed as a next dependency), I get a `Cannot read property 'name' of undefined` TypeError in `_utils.js`.  This only happens when also using [`next-transpile-modules`](https://github.com/martpie/next-transpile-modules)

The offending code is the check for `attr.name.name` in line 124:
https://github.com/zeit/styled-jsx/blob/00fcb7bcad9c8af91167056f93c63858d24769ba/src/_utils.js#L121-L124

We don't actually use styled-jsx, and I have no idea our app is running into this, but patching it like this avoids the issue:
```js
el.openingElement.attributes.some(attr => attr.name && attr.name.name === STYLE_ATTRIBUTE)
```

If deemed worthy, I'm happy to send a pull request with the above change.

#### Environment (include versions)

* OS: osx 10.13.6
* Browser: compoile time error
* styled-jsx (version): 3.2.1

#### Did this work in previous versions?
I don't know

**Comment by giuseppeg** [comment]
hi this could be a precedence issue i.e. maybe `next-transpile-modules` runs before styled-jsx and it is transpiling something which leads to the bug. Have you tried to remove styled-jsx from the next/babel preset? What does your `transpileModules` look like?

**Comment by TxHawks** [comment]
Sorry for the long delay in replying. Closing since the issue seem to no longer happen with latest version of Next.
