### ISSUE TITLE
JS Variable in JSX breaks when used in SASS Function

### ISSUE THREAD

**Issue by Soundvessel** [zeit/styled-jsx#558]
#### Do you want to request a *feature* or report a *bug*?

Bug

#### What is the current behavior?

SASS functions are getting run before the JS variable is processed creating a build error.

```
./pages/index.js
Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
Error: Undefined operation: "styled-jsx-placeholder-1-/16 times 1rem".
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
```

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

Example: https://codesandbox.io/s/0y2q7162k0 look at `/pages/index.jsx` 

My goal was to have a JS variable passed into styled-JSX SASS and processed with a SASS function. It appears the SASS function is running before the JS variable is applied.

You can comment out line 31 and uncomment line 30 to see that the JS variable works when not in a SASS function.

#### What is the expected behavior?

SASS function utilizes JS variable and doesn't error out with styled-jsx-placeholder.

#### Environment (include versions)

* OS: Windows & CodeSandbox
* Browser: Chrome
* styled-jsx (version): Whatever is shipped with NextJS 8.0.3

#### Did this work in previous versions?

Unknown

#### Why?

This is a simple example from my setup that utilizes Bootstrap as a global design system. It's variables and functions are imported into custom components to create scoped CSS for new components. I have images which I wanted one source of truth for image sizes to apply to both image tags and processed SASS that utilize their measurements.

**Comment by giuseppeg** [comment]
Hi unfortunately this is not possible as SASS is run at build time and JS (interpolations) at runtime. In general interpolations cannot be preprocessed https://github.com/zeit/styled-jsx#css-preprocessing-via-plugins
