### ISSUE TITLE
_JSXStyle is not defined

### ISSUE THREAD

**Issue by achefinil** [zeit/styled-jsx#560]
####  my .babelrc file
```
"plugins": [
    [
      "styled-jsx/babel"
    ],
    "inline-dotenv",
    ["module-resolver", {
      "root": ["./src"]
    }],
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    [
      "import", {
        "libraryName": "antd",
        "style": true
      }
    ]
  ],
```
#### my js 
```
<style jsx>{`
 span {
   color: red;
  }
`}</style>
```
then i got error ~ Please give me solution for this problem. 

`ReferenceError: _JSXStyle is not defined`

#### Environment (include versions)

* OS: mac windows
* Browser: chrome
* styled-jsx (version): styled-jsx 3.2.1 nextjs 8.0.1

**Comment by tbarkley** [comment]
I'm having a similar issue;

next: ^8.0.4
webpack: ^4.30.0
styled-jsx: ^3.2.1

**Comment by tbarkley** [comment]
> * Browser: chrome

@achefinil ... I found this which may be the cause: #545

**Comment by tbarkley** [comment]
I'm still also trying to get this to work and #545 is not the issue I think (I'm not using a different version of styled-jsx now at all in my dependencies). I was getting the same _JSXStyle is not defined and while attempting to debug I tried this which actually caused it to work;

**MainLayout.jsx**

```js
//Not sure why but, it only works when I do this
import _JSXStyle from "styled-jsx/style";

class MainLayout extends React.Component {
    componentDidMount() {
           console.log(_JSXStyle); //Only works below when I'm console logging it??
    }
    render() {
          return (
             <div>
                    <p>Yooo</p> 
                     {
                         //Paragraph is black as expected unless I take the console log out in componentDidMount.
                     }
                    <style jsx>
                           {`p {background-color:black; }`}
                     </style>
             </div>
           );
    }
}
```

**Comment by Rapol** [comment]
I'm experiencing the same issue when I include styled-jsx-plugin-sass to my babelrc. Importing _JSXStyle fixes the problem just like @tbarkley found.

.babelrc
```
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "styled-jsx/babel",
      { "plugins": ["styled-jsx-plugin-sass"] }
    ]
  ]
}
```

next: ^8.0.3
styled-jsx-plugin-sass: ^1.0.0

I thought it was the same issue as https://github.com/zeit/styled-jsx/issues/545 but I dont have styled-jsx as a dependency and styled-jsx-plugin-sass doesn't have it either. I searched my package-lock and there isnt any other library using styled-jsx so I cant really fixed it by forcing versions via yarn resolutions.

**Comment by achefinil** [comment]
@tbarkley thank you very much ..

**Comment by achefinil** [comment]
@Rapol thank you very much

**Comment by Rapol** [comment]
I was able to fix my problem following the sass sample at (https://github.com/zeit/next.js/tree/canary/examples/with-external-styled-jsx-sass). Seems like I was misusing the babel config.

**Comment by ArtyomResh** [comment]
Any suggestions on how to fix this for large projects that start `using next-js` and `styled-jsx` along time ago? I can't afford to manually paste `import _JSXStyle from "styled-jsx/style"` in every file that uses `styled-jsx`

**Comment by nicholas-c** [comment]
Also happening with postCSS plugin - Not just the Sass...

https://github.com/giuseppeg/styled-jsx-plugin-postcss

**Comment by gtolarc** [comment]
@BradEP You're right!

next/babel preset contains styled-jsx, so do not add duplicates to existing plugins and use the default preset.

```
{
  "presets": [["next/babel", {
    "preset-env": {},
    "styled-jsx": {
      "plugins": ["styled-jsx-plugin-postcss"]
    }
  }]],
  // "plugins": [["styled-jsx/babel", {
  //   "plugins": ["styled-jsx-plugin-postcss"]
  // }]]
}
```

**Comment by giuseppeg** [comment]
It seems that you tracked down the source of the issue. Next.js includes styled-jsx already and therefore you need to configure it via the preset like in this comment https://github.com/zeit/styled-jsx/issues/560#issuecomment-493112657

**Comment by HajimexxxNakagawa** [comment]
I got the same issue resolved in a sly(?) way.

**.babelrc**
```
{
  "presets": ["next/babel"],
  "plugins": ["styled-jsx/babel"]
}

```


**_app.tsx**
```
~~~~~~~~~~~~~~~~~~~~~~~~~~
const _JSXStyle = require('styled-jsx/style').default

if (typeof global !== 'undefined') {
  Object.assign(global, { _JSXStyle })
}
~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by timneutkens** [comment]
@HajimexxxNakagawa that's going to break the implementation and cause a FOUC in many cases.

**Comment by cleverboy32** [comment]
> @HajimexxxNakagawa that's going to break the implementation and cause a FOUC in many cases.
i found import _JSXStyle not work in .ts file / but use  require can ?

**Comment by mavichow** [comment]
Hi guys, I've encounter the same error when including "plugins" too in .babelrc file.

I wanted to try include "rupture" & "nib" plugins into .babelrc w [styled-jsx-plugin-stylus](https://github.com/omardelarosa/styled-jsx-plugin-stylus), but got this error.

```
{
    "presets": [
        [
            "next/babel",
            {
                "styled-jsx": {
                    "plugins": ["styled-jsx-plugin-stylus"]
                }
            }
        ]
    ],
    "plugins": [
        [
            "styled-jsx/babel", {
                "plugins": [
                    [
                        "styled-jsx-plugin-stylus",
                        {
                            "stylusOptions": {
                                "use" : ["nib","rupture"],
                            }
                        }
                    ]
                ]
            }
        ]
    ]
}
```

May I know any of you guys encounter the same _JSXStyle error while setting up JSX with Stylus?

Tq
