### ISSUE TITLE
Styletron like one class per prop

### ISSUE THREAD

**Issue by steida** [zeit/styled-jsx#568]
#### What is the current behavior?

Styledjsx generates CSS chunks. 

#### What is the expected behavior?

Maybe it could generate one class per prop. It should open the possibility for progressive CSS and the output should be smaller I guess. I am simulating this behavior with this code:

```ts
const utilityCSSClassNames: string[] = [];
  const utilityCSSStyles = [];
  Object.keys(blockStyle).forEach(prop => {
    const value = blockStyle[prop];
    if (value.trim().length === 0) return;
    // thysultan/stylis.js supports flat stylesheets aka without .foo { ... }
    const styleText = `${prop}: ${value}`;
    const { className, styles } = css.resolve`${styleText}`;
    utilityCSSClassNames.push(className);
    utilityCSSStyles.push(styles);
  });
```

**Comment by giuseppeg** [comment]
Compiling to atomic CSS classes comes with a lot of constraints and trade-offs and it is outside of the scope of this library.
