### ISSUE TITLE
&:first-child in css.resolve bug

### ISSUE THREAD

**Issue by jaydenseric** [zeit/styled-jsx#576]
#### Do you want to request a *feature* or report a *bug*?

Bug.

#### What is the current behavior?

Using `css.resolve`, the `&:first-child` selector is buggy; the generated selector only has the class name from the `&` part, without the `:first-child` part. 

This should work, as stylis is ok with it:

<img width="612" alt="Screen Shot 2019-08-29 at 1 50 38 pm" src="https://user-images.githubusercontent.com/1754873/63908914-38ccd880-ca64-11e9-862a-384cdc156dbb.png">

Surprisingly `:first-child` on its own (without the `&` prefix) works.

Other pseudo-classes like `:last-child` have the same issue.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

With:

```js
import css from 'styled-jsx/css'

const styles = css.resolve`
  &:first-child {
    color: red;
  }
`
```

The generated CSS is something like this:

```css
.jsx-2431407468 {
  color: red;
}
```

#### What is the expected behavior?
 
The generated selector should have `:first-child` in it, like this:

```css
.jsx-2431407468:first-child {
  color: red;
}
```

#### Environment (include versions)

* OS: N/A
* Browser: N/A
* styled-jsx (version): 3.2.1

#### Did this work in previous versions?

Not sure.

**Comment by giuseppeg** [comment]
The `&` (parent reference) syntax is disabled in styled-jsx as we only support standard CSS.

**Comment by jaydenseric** [comment]
@giuseppeg that's not entirely true, I depend upon the `&` working in [`device-agnostic-ui`](https://github.com/jaydenseric/device-agnostic-ui):

https://github.com/jaydenseric/device-agnostic-ui/blob/bb71c7d1e1a789eb0266f3b9c628eefa07912cc2/src/styles/Blockquote.mjs#L7

It allows sharable styles (via `css.resolve`) to be applied to any element that has the class name represented by `&`. It also allows for smaller bundle sizes and less CSS, as in many cases `blockquote.jsx-3666658243` would be pointless specific, when `.jsx-3666658243` would do.

You can see it in action here: https://deviceagnosticui.com/components/Blockquote
