### ISSUE TITLE
Omitting escape character in a specific circumstance

### ISSUE THREAD

**Issue by rickgbw** [zeit/styled-jsx#578]
#### Do you want to request a *feature* or report a *bug*?
Bug

#### What is the current behavior?
When creating a style inside a Next.js page, it removes the escape character from a "content" style (Like: `e92b` instead `\e92b`). It happened only if I have a require statement on the same style.

#### If the current behavior is a bug, please provide the steps to reproduce and possibly a minimal demo or testcase in the form of a Next.js app, CodeSandbox URL or similar

```jsx

function Page() { 
   return (
      <div>
         <div className="test" />
         <style jsx>{`
            .test {
               background-image: url(${require('../sample.svg')});
            }
            .test:before {
               content: '\\e92b';
               font-family: 'ico';
            }
        `}
        </style>
      </div>
   );
}
```

It compiles to `content: 'e92b'`:

<img width="205" alt="Screen Shot 2019-08-30 at 13 50 28" src="https://user-images.githubusercontent.com/924158/64037927-36828100-cb2d-11e9-9e68-20b7ebf2c02c.png">

But, if I remove the "background-image" line, it works as expected (`content: '\e92b'`)

#### What is the expected behavior?
The compiled CSS return `content` with escape character like: `content: \e92b` instead `content: e92b`.

#### Environment (include versions)

* OS: macOS 10.14.5
* Browser: Chrome 76.0.3809.100
* styled-jsx (version): 3.2.1
* next.js (version): 9.0.5

#### Did this work in previous versions?
Yes. Using with Next.js 9.0.2 it works as expected.

**Comment by giuseppeg** [comment]
fixed in #577
