### ISSUE TITLE
Flash of unstyled content with recent v3.2.2 upgrade.

### ISSUE THREAD

**Issue by maxchehab** [zeit/styled-jsx#579]
#### Do you want to request a *feature* or report a *bug*?
A bug 🐛 .

#### What is the current behavior?
After upgrading styled-jsx from **3.2.1** to **3.2.2** we noticed our entire web app flashes unstyled content in production (hosted with zeit). However, this is not reproducible within a development environment (`now dev`).

#### Environment (include versions)

* OS: OSX 10.14.6
* Browser: Firefox 68.0.2
* styled-jsx (version): 3.2.2

#### Did this work in previous versions?
Yes

**Comment by giuseppeg** [comment]
@maxchehab can you provide a test case? Maybe a minimal Next.js app that I can clone and try out

**Comment by maxchehab** [comment]
@giuseppeg Sorry for the lag.

We resolved this by removing `styled-jsx` as a dependency for our project.

It seems since we are using NextJS ([which depends on `styled-jsx`](https://github.com/zeit/next.js/blob/1aec686c8029e0914261a348bfda542e2f2a9694/packages/next/package.json#L119)), including `styled-jsx` was causing conflicts with our css (maybe with generated class names?).

Again, sorry for not responding quicker. Will close this issue :)

**Comment by marktran** [comment]
Specifically, we had `styled-jsx@3.2.2` in our `package.json` and `next/styled-jsx@3.2.1`. Having both versions was causing unstyled content to flash.

(@maxchehab and I are on the same team)
