### ISSUE TITLE
Combining HTML, CSS and Babel+JSX into one 

### ISSUE THREAD

**Issue by jermaiine** [zeit/styled-jsx#582]
Hi, 
I'm new to programming here. I seem to have trouble trying to code HTML, CSS and JS into one. Would appreciate any help I could get. 

Here is the link:
https://jsfiddle.net/kimmobrunfeldt/72tkyn40/

Thank you!

**Comment by giuseppeg** [comment]
Hi thanks for reaching out, unfortunately this is out of scope for this repository therefore I am closing it :)
