### ISSUE TITLE
className missing when assigned using an object

### ISSUE THREAD

**Issue by michalisgar** [zeit/styled-jsx#583]
#### Do you want to request a *feature* or report a *bug*?
Bug.

#### What is the current behavior?
I have created a [codesandbox](https://codesandbox.io/s/nextjs-jsx-ecxhd?fontsize=14) to use as a reference. 

When using `<style jsx>` while assigning a `className` to my component with the use of an object, the `class` is overwritten (**pages/withJsx.js**) by the one `styled-jsx` creates. I've also added an `id` on the same object in order to see if my approach is valid. 
![withJsx](https://user-images.githubusercontent.com/29352004/65265410-914e3d80-db19-11e9-9dc9-5a55f0d4fbb7.png)

When I don't use `<style jsx>` this works as expected with both `id` and `class` assigned to the component (**pages/withoutJsx.js**).

Of course, there is an alternative approach for this one (**pages/withJsxWorkaround.js**) but I suppose the first one should also work like this.

#### Environment (include versions)

* OS: macOS High Sierra 10.13.6
* Browser: Chrome Version 76.0.3809.132 (Official Build) (64-bit)
* styled-jsx (version): 3.2.1

#### Did this work in previous versions?
Not sure about this. I just noticed it.

**Comment by giuseppeg** [comment]
@michalisgar thanks for the detailed bug report! Even though this is an actual bug, I think this is an edge case and probably adding a fix for it would make the compiled output way more complex than it is right now. So I'd rather not fix it. 

I think that you can move the ternary in a constant inside of the `render` method and then use that in `className`. 

I am closing the issue for now :)

**Comment by michalisgar** [comment]
Totally understandable! Thanks for your feedback @giuseppeg. :slightly_smiling_face:
