### ISSUE TITLE
Consider taking the ownership of VSCode extensions

### ISSUE THREAD

**Issue by HosseinAgha** [zeit/styled-jsx#585]
#### Do you want to request a *feature* or report a *bug*?
not a bug nor a feature

The vscode extensions for `styled-jsx` are unmaintained and incomplete. Take a look at 2 of the most used extensions by community:  
  - https://github.com/iFwu/vscode-styled-jsx
  - https://github.com/Grimones/vscode-styled-jsx-languageserver

Both are not standard, maintainers abandoned the projects, have many open issues.  

For example take a look at https://github.com/iFwu/vscode-styled-jsx/issues/6 that is open since 2 years ago.  

The problem of writing a vscode extension for template literal languages (with full autocomplete support) is solved a long time ago. Take a look at https://github.com/styled-components/vscode-styled-components and https://github.com/Microsoft/typescript-styled-plugin. So we can easily write a full functioning extension by forking these 2 projects.  

I think editor support is an important factor in adopting a new language or library and vscode is of course the most used editor in the community.  

Please also take a look at https://github.com/zeit/next.js/issues/8971

**Comment by giuseppeg** [comment]
@HosseinAgha I don't disagree with your proposal but I am the only maintainer of this repo and I doubt I'd have the time to work on that and maintain it. I would be happy to link to a repo if you want to work on a modern version though! 

I am going to close the issue for now :)

**Comment by HosseinAgha** [comment]
Thanks for answering so fast and maintaining this awesome project.
I think adding the `help-wanted` tag (and changing the issue's title) would be a better approach so somebody (maybe myself) someday finds this issue and tries to develop a better extension :)

**Comment by giuseppeg** [comment]
Once we add the extension we will have to maintain, people will report bugs and feature requests, and I don't have time for that. That's why I prefer it to be maintained by the community.
