### ISSUE TITLE
no unicode in :after content

### ISSUE THREAD

**Issue by JipSterk** [zeit/styled-jsx#587]
#### Do you want to request a *feature* or report a *bug*?
bug
#### What is the current behavior?
```tsx
<style jsx>{`
div:after {
content: "\25BC"
}
`}</style>
```

the snippit above fails even if i add an extra `\`

#### What is the expected behavior?

display a ▼

#### Environment (include versions)

* OS: macos
* Browser: brave v0.69.132
* styled-jsx (version): 3.3.2

**Comment by giuseppeg** [comment]
tracking this issue here, thanks for reporting it! https://github.com/zeit/styled-jsx/issues/589
