### ISSUE TITLE
Component(constants) having props with children doesn't working

### ISSUE THREAD

**Issue by kkangil** [zeit/styled-jsx#593]
👋 friend. Welcome to styled-jsx and thanks for contributing!

⚠️ IMPORTANT ⚠️

If you need help or have a question about styled-jsx please ask it on Spectrum https://spectrum.chat/styled-jsx or join our Slack community at https://zeit.chat and ask it in the `#next` channel.

Before you open a new issue please take a look at our [**Frequent Asked Questions**](https://github.com/zeit/styled-jsx#faq) and [**open issues**](https://github.com/zeit/styled-jsx/issues).

Remember, often time asking in chat or looking at the FAQ/issues can be *faster than waiting for us to reply to a new issue**.

If you are here to report a bug or request a feature please remove this introductory section and fill out the information below!

---

#### Do you want to request a *feature* or report a *bug*?
bug
#### What is the current behavior?

https://github.com/zeit/styled-jsx#constants

Component(constants) having props with children doesn't working that I expected like below

```
const App = () => {
  return (
     ...
    <Title color={"red"}>
        <div>
            <h1>TITLE</h1>
            <p>DESCRIPTION</p>
        </div>
    </Title>
   ...
  )
}
const Title = ({children, color}) => (
    <div className={'test'}>
        {children}
        <style jsx>{`
            .test h1 { color:${color}; }
            .test p { color:${color}; }
        `}</style>
    </div>
);
```

I can't understand why this code is not working.

But below code is working well.

```
const App = () => {
  return (
     ...
    <Title color={"red"}>
        <h1>TITLE</h1>
    </Title>
   ...
  )
}
const Title = ({children, color}) => (
    <h1 className={'test'}>
        {children}
        <style jsx>{`
            .test { color:${color}; }
        `}</style>
    </h1>
);
```

I wonder, Why it isn't working. How can I resolve it?

#### What is the expected behavior?

I think `.test h1`, `.test p` styles should be working.

#### Environment (include versions)

* OS: macOS Catalina
* Browser: Chrome 77
* styled-jsx (version):NextJS 8.0.3 bundled (styled-jsx@3.2.1)

**Comment by giuseppeg** [comment]
@kkangil styles are scoped to the component that's why they don't apply to children. You can read more about this here https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent
