### ISSUE TITLE
Docs don't state why I'd use styled-jsx/macro over styled-jsx/css

### ISSUE THREAD

**Issue by wilsonpage** [zeit/styled-jsx#597]
The docs state:

> The resolve tag can be used as a Babel macro thanks to the babel-plugin-macros system.

But don't say why this is good, or if/when/why I'd choose to use it over `styled-jsx/css`. As a user I'd like to know the pros and cons of each so I can decide which approach I should use.

**Comment by giuseppeg** [comment]
Hi @wilsonpage, the macro is for when you cannot customize the Babel configuration but can install macros - you can read more about this here https://github.com/kentcdodds/babel-plugin-macros

For example Create React App supports macros. Would you like to submit a PR to clarify this in the README?

**Comment by wilsonpage** [comment]
@giuseppeg ah I'm using Nextjs, so I assume that the next-babel config already contains the styled-jsx loader/transpiler?

**Comment by giuseppeg** [comment]
yes Next is already configured to use styled-jsx so you can use `styled-jsx/css`

**Comment by wilsonpage** [comment]
Ah ok, so there's not much sense in me using the macro here?

**Comment by wilsonpage** [comment]
https://github.com/zeit/styled-jsx/pull/601
