### ISSUE TITLE
Support for WebStorm

### ISSUE THREAD

**Issue by sbking** [zeit/styled-jsx#60]
WebStorm's JSX interpreter does not like the use of `<style>` tags, so you get tons of syntax errors and warnings, and there is apparently no way to suppress the errors. Perhaps there could be an alternative syntax such as `<styled jsx>`? This would allow developers who use intelliJ IDEs to use this project.

**Comment by elliottpost** [comment]
There is a work around for this. See https://github.com/zeit/styled-jsx/issues/186
