### ISSUE TITLE
Taking over vscode-styled-jsx

### ISSUE THREAD

**Issue by anderseide** [zeit/styled-jsx#604]
The Visual Studio Code extension vscode-styled-jsx isn't maintained anymore by @iFwu 

* https://marketplace.visualstudio.com/items?itemName=blanu.vscode-styled-jsx
* https://github.com/iFwu/vscode-styled-jsx

Would like to propose that zeit took over that project. Would be great if that project didn't die

**Comment by giuseppeg** [comment]
@anderseide unfortunately I am the only maintainer and I don't have time to maintain that as well. I will leave it to the community to continue the work on that extension. Thank you for bringing this up though! Would you like to submit a PR to clarify in the README that the extension in not maintained and suggest that somebody takes over it?

**Comment by anderseide** [comment]
@iFwu have already stated that in the Readme. 

I was more thinking that the plugin could be naturally placed under the Zeit org. and then maintained by the community. When it’s placed under a personal account on GitHub and then left for anyone to grab, it will most likely be left for good.

Totally understand that you cannot take that responsibility and maintain it on your own

**Comment by aldendaniels** [comment]
Worth also noting that [vscode-styled-jsx-languageserver](https://github.com/Grimones/vscode-styled-jsx-languageserver) appears to be similarly unmaintained and doesn't support common patterns like using variable substitution in the template literal.

**Comment by aldendaniels** [comment]
> doesn't support common patterns like using variable substitution in the template literal

Specifically, the autocomplete package doesn't support this pattern:

```typescript
${ButtonSize.Medium} {
  border-radius: 40px;
  padding: 5px 20px;
}
```

**Comment by giuseppeg** [comment]
I am going to close this, if anybody wants to take over the plugin we can link and recommend it in the README
