### ISSUE TITLE
element + element selector problem

### ISSUE THREAD

**Issue by jackylee941130** [zeit/styled-jsx#611]
I would like to add margin-left for each <ComponentA> except the first one.

```
<div>
  <ComponentA class="a">
  <ComponentA class="a">
  <ComponentA class="a">
</div>
```

In general css, I can do something like
```
.a + .a {
   margin-left: 10px;
}
```
But it **doesn't** work at all!

Additionally, my ComponentA use React.fragment as the root. How can I do the same thing as below (Without replacing the fragment by <div> as root)?
```
self + self {
  margin-left: 10px;
}
```

**Comment by giuseppeg** [comment]
styled-jsx doesn't add scoped classes to components automatically. 

In order to style nested components you have these options https://github.com/zeit/styled-jsx#styling-third-parties--child-components-from-the-parent
