### ISSUE TITLE
No source tag or commit for version 3.2.4

### ISSUE THREAD

**Issue by ChALkeR** [zeit/styled-jsx#613]
Version 3.2.4 was [published on npm](https://www.npmjs.com/package/styled-jsx/v/3.2.4) two months ago, but not present here.

It apparently has been cut from 66f3b36ef53f3e576f0ec40ef782a2b87a7f015a plus the `version` update in `package.json`, build seems to be reproducible.

**Comment by giuseppeg** [comment]
fixed https://github.com/zeit/styled-jsx/releases/tag/3.2.4
