### ISSUE TITLE
can i use sass nested within styled-jsx/css, outside one react component??

### ISSUE THREAD

**Issue by milobluebell** [zeit/styled-jsx#614]
How can i compile sass like `External CSS and styles outside of the component` using styled-jsx/css?

when:
```
import css from 'styled-jsx/css';
const test1 = css`
.test-wapper{
    background-color: red;
    color: white;
    .span{
      background-color: green;
      color: white;
    }
}
```

it will make errors fatally,  error log:
```
Nesting detected at xx:xx Unfortunately nesting is not supported by styled-jsx.

    at Array.forEach (<anonymous>)

    at Array.forEach (<anonymous>)

    at Array.forEach (<anonymous>)

```

**So, can i use sass within styled-jsx/css nested outside one react component? and how to?**
ty! plz be quick😊

**Comment by giuseppeg** [comment]
hi @milobluebell see https://github.com/zeit/next.js/tree/canary/examples/with-external-styled-jsx-sass
