### ISSUE TITLE
高亮消失

### ISSUE THREAD

**Issue by GitHub-o** [zeit/styled-jsx#617]
### 表达式内出现空格，高亮消失

![Uploading E_U[HD`85PMT%8%EM70)MCL.png…]()

**Comment by timneutkens** [comment]
Please follow the issue template.

https://github.com/zeit/next.js/issues/new/choose

https://github.com/zeit/next.js/issues/new?template=8.Question_about_next.md

```
# Question about Next.js

GitHub Issues are reserved for Bug reports and Feature requests. The best place to get your question answered is to post it on https://spectrum.chat/next-js.
```
