### ISSUE TITLE
Styles in separate file

### ISSUE THREAD

**Issue by Jpunt** [zeit/styled-jsx#62]
Could we imagine a webpack-loader that loads `*.sjsx` files? That way you could save your styles in separate files and configure your editor to use regular old css syntax-highlighting and code-completion. Love the idea of styled-jsx, but styles inside a string literal get pretty hard to read.

```jsx
// Component.js
import React from 'react';
import './Component.sjsx';

export default () => (
  <div>
    <p>Some component</p>
  </div>
)
```
```scss
// Component.sjsx
p {
  color: red;
}
```

**Comment by thysultan** [comment]
wouldn't this work?

```
import './Component.sjsx' as css;

export default () => (
  <div>
    <p>Some component</p>
    <style jsx>{css}</style>
  </div>
)
```

**Comment by rstacruz** [comment]
> edit: actually that might not work without exporting the string in the other file.

Looks like a job for [raw-loader](https://www.npmjs.com/package/raw-loader)

**Comment by Jpunt** [comment]
Sounds like a plan, thanks 👍

**Comment by thisbejim** [comment]
For those of you using [next.js](https://github.com/zeit/next.js) you can put your styles in a `./styles.js` file next to your component:
```
export default `
  p {
    color: red;
  }
`
```
Then import it:
```
import styles from './styles';

export default () => (
  <div>
    <p>only this paragraph will get the style :)</p>
    <style jsx>{styles}</style>
  </div>
)
```

**Comment by MrOrz** [comment]
@thysultan 

in styled-jsx 0.5.2

```
import './Component.sjsx' as css;

export default () => (
  <div>
    <p>Some component</p>
    <style jsx>{css}</style>
  </div>
)
```

Gives the error:

```
SyntaxError: Expected a template literal or String literal as the child of the JSX Style tag (eg: <style jsx>{`some css`}</style>), but got Identifier
```

Thus it doesn't work.

**Comment by winglian** [comment]
I also tried `<style jsx dangerouslySetInnerHTML={{ __html: s }} />` but received the error

`Cannot read property 'length' of undefined`

which traces to https://github.com/zeit/styled-jsx/blob/master/src/babel.js#L242

Any ideas?
