### ISSUE TITLE
Malformed CSS if tag is empty

### ISSUE THREAD

**Issue by derolf** [zeit/styled-jsx#623]
Consider the following SIMPLIFIED example:

```
<style jsx>{`
  div {
    ${flag ? "color: blue;" :""}
  }
`}</style>
```

If flag is false, this results in the following invalid CSS:

```
div {;}
```

The following basic example also results in the same invalid CSS:

```
div {
  ${""}
}
```

**Comment by giuseppeg** [comment]
this is discouraged and not guaranteed to work `flag ? "color: blue;" :""`

Instead you should define those styles using a class and toggle that class on the element based on the value of `flag`

**Comment by derolf** [comment]
Thanks for closing the issue. Understood that the simplified example was too simplified.

Hence, I created a more complex example in a new issue:

https://github.com/zeit/styled-jsx/issues/625
