### ISSUE TITLE
Duplicate styles after static site generatation with nextjs

### ISSUE THREAD

**Issue by muyiwaoyeniyi** [zeit/styled-jsx#632]
It appears styled-jsx doesn't properly diff styles from the server with styles generated on the frontend.

See attached screenshot

![Screenshot from 2020-04-24 07-46-45](https://user-images.githubusercontent.com/1622600/80210296-8274bf80-8601-11ea-82d3-b99626741898.png)

Code--
```
import Document, { Html, Head, Main, NextScript } from "next/document";
import flush, { flushToHTML } from "styled-jsx/server";

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    initialProps.styles = flush();
    return { ...initialProps };
  }

  render() {
    console.log(this.props.styles);
    return (
      <Html>
        <Head>{this.props.styles}</Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

#### What is the expected behavior?
Styles should not be duplicated.

#### Environment (include versions)

* OS: Ubuntu 18.04
* Browser: Chrome
* styled-jsx (version): 3.2.5

**Comment by ke1vin1993** [comment]
@muyiwaoyeniyi Did you solve it?

**Comment by muyiwaoyeniyi** [comment]
@ke1vin1993 I did but I don't completely recall the solution. Here's what I know... if your _document.js is just like mine, then you actually don't need the file anymore. Nextjs injects the files on the server by default without having to spin up this file.

**Comment by ivan-kleshnin** [comment]
But then you need to pass something to `flush` for stricter CSP and so custom `_document.js` and `getInitialProps` are required again, I guess.
