### ISSUE TITLE
Replacing duplicated rules by a class in compile time

### ISSUE THREAD

**Issue by richardaum** [zeit/styled-jsx#633]
#### Do you want to request a *feature* or report a *bug*?
Feature

#### What is the current behavior?
Imagine you apply some styles in your application:
```
<div className="box-a" />
<div className="box-b" />
<div className="box-c" />
<style jsx>{`.box-a { color: 'red', margin: 10x, padding: 10px } }`}</style>
<style jsx>{`.box-b { color: 'blue', margin: 10x, padding: 10px }`}</style>
<style jsx>{`.box-c { color: 'purple', margin: 10x, padding: 10px }`}</style>
```
The generated CSS would be made using a hash generated from those 3 classes. 

#### What is the expected behavior?
What if styled-jsx could recognize all common used CSS properties and try to write classes for them?
```
<div className="box-a generated-a-b-c" />
<div className="box-b generated-a-b-c" />
<div className="box-c generated-a-b-c" />

.box-a { color: 'red' }
.box-b { color: 'blue' }
.box-c { color: 'purple' }
.generated-a-b-c { margin: 10x; padding: 10px }
```
Considering we repeat some styles multiple times in our apps, this approach would reduce the CSS final size by grouping duplicated CSS into multiple classes.

What do you guys think?

**Comment by giuseppeg** [comment]
it is not possible to automate this atm
