### ISSUE TITLE
How can we remove the attached dynamic jsx-[rendom id]

### ISSUE THREAD

**Issue by tufail** [zeit/styled-jsx#636]
Hi,

I like to remove the extra dynamic classes attaching with my class name.
example:
` .email svg { height: 220px}`

The out put is generating ` .email.jsx-3069860201 svg.jsx-3069860201`

but I don't need any class in svg and how to get current jsx-id so that we can put dynamically in react.

Please help us

**Comment by giuseppeg** [comment]
you can use :global:

```
.email :global(svg) { height: 220px}
```
