### ISSUE TITLE
Scoping seems to only apply to immediate markup

### ISSUE THREAD

**Issue by anaisbetts** [zeit/styled-jsx#638]
Scoped `style` tags don't seem to apply to elements that aren't verbatim included in the content. For example:

```jsx
const items = [1,2,3,4,5].map(x => (<li key={x}>It's {x}!</li>));

return <>
  <ul>{items}</ul>

  <style jsx>{`
    ul { background: blue; }
    li { background: red; }
  `}</style>
</>;
```

In this example, only the style for `ul` will be applied. Creating a style tag for the `li` is possible but feels super inefficient (creating N CSS classes), and also makes styling things like CSS Grids really inconvenient, because I have to separate the "semantics" of the grid across separate style tags, whereas I'd prefer that everything related to that Grid is right next to each other

My apologies for filing this arguably-a-question as a bug report, Spectrum seems DOA, and zeit.chat redirects to a Discussions tab of `now` which seems Unrelated. Also, CodeSandbox seems to be broken today, I can't load it on my machine.  

#### Environment (include versions)

* OS: Windows 10
* Browser: Edge Chromium Dev 84
* styled-jsx (version): 3.2.5

**Comment by giuseppeg** [comment]
hi @anaisbetts

> My apologies for filing this arguably-a-question as a bug report

No worries and no need to apologize! :) 

> Creating a style tag for the li is possible but feels super inefficient (creating N CSS classes)

This is indeed the case here and the suggested way to style things but I agree that it might be annoying. I don't understand the _creating N CSS classes_ part.

styled-jsx encapsulates styles on a per-component basis like ShadowDOM does. Therefore crossing the component boundaries is not possible unless you explicitly opt out scoping with the `:global(your_selector_goes_here)`  pseudo selector 

```jsx
return <>
  <ul>{items}</ul>

  <style jsx>{`
    ul { background: blue; }
    ul > :global(li) { background: red; }
  `}</style>
</>;
```

or create some scoped class in the current component and pass it down to the children as prop

```diff
+ import css from 'styled-jsx/css'
+ const { className, styles } = css.resolve`
+   li { background: red; }
+ `

function List() {
  return <>
    <ul>{
+       items.map((item, key) => 
+         React.cloneElement(
+           item, 
+           {
+             ...item.props,
+             className: `${className} ${item.props.className || ''}`
+           }
+         )
+       )
    }</ul>

+    {styles}
    <style jsx>{`
      ul { background: blue; } 
+      li { background: red; }     
    `}</style>
  </>;
}
```

Hope this helps
