### ISSUE TITLE
Question: What's the reason to not provide an async api for plugins?

### ISSUE THREAD

**Issue by StarpTech** [zeit/styled-jsx#639]
Related issue:

https://github.com/giuseppeg/styled-jsx-plugin-postcss/issues/31#issuecomment-588051109

As soon as a postcss plugin is async we have to use the async version of postcss but this is then incompatible with styled-jsx.

**Comment by giuseppeg** [comment]
styled-jsx is a Babel plugin and Babel doesn't have an async API for plugins unfortunately

**Comment by StarpTech** [comment]
Does that mean it's impossible to use async plugins with styled-jsx? Who designed that plugin architecture in an asynchronous environment called Node.js? :exploding_head: Thanks for clarifying.

**Comment by giuseppeg** [comment]
Yeah it is not possible, you need to use a workaround like execSync. The issue is not necessarily with styled-jsx but with Babel as Babel plugins cannot be async or do async work (and should be side-effect free). styled-jsx is a Babel plugin.
