### ISSUE TITLE
Components shouldn't get the data-jsx attribute

### ISSUE THREAD

**Issue by giuseppeg** [zeit/styled-jsx#66]
```jsx
const Test = () => (
  <div>
    <Component />
    <style jsx>{`
      span { color: red; }
    `}</style>
  </div>
)
```

When transpiled `Component` gets the `data-jsx` attribute.

```jsx
<Component data-jsx={2520901095} />
```

**Comment by rauchg** [comment]
+1

**Comment by nkzawa** [comment]
btw, you'd be able to apply styles to components If we add `data-jsx` to them as well.

```js
const Component = (props) => <div {...props}>hi</div>

const Test = () => (
  <div>
    <Component className="mystyle" />
    <style jsx>{`
      .mystyle { color: red; }
    `}</style>
  </div>
)
```

**Comment by giuseppeg** [comment]
@nkzawa I think that @rauchg and I discussed about controlling styles from a parent but he didn't seem to be that excited about the idea and in the end I agree.

Your idea would need a HOC because `className` need to be merged with existing classes.
I believe that `div :global(> *) { color: red; }` is quicker and gets the job done anyway. 

My proposal was to wrap `Component` if necessary and transpile `Component { color: red; }` to `closestparent :global(> *) { color: red; }`.

**Comment by rauchg** [comment]
Weren't there performance concerns with the usage of `*` ?

**Comment by giuseppeg** [comment]
@rauchg I have no idea tbh. I believe that browsers are fast enough so it should be fine. I think that `>` should make it faster since the engine won't look for matches further down the tree.
