### ISSUE TITLE
Child selectors don't work

### ISSUE THREAD

**Issue by Jpunt** [zeit/styled-jsx#67]
I can see it's very logical that this doesn't work, but it would be great. Consider the following pseudo-code:

```jsx
export default ({people}) => (
  <div className="root">
    {people.map(person =>
      <Person key={person._id} person={person} />
    )}

    <style jsx>{`
      .root {
        display: flex;
      }
      .root > * {
        flex: 1 0 50%;
      }
    `}</style>
  </div>
)
```

The only way to set the flex of `Person` is inside of that component. But I wouldn't always want it to be `50%`, it could be rendered anywhere. I could add an extra component or element in between, but in that case `Person` always needs to do some "full width/height to its parent" trickery. Overriding it with a prop doesn't feel right either..

Is there any way to make this work? Would be awesome!

**Comment by giuseppeg** [comment]
> I could add an extra component or element in between, but in that case Person always needs to do some "full width/height to its parent" trickery

This is indeed [what we recommend in SUIT CSS](https://github.com/suitcss/suit/blob/master/doc/components.md#adapting-to-ancestral-context) since it makes it easy to compose and adapt `Person` to different contexts.

I also wrote about [this topic](http://giuseppegurgone.com/margins-and-composability-in-css).

Targeting components from the parent like that is not possible right now.

**Comment by Jpunt** [comment]
That's a very nice article, @giuseppeg. I totally agree that components should be responsible for their own layout, but their parents should do the positioning and things like margins. 

However, the article does not consider flexbox and I think this falls in the same category: The parent should be responsible to do the outer layout of its components, therefore it should set their `flex` property, like it would set it's `margin` or `width`. 

I can see how you could add an extra element inside the parent and set things like `margin` and `width` (which is what you mean by composing, right?). 

```jsx
export default ({people}) => (
  <div className="root">
    {people.map(person =>
      <div className="person">
        <Person key={person._id} person={person} />
      </div>
    )}

    <style jsx>{`
      .root {
        display: flex;
      }
      .person {
        flex: 1 0 50%;
      }
    `}</style>
  </div>
)
```

Unfortunately, in flexbox things get a bit more tricky, because it's pretty dependent on the direct children. For example: you could use it to make the items evenly high, but if you do this by adding extra elements inside the parent and set their `flex`, you'd still need to set the `height` property of the inner component. 

This is where child selectors would come in very handy, because you could say that whatever is inside this flex-container should have some flex-property. But I can see that this is not possible at the moment.

**Comment by Jpunt** [comment]
What if you could add a className inside the parent:

```jsx
export default ({people}) => (
  <div className="root">
    {people.map(person =>
      <Person key={person._id} person={person} className="person" />
    )}

    <style jsx>{`
      .root {
        display: flex;
      }
      .person {
        flex: 1 0 50%;
      }
    `}</style>
  </div>
)
```

And these styles get merged with the styles inside `Parent`?

**Comment by giuseppeg** [comment]
> What if you could add a className inside the parent

You can already do that with an higher order component which in this case is just for layout.

You can also use `:global` like this:

```css
.root :global(> *) {}
```

FWIW I believe that components like Person could also stretch vertically (flex-direction: row) too and let the parent or context decide the size – I am not at home now but I'll try that later.

**Comment by giuseppeg** [comment]
@Jpunt for what is worth: http://codepen.io/giuseppegurgone/pen/xgxKGB?editors=1100

**Comment by Jpunt** [comment]
Yeah, these rules are the ones that bother me:

```css
.Person {
  flex-direction: column;
  flex-grow: 1;
}
```

`Person` should not have to know that it should vertically grow to anything, because in other cases it may not be what you want. 

The global-trick seems to be what I need! I'll play around with it ASAP, thanks 👍
