### ISSUE TITLE
Make it possible to have <style> as a top-level component

### ISSUE THREAD

**Issue by rickyrauch** [zeit/styled-jsx#72]
Hello!

I had this scenario today: https://gist.github.com/rickyrauch/a9aa62854d2ebf9bed22d4bd14561de8

I fixed this wrap it in a `<div>`

Thanks

**Comment by giuseppeg** [comment]
Correct me if I am wrong but this feature makes sense only for `global` styles and basically you are using styled-jsx to do the following:

```js
document.head.insertAdjacentHTML('beforeEnd', `<style>p { color: red; }</style>`)
```

Is this worth the (possibly little) overhead?
