### ISSUE TITLE
Conflict with transform-react-constant-elements plugin

### ISSUE THREAD

**Issue by romainneutron** [zeit/styled-jsx#85]
When using the `transform-react-constant-elements` alongside the `style-jsx` plugin, the result is broken, see:

```html
<html>
    <body>
        <div id="app"></div>
    </body>
    <script src="app.js"></script>
</html>
```

```jsx
import React from 'react';
import { render } from 'react-dom';

function Component2() {
    return (
        <div>
            <style jsx>{`
                p {
                    color: red;
                }
            `}</style>
            <p>{'This should be red'}</p>
        </div>
    );
}

function Component1() {
    return (
        <div>
            <p>{'This should be black'}</p>
            <Component2 />
        </div>
    );
}

render(<Component1 />, document.getElementById('app'));
```

When using webpack configuration:
```json
  {
      "presets": [
        ["es2015", { "modules": false }],
        "react",
        "stage-0"
      ],
      "plugins": [
        "styled-jsx/babel",
      ]
    }
```
![image](https://cloud.githubusercontent.com/assets/137574/22152595/f8d4c608-df23-11e6-8cdf-3b81e3f0342d.png)

When using webpack configuration:
```json
  {
      "presets": [
        ["es2015", { "modules": false }],
        "react",
        "stage-0"
      ],
      "plugins": [
        "transform-react-constant-elements",
        "styled-jsx/babel",
      ]
    }
```
![image](https://cloud.githubusercontent.com/assets/137574/22152652/461142b6-df24-11e6-8dcb-a170a770f237.png)

**Comment by giuseppeg** [comment]
Have you tried to invert the plugins order? By hoisting element creation styled-jsx can't transform those right now (it could but it would complicate things).

**Comment by romainneutron** [comment]
Yep, I've tried to revert plugin order

**Comment by giuseppeg** [comment]
@romainneutron this issue is due to the fact that Babel is merging visitors so this happens:

styled-jsx's JSXElement visitors runs
annoying babel plugin's JSXElement visitors runs.

At this point the latter has optimized/replaced JSX and future attempt to run other visitors (eg. JSXOpeningElement) fail / don't apply.

A workaround is to run babel with the `passPerPreset` option set to `true`.

**Comment by jbrantly** [comment]
`passPerPreset` can unfortunately have other issues.

One solution I've found to this type of problem with my own custom plugins is to [manually traverse](https://github.com/babel/babel/issues/3793#issuecomment-245406254). I think the idea is that doing so incurs a performance penalty, but it does generally fix this kind of plugin ordering issue.

Apparently rethinking plugin order is on the table for Babel's next big release.

**Comment by giuseppeg** [comment]
Another solution could be to use just one visitor `JSXElement` and grab `JSXOpeningElement` by hand. To keep this sane we would split the business logic in smaller functions otherwise the visitor would be fairly big. 

If anyone wants to give it a stab I am here to help and guide if necessary.

**Comment by giuseppeg** [comment]
Related #84

**Comment by hzoo** [comment]
FYI made https://github.com/babel/babel/issues/5623 to discuss plugin ordering if anyone is interested
