### ISSUE TITLE
Styles doesn't get appended to the head in IE10 / IE11

### ISSUE THREAD

**Issue by roopemerikukka** [zeit/styled-jsx#88]
I found that if I have a component that mounts another component in example by clicking some button, the styles applied for the mounted component doesn't get applied.

Here is the example case:
```jsx

import React, { Component } from 'react'
import Head from 'next/head'

class App extends Component {

  constructor () {
    super()
    this.state = {
      showDiv: false
    }
  }

  onLinkClick () {
    this.setState({
      showDiv: !this.state.showDiv
    })
  }

  render () {
    return (
      <div>
        <Head>
          <title>Next.js with styled-jsx and IE10</title>
          <script src='https://cdn.polyfill.io/v2/polyfill.min.js' />
        </Head>
        <a href='#' onClick={(e) => { this.onLinkClick() }}>Click me!</a>
        { this.state.showDiv &&
          <SubComponent />
        }
      </div>
    )
  }
}

class SubComponent extends Component {
  render () {
    return (
      <div>
        <div className='subcomponent'>
          This and that
        </div>
        <style jsx>{`
          .subcomponent {
            background-color: black;
            color: white;
          }  
        `}</style>
      </div>
    )
  }
}

export default App

```

The subcomponent doesn't get the black background or the white text colors. The component gets the `data-jsx` attribute, but the `<style></style>` tags doesn't get appended to the pages `<head>` as they are in Chrome (or other newer browsers).

This bug occurs in both IE10 and IE11.

Here is the complete example repo: https://github.com/roopemerikukka/next.js-styled-jsx-ie10-issue

**Comment by roopemerikukka** [comment]
Now I noticed that this also happens when navigating to other page. Lets say I have pages like this:

```
pages/
  index.js
  item.js
```

Now if I have an component on the index page and there is a link to item page, the item page doesn't get any styles given by `<style jsx>` tags. If I navigate there directly I get the styles, propably because of SSR.

**Comment by giuseppeg** [comment]
I just tried your example on Windows 10 and it works 🤔

**Comment by roopemerikukka** [comment]
With which version of IE? I've tried it with IE10 on Windows 8, IE11 on Windows 7 and IE11 on Windows 10 but none of those worked (at least with browserstack). Here is the screenshots (IE11/Win10) with link clicked and without. As you see the style tag for the subcomponent is missing.

![screenshot 2017-01-24 09 27 35](https://cloud.githubusercontent.com/assets/1453463/22238096/322b1b9a-e218-11e6-89bb-bbbc35b25369.png)

---

![screenshot 2017-01-24 09 27 49](https://cloud.githubusercontent.com/assets/1453463/22238106/3dc13bf6-e218-11e6-9853-ef87c40de18c.png)

**Comment by sarukuku** [comment]
Remember that `Edge != IE` 😄

**Comment by sarukuku** [comment]
@roopemerikukka does it work on Edge?

**Comment by roopemerikukka** [comment]
@sarukuku yep works fine on the latest Edge.

**Comment by giuseppeg** [comment]
aw indeed IE10 comes with Edge, I will have to test it on 10/11

**Comment by sarukuku** [comment]
@giuseppeg have you had time to test this? :)

**Comment by giuseppeg** [comment]
@roopemerikukka @sarukuku sorry guys I've been a bit busy. 
I took a quick look and the issue seems to be with Promises so either there is a unhandled error or something doesn't work properly on the Next.js side, the polyfill is loaded too late or an actual problem with [this piece of code](https://github.com/zeit/styled-jsx/blob/master/src/style.js#L53).

@roopemerikukka have you tried to define a custom document instead of using `<Head/>`?

**Comment by roopemerikukka** [comment]
@giuseppeg yes I've tried to use a custom document also but with no luck. I also tried to do this directly
```jsx
function updateOnClient() {
  var Promise = require('es6-promise').Promise
  // Debounce calls and only render once the latest promise resolves.
  // rAF causes FOUC in Safari, setTimeout causes FOUC in Chrome, Promise#then()
  // ensures micro task enqueuing of styles update before paint.
  var promise = updatePromise = Promise.resolve().then(function () {
    if (promise === updatePromise) {
      updatePromise = null;
      doRender();
    }
  });
}
```

but it didn't fix the problem either.

**Comment by roopemerikukka** [comment]
The example seems to work if I'll include the whole `babel-polyfill` in the `<Head />` like this
```jsx
<Head>
  <script
    type='text/javascript'
    src='https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.20.0/polyfill.min.js' />
</Head>
```

So I can now make a test in there and include it only if necessary.

**Comment by giuseppeg** [comment]
@roopemerikukka so it seems to be an issue with the polyfill right? If you can confirm I'll close this issue.

**Comment by roopemerikukka** [comment]
@giuseppeg yep the problem was with the polyfill.

**Comment by sarukuku** [comment]
But shouldn't styled-jsx polyfill itself and not leave the polyfilling to the user of the library?

**Comment by giuseppeg** [comment]
@sarukuku nope if you have n libraries in your app you don't want n polyfills do you?
