### ISSUE TITLE
Constants in styled jsx combined with a PostCSS prefixing leads to a fatal error

### ISSUE THREAD

**Issue by sarukuku** [zeit/styled-jsx#91]
Have you tried constants in styled jsx markup plus using a PostCSS autoprefixer with styled jsx? This seems to cause a fatal error.

We're using this combo because styled jsx doesn't prefix flexbox correctly on its own.

**Comment by giuseppeg** [comment]
Are you using styled-jsx-postcss? If so this not related to this repo.

In styled-jsx prefixing is done by the [styles transformation library](https://github.com/zeit/styled-jsx/blob/master/lib/style-transform.js) which is a fork of stylis. 

If I am not mistaken in styled-jsx-postcss PostCSS runs after Stylis (maybe you can verify that) – anyway can you show the CSS that you are trying to preprocess?

**Comment by giuseppeg** [comment]
@sarukuku any update?

**Comment by sarukuku** [comment]
@giuseppeg so sorry about the delay, I've been really busy. I'll try to get back to this issue in the beginning of next week I'm again working with styled-jsx & next related project.

**Comment by giuseppeg** [comment]
@sarukuku no worries and no rush, I just wanted to know if you are using styled-jsx-postcss. If that's the case we should move the issue to that repo

**Comment by babenzele** [comment]
link for reference: [styled-jsx-postcss](https://github.com/giuseppeg/styled-jsx-postcss)

**Comment by giuseppeg** [comment]
styled-jsx-postcss doesn't support string interpolation yet
