### ISSUE TITLE
Is there a way to configure prefixing on styled jsx?

### ISSUE THREAD

**Issue by sarukuku** [zeit/styled-jsx#92]
I'm thinking something you have with autoprefixer like `last 2 versions` or similar.

**Comment by giuseppeg** [comment]
nope we don't use autoprefixer at all

**Comment by giuseppeg** [comment]
prefixing is done by https://github.com/zeit/styled-jsx/blob/master/lib/style-transform.js

**Comment by sarukuku** [comment]
Ok! But is there a way to configure what it prefixes in some way?

**Comment by giuseppeg** [comment]
No

**Comment by giuseppeg** [comment]
maybe you can configure autoprefixer to run on prefixed rules as well (if that's an option) and ask him to autoprefix the remaining rules https://github.com/postcss/autoprefixer#how-to-work-with-legacy--webkit--only-code

**Comment by babenzele** [comment]
prefixing with postcss: https://github.com/giuseppeg/styled-jsx-postcss
